'use client';
import {useEffect,useState,useRef} from 'react';
import RebalancePanel from './rebalance';
import CashRaisingPanel from './cash-raising';
import InflowsPanel from './inflows';
import RecurringPanel from './recurring';
import MandateRouteReview from './mandate-route-review';
import type {CapitalView,CapitalPolicy,CapitalCheckpoint,MandateInput,PlanResult,InstrumentPassport,InvestmentPolicy,SavedInvestmentMandate,ResearchProposal} from '@mandate/domain';
function investmentRules(m:MandateInput):InvestmentPolicy{return {allocations:m.allocations,maxIssuerBps:m.maxIssuerBps,maxCostBps:m.maxCostBps,allowLeveraged:m.allowLeveraged,representationAllowlist:[],exposureScope:'tracked-holdings-pending-proposed'};}
function ruleKey(p:InvestmentPolicy){return JSON.stringify({...p,representationAllowlist:[...p.representationAllowlist].sort()});}
function units(value:string,decimals=18){
 const n=BigInt(value),scale=10n**BigInt(decimals),fraction=(n%scale).toString().padStart(decimals,'0').replace(/0+$/,'');
 return (n/scale).toLocaleString('en-US')+(fraction?'.'+fraction:'');
}
function usdEstimate(value:string){
 const raw=BigInt(value),cents=(raw+5n*10n**15n)/10n**16n;
 if(raw>0n&&cents===0n)return '<$0.01';
 return '$'+(cents/100n).toLocaleString('en-US')+'.'+(cents%100n).toString().padStart(2,'0');
}
const errors:Record<string,string>={STALE_ACCOUNT:'Cash rules or reservations changed. Refresh capital to review the latest state before saving.',FRESH_CAPITAL_REQUIRED:'Refresh capital before planning.',CAPITAL_READ_UNAVAILABLE:'The chain read failed. Planning capacity is unknown; retry Refresh capital.',WALLET_SESSION_REQUIRED:'Reconnect your wallet to access its saved ledger.',INVALID_CAPITAL_POLICY:'Use non-negative amounts with no more than 18 decimal places.'};
Object.assign(errors,{STALE_MANDATE:'The saved mandate changed elsewhere. Reload the page to review its latest revision.',STALE_PROPOSAL_INPUTS:'Wallet records changed while planning. Refresh capital and try again.',INFLOW_PROOF_UNAVAILABLE:'The receipt could not be verified. It needs a successful BNB Chain USDT receipt, a canonical block and 12 confirmations.',STALE_INFLOW_REVIEW:'The receipt review changed. Reload its latest history before trying again.',INELIGIBLE_INFLOW:'Only reviewed external funding with current verified evidence can propose an allocation.',INFLOW_ALREADY_PROPOSED:'This transaction already has a linked initial proposal. Use its history to refresh and compare.',INFLOW_PROOF_CONFLICT:'Receipt facts changed. Reconciliation is required; the old review cannot approve a new proposal.',INVALID_INFLOW_REQUEST:'Enter a complete BNB Chain transaction hash.',INVALID_CASH_RAISING_REQUEST:'Use a positive cash target with no more than 18 decimal places.',INVALID_INVESTMENT_POLICY:'Use unique targets totaling 100%, valid issuer/cost limits and unique token contracts.',ACCOUNT_NOT_FOUND:'Refresh capital before saving investment rules.',CAPITAL_STALE:'Refresh capital before saving a proposal.',CAPITAL_UNKNOWN:'Capital is unresolved. Refresh before saving a proposal.'});
Object.assign(errors,{INVALID_RECURRING_SCHEDULE:'Choose a valid frequency, scenario and start time.',INVALID_RECURRING_START:'Choose a start time between now and one year ahead.',SAVED_MANDATE_REQUIRED:'Save investment rules before creating a schedule.',RECURRING_REQUEST_CONFLICT:'This schedule request was already used with different settings. Change the settings and retry.',RECURRING_LIMIT:'This wallet already has 20 active or paused schedules.',STALE_RECURRING_SCHEDULE:'The schedule changed elsewhere. Its latest state has been reloaded.',RECURRING_TRANSITION_INVALID:'This schedule has already changed state. Review its latest status.',RECURRING_NOT_FOUND:'This schedule is no longer available for this wallet.'});
async function request(url:string,body?:unknown){
 const r=await fetch('/api/v1/capital'+url,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});
 const data=await r.json();if(!r.ok)throw new Error(errors[data.error]??'Capital request failed. Refresh or reconnect and retry.');return data;
}
export type CapitalSection='overview'|'cash'|'plan'|'holdings'|'rebalance'|'cash-raising'|'inflows'|'recurring'|'records';
type History={items:{id:string;record:CapitalCheckpoint}[];policies:{revision:number;record:CapitalPolicy;created_at:string}[]};
export default function CapitalPanel({mandate,section='overview'}:{mandate:MandateInput;section?:CapitalSection}){
 const [capital,setCapital]=useState<CapitalView|null>(null),[policy,setPolicy]=useState<CapitalPolicy>({reserveFloor:'0',operatingBudget:'0',obligations:[]});
 const [representations,setRepresentations]=useState<InstrumentPassport[]>([]),[approved,setApproved]=useState<string[]>([]);
 const [rules,setRules]=useState<InvestmentPolicy>(()=>investmentRules(mandate)),[saved,setSaved]=useState<SavedInvestmentMandate|null>(null),[mandateHistory,setMandateHistory]=useState<SavedInvestmentMandate[]>([]),[proposals,setProposals]=useState<ResearchProposal[]>([]),[rulesLoaded,setRulesLoaded]=useState(false),[proposalId,setProposalId]=useState<string|null>(null);
 const [newTarget,setNewTarget]=useState('');
 const revalidationRequests=useRef<Record<string,string>>({});
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[plan,setPlan]=useState<PlanResult|null>(null),[history,setHistory]=useState<History|null>(null),[now,setNow]=useState(Date.now());
 function accept(value:CapitalView){setCapital(value);setPolicy(value.policy);setDirty(false);setNow(Date.now());}
 useEffect(()=>{
  let active=true;void request('').then(value=>{if(active)accept(value);}).catch(e=>{if(active)setError(e.message);});
  const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{active=false;clearInterval(timer);};
 },[]);
 const externalRulesKey=JSON.stringify(investmentRules(mandate));
 useEffect(()=>{setPlan(null);},[mandate]);
 useEffect(()=>{setRules(previous=>({...JSON.parse(externalRulesKey),representationAllowlist:previous.representationAllowlist}));},[externalRulesKey]);
 useEffect(()=>{let active=true;void request('/mandates').then(v=>{if(!active)return;setSaved(v.latest);setMandateHistory(v.history);if(v.latest){setRules(v.latest.policy);setApproved(v.latest.policy.representationAllowlist);}setRulesLoaded(true);}).catch(e=>{if(active)setError(e.message);});void request('/proposals').then(v=>{if(active)setProposals(v.items);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 useEffect(()=>{let active=true;void fetch('/api/v1/instruments/passports').then(r=>r.ok?r.json():Promise.reject()).then(v=>{if(active)setRepresentations(v.items);}).catch(()=>{});return()=>{active=false;};},[]);
 const visiblePositions=capital?.portfolio?.positions.filter(p=>{
  if(p.rawAtomic===null||p.valueAtomic===null)return true;
  return p.markState!=='ZERO'||BigInt(p.rawAtomic)>0n||BigInt(p.valueAtomic)>0n;
 })??[];
 const age=capital?.checkpoint?now-Date.parse(capital.checkpoint.observedAt):Infinity;
 const fresh=capital?.state==='OBSERVED'&&age>=0&&age<=60000;
 const state=capital?.state==='OBSERVED'&&!fresh?'STALE':capital?.state??'NOT_OBSERVED';
 const draft={...rules,representationAllowlist:approved};
 const mandateDirty=!saved||ruleKey(draft)!==ruleKey(saved.policy);
 function editRules(next:InvestmentPolicy){setRules(next);setPlan(null);setProposalId(null);}
 const remainingTargets=[...new Set(representations.map(i=>i.underlying))].filter(u=>!rules.allocations.some(a=>a.underlying===u));
 function changeTargets(targets:string[]){const base=Math.floor(10000/targets.length);editRules({...rules,allocations:targets.map((underlying,n)=>({underlying,weightBps:base+(n===0?10000-base*targets.length:0)}))});}
 async function saveRules(){const value=await request('/mandates',{policy:draft,expectedRevision:saved?.revision??0});setSaved(value.latest);setRules(value.latest.policy);setApproved(value.latest.policy.representationAllowlist);accept(value.capital);setPlan(null);setMandateHistory((await request('/mandates')).history);}
 async function propose(){const value=await request('/proposals',{mandateRevision:saved!.revision,scenario:mandate.scenario,requestId:crypto.randomUUID()});setPlan(value.proposal.result);setProposalId(value.proposal.id);setProposals((await request('/proposals')).items);}
 async function revalidate(p:ResearchProposal){const key=p.id+':'+saved!.revision+':'+mandate.scenario,requestId=revalidationRequests.current[key]??=crypto.randomUUID();try{const value=await request('/proposals/revalidate',{proposalId:p.id,mandateRevision:saved!.revision,scenario:mandate.scenario,requestId});accept(value.capital);setHistory(null);setPlan(value.proposal.inputs.funding.accountRevision===value.capital.revision?value.proposal.result:null);setProposalId(value.proposal.id);setProposals((await request('/proposals')).items);delete revalidationRequests.current[key];}catch(e){setPlan(null);if((e as Error).message===errors.CAPITAL_READ_UNAVAILABLE)setCapital(previous=>previous?{...previous,state:'UNKNOWN',availableAtomic:'0'}:null);throw e;}}
 function edit(next:CapitalPolicy){setPolicy(next);setDirty(true);setPlan(null);}
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);setPlan(null);}finally{setBusy(false);}}
 async function refresh(){setPlan(null);try{accept(await request('/refresh',{}));setHistory(null);}catch(e){setCapital(previous=>previous?{...previous,state:'UNKNOWN',availableAtomic:'0'}:null);throw e;}}
 const titles:Record<CapitalSection,string>={overview:'Your wallet at a glance',cash:'Cash rules and commitments',plan:'Investment rules and proposals',holdings:'Tracked holdings',rebalance:'Target drift and rebalance','cash-raising':'Raise cash for a need',inflows:'Incoming funds',recurring:'Recurring checks',records:'Saved records and evidence'};
  return <section className="panel capital-panel" aria-label="Wallet cash and commitments">
  <div className="panel-title"><div><span className="eyebrow">{section==='overview'?'WALLET OVERVIEW':'WALLET PLANNING'}</span><h2>{titles[section]}</h2><p>{section==='overview'?'A current wallet reading, the cash you have protected, and your next planning step.':'Your saved rules and wallet readings stay available as you work.'}</p></div><div className="capital-head-actions">{section==='overview'?null:<a className="text-button" href="/portfolio-exit">Back to overview</a>}<button id="refresh-capital" className="text-button" disabled={busy} onClick={()=>void run(refresh)}>{busy?'Working…':'Refresh capital'}</button></div></div>
  <p className="capital-state" aria-live="polite">{state==='OBSERVED'?'Wallet read at BNB Chain block #'+capital?.checkpoint?.blockNumber:state==='STALE'?'The wallet reading is over one minute old. Refresh before planning.':state==='UNKNOWN'?'The wallet could not be read. Available cash is unknown.':'Refresh to read your wallet balances for this research session.'} · Planning view</p>
  {error&&<p role="alert" className="wallet-error">{error}</p>}
  {capital?.checkpoint&&<>
   <div className="capital-metrics">
    <div><span>{fresh?'Observed':'Last recorded'} USDT</span><strong>{units(capital.balanceAtomic)} USDT</strong></div>
    <div><span>Cash set aside</span><strong>{units(capital.protectedAtomic)} USDT</strong></div>
    <div><span>Pending holds</span><strong>{units(capital.heldAtomic)} USDT</strong></div>
    <div><span>Available after protections</span><strong>{fresh?units(capital.availableAtomic)+' USDT':'Unknown'}</strong></div>
   </div>
   {BigInt(capital.shortfallAtomic)>0n&&<p className="wallet-error">Cash is {units(capital.shortfallAtomic)} USDT below saved protections and pending holds. Existing holds remain attached to their plans.</p>}
   {section==='overview'&&<>
     <div className="capital-next-step" aria-label="Suggested next step"><div><span className="eyebrow">NEXT STEP</span><h3>{!fresh?'Refresh your wallet reading':!saved?'Save your investment rules':'Review your saved plan'}</h3><p>{!fresh?'The latest wallet reading is too old for a new plan. Refresh before making decisions.':!saved?'Set your targets, issuer limit and token versions before previewing with wallet cash.':'Your plan is saved. Review its targets and current wallet capacity before considering a separate route.'}</p></div>{!fresh?<button type="button" className="capital-next-action" disabled={busy} onClick={()=>void run(refresh)}>Refresh wallet</button>:<a className="capital-next-action" href="/plans">{saved?'Review investment plan':'Set investment rules'}</a>}</div>
     <div className="capital-overview-grid"><section><h3>Your holdings</h3><p>{capital.portfolio?.state==='KNOWN'?capital.portfolio.pendingCount+' pending plan'+(capital.portfolio.pendingCount===1?'':'s'):'Tracked exposure needs review'}</p>{visiblePositions.length?visiblePositions.slice(0,3).map(p=><div className="capital-overview-row" key={p.contract}><strong>{p.symbol}</strong><span>{p.valueAtomic===null?'Value unknown':usdEstimate(p.valueAtomic)+' estimated'}</span></div>):<p>No tracked token holdings in this wallet reading.</p>}<a href="/portfolio">View holdings →</a></section><section><h3>Your saved plan</h3>{saved?<><p>Revision {saved.revision} · research rules</p>{saved.policy.allocations.map(a=><div className="capital-overview-row" key={a.underlying}><strong>{a.underlying}</strong><span>{(a.weightBps/100).toFixed(0)}%</span></div>)}</>:<p>No investment rules saved yet.</p>}<a href="/plans">Review investment plan →</a></section></div>
     <nav className="capital-overview-tasks" aria-label="Planning tasks"><h3>Choose a task</h3><div><a href="/cash-rules">Protect cash <span>Reserve and commitments →</span></a><a href="/cash-raising">Plan a cash need <span>Estimate ways to raise it →</span></a></div><details><summary>More planning tools and records</summary><div><a href="/rebalance">Explore rebalance <span>Model target changes →</span></a><a href="/inflows">Review incoming funds <span>Check a transfer →</span></a><a href="/recurring">Recurring checks <span>Schedule research →</span></a><a href="/records">Records and evidence <span>Inspect saved decisions →</span></a></div></details></nav>
     <p className="footnote">The wallet remains in your control. This overview does not place a trade. The capped SPYon route has a separate eligibility and wallet review.</p>
    </>}
    {(section==='cash'||section==='plan')&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{accept(await request('/policy',{policy,expectedRevision:capital.revision}));setPlan(null);setHistory(null);});}}>
    {section==='cash'&&<>
    <div className="capital-fields">
     <label>Cash reserve · USDT<input aria-label="Ledger cash reserve" inputMode="decimal" value={policy.reserveFloor} onChange={e=>edit({...policy,reserveFloor:e.target.value})}/></label>
     <label>Operating budget · USDT<input aria-label="Ledger operating budget" inputMode="decimal" value={policy.operatingBudget} onChange={e=>edit({...policy,operatingBudget:e.target.value})}/></label>
    </div>
    <fieldset className="capital-obligations"><legend>Commitments</legend>
     {!policy.obligations.length&&<p>No commitments recorded.</p>}
     {policy.obligations.map((o,n)=><div className="capital-obligation" key={o.id}>
      <label>Name<input aria-label={`Commitment ${n+1} name`} value={o.label} onChange={e=>edit({...policy,obligations:policy.obligations.map((v,i)=>i===n?{...v,label:e.target.value}:v)})}/></label>
      <label>Amount · USDT<input aria-label={`Commitment ${n+1} amount`} inputMode="decimal" value={o.amount} onChange={e=>edit({...policy,obligations:policy.obligations.map((v,i)=>i===n?{...v,amount:e.target.value}:v)})}/></label>
      <label>Funding<select aria-label={`Commitment ${n+1} funding`} value={o.coverage} onChange={e=>edit({...policy,obligations:policy.obligations.map((v,i)=>i===n?{...v,coverage:e.target.value as 'reserve'|'additional'}:v)})}><option value="reserve">Covered by reserve</option><option value="additional">Additional to reserve</option></select></label>
      <button className="text-button" type="button" aria-label={`Remove commitment ${n+1}`} onClick={()=>edit({...policy,obligations:policy.obligations.filter((_,i)=>i!==n)})}>Remove</button>
     </div>)}
     <button className="text-button" type="button" disabled={policy.obligations.length>=20||busy} onClick={()=>edit({...policy,obligations:[...policy.obligations,{id:crypto.randomUUID(),label:'Commitment',amount:'0',coverage:'reserve'}]})}>Add commitment</button>
    </fieldset>
    <p className="footnote">Protection = the larger of your cash reserve or reserve-covered commitments, plus additional commitments and operating budget. Pending holds are deducted separately. These are Mandate records; funds remain in your wallet.</p>
    <div className="capital-actions">
     <button type="submit" className="text-button" disabled={busy||!dirty}>Save cash rules</button>

    </div>
    </>}
    {section==='plan'&&<>
    <fieldset className="capital-investment-rules" disabled={busy||!rulesLoaded}><legend>Saved investment rules</legend><p>{saved?'Saved revision '+saved.revision:'No investment rules saved'}{mandateDirty?' · Unsaved changes':''}</p><div className="capital-fields"><label>Maximum with one token issuer · %<input type="number" min="1" max="100" value={rules.maxIssuerBps/100} onChange={e=>editRules({...rules,maxIssuerBps:Math.round(Number(e.target.value)*100)})}/></label><label>Maximum cost · bps<input type="number" min="0" max="1000" value={rules.maxCostBps} onChange={e=>editRules({...rules,maxCostBps:Number(e.target.value)})}/></label>{rules.allocations.map((a,n)=><div key={a.underlying}><label>Target allocation {a.underlying} · %<input type="number" min="1" max="100" value={a.weightBps/100} onChange={e=>editRules({...rules,allocations:rules.allocations.map((v,i)=>i===n?{...v,weightBps:Number(e.target.value)*100}:v)})}/></label><button type="button" className="text-button" aria-label={'Remove target allocation '+a.underlying} disabled={rules.allocations.length===1} onClick={()=>{changeTargets(rules.allocations.filter(v=>v.underlying!==a.underlying).map(v=>v.underlying));setApproved(prev=>prev.filter(c=>!representations.some(i=>i.contract===c&&i.underlying===a.underlying)));}}>Remove target</button></div>)}</div><p className="field-help">100 bps = 1%. This limit applies to scenario previews and the live-route research check.</p><div className="capital-target-add"><label>Choose another investment<select aria-label="Choose another investment" value={remainingTargets.includes(newTarget)?newTarget:remainingTargets[0]??''} onChange={e=>setNewTarget(e.target.value)}>{remainingTargets.map(u=><option key={u} value={u}>{u}</option>)}</select></label><button type="button" className="text-button" disabled={!remainingTargets.length||rules.allocations.length>=6} onClick={()=>changeTargets([...rules.allocations.map(a=>a.underlying),remainingTargets.includes(newTarget)?newTarget:remainingTargets[0]])}>Add investment target</button></div><p className="footnote">Adding or removing a target resets targets to equal weights. Adjust them before saving; the total must be 100%.</p><label className="checkbox"><input type="checkbox" checked={!rules.allowLeveraged} onChange={e=>editRules({...rules,allowLeveraged:!e.target.checked})}/>Exclude leveraged tokens</label></fieldset>
    <fieldset className="capital-representations" disabled={busy||!rulesLoaded}><legend>Token versions to consider</legend><p>Choose the token contracts this research plan may consider. This does not make them tradeable or approve a trade.</p>{representations.filter(i=>rules.allocations.some(a=>a.underlying===i.underlying)||capital.portfolio?.positions.some(p=>p.contract===i.contract&&p.rawAtomic!==null&&BigInt(p.rawAtomic)>0n)).map(i=><label key={i.contract}><input type="checkbox" checked={approved.includes(i.contract)} onChange={e=>{setApproved(prev=>e.target.checked?[...prev,i.contract]:prev.filter(c=>c!==i.contract));setPlan(null);setProposalId(null);}}/>{i.symbol} · {i.issuer==='ondo'?'Ondo':'bStocks'}</label>)}</fieldset>
    <div className="capital-actions"><button id="save-investment-rules" type="button" className="text-button" disabled={busy||dirty||!rulesLoaded||!mandateDirty} onClick={()=>void run(saveRules)}>Save investment rules</button><button type="button" className="text-button" disabled={busy||dirty||!fresh||!rulesLoaded||mandateDirty} onClick={()=>void run(propose)}>Preview using wallet cash</button></div><p className="footnote">Save changes before previewing. These rules cover tracked holdings + pending plans + proposed net exposure, with cash excluded. Cash protections are saved separately. Each preview records a research proposal using the selected scenario conditions.</p>
    <p className="footnote">Rules revision {capital.policyRevision} · account revision {capital.revision}. The allocation preview uses your current target weights and cost/issuer limits with synthetic quotes. It does not reserve funds or authorize a trade.</p>
    </>}
   </form>}
   {section==='plan'&&<MandateRouteReview ready={Boolean(saved)&&!dirty&&!mandateDirty}/>}
   {section==='holdings'&&capital.portfolio&&<section className="capital-portfolio" aria-label="Tracked portfolio exposure">
    <h3>Tracked holdings and pending exposure</h3>
    <p>{capital.portfolio.state==='KNOWN'?'Tracked exposure resolved':'Exposure unresolved'} · {capital.portfolio.pendingCount} pending plan{capital.portfolio.pendingCount===1?'':'s'}</p>
    <p className="footnote">USD values are rounded estimates from token marks, not sale quotes. Exact token quantities remain below; modeled USDT assumes nominal 1:1 parity.</p>
    {visiblePositions.length>0?<div className="table-wrap"><table><thead><tr><th>Holding</th><th>Exact quantity</th><th>Est. USD</th></tr></thead><tbody>{visiblePositions.map(p=><tr key={p.contract}><td><strong>{p.symbol}</strong><small>{p.markState==='ZERO'?'Observed empty':p.markState==='FRESH'?'Fresh mark':p.markState==='STALE'?'Stale mark':'Unknown mark'}</small></td><td>{p.rawAtomic===null?'Unknown':units(p.rawAtomic,p.decimals)}</td><td>{p.valueAtomic===null?'Unknown':usdEstimate(p.valueAtomic)}</td></tr>)}</tbody></table></div>:<p>No tracked token holdings. Any pending plans remain counted above.</p>}
    <details className="capital-all-tokens"><summary>Inspect all {capital.portfolio.positions.length} tracked tokens and exact modeled values</summary><div className="table-wrap"><table><thead><tr><th>Token</th><th>Raw quantity</th><th>Exact USD model</th><th>Evidence</th></tr></thead><tbody>{capital.portfolio.positions.map(p=><tr key={p.contract}><td>{p.symbol}</td><td>{p.rawAtomic===null?'Unknown':units(p.rawAtomic,p.decimals)}</td><td>{p.valueAtomic===null?'Unknown':units(p.valueAtomic)}</td><td>{p.markState==='ZERO'?'Observed empty':p.markState==='FRESH'?'Fresh mark':p.markState==='STALE'?'Stale mark':'Unknown'}</td></tr>)}</tbody></table></div></details>
    <div className="capital-exposure-groups"><div><h4>By issuer · USD model</h4>{capital.portfolio.byIssuer.length?capital.portfolio.byIssuer.map(g=><p key={g.issuer}><strong>{g.issuer}</strong> · {usdEstimate(g.existingAtomic)} held + {usdEstimate(g.pendingAtomic)} pending</p>):<p>No known positive issuer exposure.</p>}</div><div><h4>By underlying · USD model</h4>{capital.portfolio.byUnderlying.length?capital.portfolio.byUnderlying.map(g=><p key={g.underlying}><strong>{g.underlying}</strong> · {usdEstimate(g.existingAtomic)} held + {usdEstimate(g.pendingAtomic)} pending</p>):<p>No known positive underlying exposure.</p>}</div></div>
    {capital.portfolio.reasons.length>0&&<details><summary>Review {capital.portfolio.reasons.length} unresolved exposure check{capital.portfolio.reasons.length===1?'':'s'}</summary>{capital.portfolio.reasons.map((r,n)=><p key={n}>{r}</p>)}</details>}
   </section>}
   {section==='rebalance'&&<RebalancePanel saved={saved} scenario={mandate.scenario} fresh={fresh} dirty={dirty||mandateDirty} busy={busy} request={request} run={run}/>}
   {section==='cash-raising'&&<CashRaisingPanel saved={saved} scenario={mandate.scenario} fresh={fresh} dirty={dirty||mandateDirty} busy={busy} request={request} run={run}/>}
   {section==='inflows'&&<InflowsPanel saved={saved} scenario={mandate.scenario} fresh={fresh} dirty={dirty||mandateDirty} busy={busy} request={request} run={run} onReview={c=>{setCapital(c);setNow(Date.now());setPlan(null);setProposalId(null);}} onProposal={(p,c)=>{if(c)accept(c);setPlan(p.result);setProposalId(p.id);setProposals(previous=>[p,...previous.filter(v=>v.id!==p.id)].slice(0,20));}}/>}
   {section==='plan'&&plan&&fresh&&<div className="capital-preview" aria-live="polite"><h3>Wallet cash with illustrative quote costs</h3><p>{plan.status==='feasible'?'This example fits your wallet cash and saved rules.':'No allocation is available.'}</p><p>Research budget: {units(plan.investableAtomic,plan.decimals)} USDT</p>{plan.legs.map(leg=><p key={leg.instrumentId}>{leg.underlying} · {leg.issuer} · {units(leg.grossAtomic,plan.decimals)} USDT budget</p>)}{plan.issuerExposure.length>0&&<><h4>Issuer shares after the proposal</h4>{plan.issuerExposure.map(i=><p key={i.issuer}>{i.issuer}: {(i.shareBps/100).toFixed(2)}% · tracked holdings + pending + proposed net</p>)}</>}<p>{plan.reasons.join(' ')}</p></div>}
   {section==='plan'&&proposalId&&plan&&fresh&&<p className="footnote">Recorded proposal {proposalId} · mandate revision {saved?.revision}. No cash was reserved.</p>}
   {section==='plan'&&<section className="capital-proposal-history" aria-label="Research proposal history"><h3>Research proposal history</h3><p className="footnote">Last 20 proposals. These are recorded decisions, not live quotes or trading permission.</p>{!proposals.length&&<p>No recorded proposals.</p>}{proposals.map(p=><details key={p.id} data-proposal-id={p.id}><summary>{p.result.status==='feasible'?'Model fit':'No allocation'} · mandate {p.mandateRevision} · {new Date(p.createdAt).toLocaleString()}</summary><p>Recorded research · {p.mandateRevision!==saved?.revision||p.inputs.funding.accountRevision!==capital.revision?'inputs have changed':'refresh required before another proposal'}</p><p>Decision {p.result.decisionId} · {p.scenario} synthetic quotes · cash rules {p.inputs.cashPolicyRevision} · block #{p.inputs.checkpoint.blockNumber}</p>{p.inflow&&<p className="footnote">Incoming-funds proposal · transaction {p.inflow.transactionHash} · allocation cap {units(p.inflow.budgetCapAtomic)} USDT. Receipt import did not credit cash.</p>}<p>Recorded budget: {units(p.result.investableAtomic,p.result.decimals)} USDT. Proposed legs: {p.result.legs.map(l=>l.underlying+' / '+l.issuer).join(', ')||'None'}.</p><p>{p.result.reasons.join(' ')}</p>{p.revalidation&&<section className="capital-comparison" aria-label="Proposal comparison"><h4>{p.revalidation.state==='UNCHANGED'?'No modeled input changes':'Research inputs changed'}</h4><p className="footnote">Compared with proposal {p.revalidation.parentProposalId}. {p.revalidation.note}</p>{p.revalidation.changes.map((c,n)=><details key={n}><summary>{c.label} · {c.category}</summary><div className="capital-comparison-values"><div><strong>Before</strong><pre>{c.before}</pre></div><div><strong>After</strong><pre>{c.after}</pre></div></div></details>)}</section>}<p className="footnote">Refresh and compare uses saved mandate revision {saved?.revision??'None'} and the {mandate.scenario} synthetic scenario. The original proposal remains recorded.</p><button type="button" className="text-button" disabled={busy||dirty||!rulesLoaded||mandateDirty||!saved} onClick={()=>void run(()=>revalidate(p))}>Refresh and compare</button><details><summary>Inspect recorded input snapshot</summary><pre>{JSON.stringify(p.inputs,null,2)}</pre></details></details>)}</section>}
   {section==='records'&&mandateHistory.length>0&&<details className="capital-mandate-history"><summary>{mandateHistory.length} saved mandate revision{mandateHistory.length===1?'':'s'}</summary>{mandateHistory.map(m=><div key={m.id}><p>Revision {m.revision} · {new Date(m.createdAt).toLocaleString()} · issuer cap {m.policy.maxIssuerBps/100}% · cost limit {m.policy.maxCostBps} bps</p><p>{m.policy.allocations.map(a=>a.underlying+' '+a.weightBps/100+'%').join(', ')} · {m.policy.allowLeveraged?'Leverage allowed for research':'Leverage excluded'} · {m.policy.representationAllowlist.length} exact representations</p><details><summary>Inspect saved rules</summary><pre>{JSON.stringify(m.policy,null,2)}</pre></details></div>)}</details>}
   {section==='records'&&<button type="button" className="text-button" disabled={busy} onClick={()=>void run(async()=>setHistory(await request('/history')))}>View wallet snapshots</button>}
    {section==='records'&&history&&<details open><summary>{history.items.length} recorded checkpoint{history.items.length===1?'':'s'} · tracked instrument history</summary>
    {history.items.map(row=><div className="capital-checkpoint" key={row.id}><strong>Block #{row.record.blockNumber}</strong><span>{new Date(row.record.observedAt).toLocaleString()}</span><code>{row.record.blockHash}</code><p>{units(row.record.balanceAtomic)} USDT · {row.record.positions.map(p=>`${(p.rawAtomic===null?'Unknown':units(p.rawAtomic,p.decimals))} raw ${p.symbol}, ${(p.adjustedAtomic===null?'Unknown':units(p.adjustedAtomic,p.decimals))} adjusted units (${p.accountingVersion})`).join('; ')}</p></div>)}
    {history.policies?.map(p=><div className="capital-checkpoint" key={'policy:'+p.revision}><strong>Cash rules revision {p.revision}</strong><span>{new Date(p.created_at).toLocaleString()}</span><p>Reserve {p.record.reserveFloor} USDT · operations {p.record.operatingBudget} USDT</p>{p.record.obligations.map(o=><p key={o.id}>{o.label}: {o.amount} USDT · {o.coverage==='reserve'?'covered by reserve':'additional'}</p>)}</div>)}
   </details>}
  </>}
  {section==='recurring'&&<RecurringPanel saved={saved} scenario={mandate.scenario} dirty={dirty||mandateDirty} hasCheckpoint={Boolean(capital?.checkpoint)} rulesLoaded={rulesLoaded} request={request} proposals={proposals} onProposals={setProposals}/>}
  {section==='records'&&<p className="footnote">A checkpoint is an RPC observation with a block hash, not a finalized settlement proof. Coverage includes USDT and the 14 researched tokens. Issuer limits cover these tracked investments, pending plans and proposed net exposure; other wallet assets and cash are excluded. USD marks and modeled USDT budgets assume nominal 1:1 parity. A failed read or changed block cannot clear funds for planning.</p>}
 </section>;
}
