'use client';
import {useEffect,useRef,useState} from 'react';
import type {ResearchCashRaising,SavedInvestmentMandate,MandateInput} from '@mandate/domain';
function units(value:string|null,decimals=18,full=false){if(value===null)return 'Unknown';const n=BigInt(value),scale=10n**BigInt(decimals),fraction=(n%scale).toString().padStart(decimals,'0'),shown=(full||n>0n&&n<10n**BigInt(Math.max(decimals-6,0))?fraction:fraction.slice(0,6)).replace(/0+$/,'');return (n/scale).toLocaleString('en-US')+(shown?'.'+shown:'');}
export default function CashRaisingPanel({saved,scenario,fresh,dirty,busy,request,run}:{saved:SavedInvestmentMandate|null;scenario:MandateInput['scenario'];fresh:boolean;dirty:boolean;busy:boolean;request:(url:string,body?:unknown)=>Promise<any>;run:(action:()=>Promise<void>)=>Promise<void>}){
 const [target,setTarget]=useState('10'),[records,setRecords]=useState<ResearchCashRaising[]>([]),[selected,setSelected]=useState<string|null>(null),[loadError,setLoadError]=useState('');const retry=useRef<{key:string;id:string}|null>(null);
 const valid=/^(0|[1-9]\d{0,12})(\.\d{1,18})?$/.test(target)&&/[1-9]/.test(target);
 useEffect(()=>{let active=true;void request('/cash-raising').then(v=>{if(active)setRecords(v.items);}).catch(e=>{if(active)setLoadError(e.message);});return()=>{active=false;};},[]);
 async function preview(){const key=JSON.stringify({revision:saved!.revision,scenario,target}),requestId=retry.current?.key===key?retry.current.id:crypto.randomUUID();retry.current={key,id:requestId};const v=await request('/cash-raising',{mandateRevision:saved!.revision,scenario,target,requestId});setRecords(previous=>[v.cashRaising,...previous.filter(r=>r.id!==v.cashRaising.id)].slice(0,20));setSelected(v.cashRaising.id);setLoadError('');retry.current=null;}
 return <section className="capital-cash-raising" aria-label="Net cash-raising planner"><span className="eyebrow">INVESTMENTS → CASH TARGET</span><h3>Raise cash without using your reserve</h3><p>Use available cash first, then model sales to cover the rest after fees. Keep saved protections and pending cash holds in the wallet.</p>
  <div className="capital-fields"><label>Cash target · USDT<input aria-label="Cash-raising target" inputMode="decimal" value={target} disabled={busy} onChange={e=>setTarget(e.target.value)}/></label></div>
  <p className="footnote">This is the amount you want to take out, in addition to your protected cash and pending holds. An existing protection gap must be restored first. Pending positions cannot be sold.</p>
  <button type="button" className="text-button" disabled={busy||!fresh||dirty||!saved||!valid} onClick={()=>void run(preview)}>Preview cash target</button>
  {!valid?<p className="wallet-error">Enter a positive USDT amount with up to 18 decimal places.</p>:!saved||dirty?<p className="footnote">Save cash and investment rules before modeling.</p>:!fresh?<p className="footnote">Refresh capital before creating a new model.</p>:null}
  {loadError&&<p role="alert" className="wallet-error">{loadError}</p>}<p className="footnote">Last 20 recorded models. Costs and proceeds are research estimates; no withdrawal or trade is requested.</p>
  {!records.length&&<p>No recorded cash-target models.</p>}{records.map(record=>{const r=record.result;return <details key={record.id} data-cash-raising-id={record.id} open={selected===record.id}><summary>{r.status==='feasible'?'Cash target covered':r.status==='shortfall'?'Cash target shortfall':'Cash target blocked'} · {units(r.targetAtomic,18,true)} USDT · mandate {record.mandateRevision}</summary><p>Recorded research · {new Date(record.createdAt).toLocaleString()} · block #{record.inputs.checkpoint.blockNumber} · {record.scenario} synthetic costs</p>
   <div className="capital-metrics"><div><span>Available wallet cash · USDT</span><strong>{units(r.availableCashAtomic)}</strong></div><div><span>Net sales needed · USDT</span><strong>{units(r.saleNeededAtomic)}</strong></div><div><span>Modeled net sales · USDT</span><strong>{units(r.netSaleAtomic)}</strong></div><div><span>Modeled fees · USDT</span><strong>{units(r.feeAtomic)}</strong></div></div>
   <p>Saved protections: {units(r.protectedCashAtomic)} USDT · Pending holds: {units(r.heldCashAtomic)} USDT · Initial protection gap: {units(r.protectionGapAtomic)} USDT.</p>
   {r.status!=='blocked'&&<><p>Modeled payout covered: <strong>{units(r.modeledPayoutAtomic)} USDT</strong> · Target shortfall: <strong>{units(r.shortfallAtomic)} USDT</strong>.</p><p>Projected wallet cash after covered payout: {units(r.projectedCashAfterPayoutAtomic)} USDT · Remaining protection gap: {units(r.protectionGapAfterAtomic)} USDT.</p></>}
   {r.legs.length>0&&<div className="rebalance-stage"><h4>Modeled sales · settle before any payout</h4>{r.legs.map(l=><div key={l.instrumentId}><p><strong>Sell {units(l.quantityAtomic,l.tokenDecimals)} raw {l.symbol}</strong> · {l.issuer}</p><p>Estimated net proceeds: {units(l.cashAtomic)} USDT · fee {units(l.feeAtomic)} USDT · {l.costBps} bps</p></div>)}</div>}
   {r.remaining.length>0&&<><h4>Remaining investments · USD model</h4><div className="table-wrap"><table><thead><tr><th>Underlying</th><th>Held</th><th>Pending</th><th>Remaining share</th><th>Saved target</th></tr></thead><tbody>{r.remaining.map(g=><tr key={g.underlying}><td>{g.underlying}</td><td>{units(g.heldAtomic)}</td><td>{units(g.pendingAtomic)}</td><td>{g.shareBps===null?'No remaining exposure':(g.shareBps/100).toFixed(2)+'%'}</td><td>{(g.targetWeightBps/100).toFixed(2)}%</td></tr>)}</tbody></table></div><p className="footnote">Cash raising can move investments away from target weights. Remaining issuer shares: {r.issuerExposure.map(e=>e.issuer+' '+(e.shareBps/100).toFixed(2)+'%').join(', ')||'None'}.</p></>}
   {r.excluded.length>0&&<details><summary>{r.excluded.length} held representation{r.excluded.length===1?'':'s'} excluded from sales</summary>{r.excluded.map(e=><p key={e.instrumentId}>{e.symbol}: {e.reason}</p>)}</details>}{r.reasons.map((reason,n)=><p key={n}>{reason}</p>)}
   <p className="footnote">Amounts are shown up to six decimals; payout targets and very small amounts retain more precision. The snapshot preserves full precision. Estimated proceeds are not available cash. Execution still requires market eligibility, validated routes, executable sell quotes, gas, simulation and transaction authorization. No funds are reserved or transferred.</p><details><summary>Inspect recorded cash-target snapshot</summary><pre>{JSON.stringify(record,null,2)}</pre></details>
  </details>;})}</section>;
}
