'use client';
import {useEffect,useRef,useState} from 'react';
import type {InflowRecord,InflowReview,SavedInvestmentMandate,MandateInput,ResearchProposal,CapitalView} from '@mandate/domain';
const labels={external:'Reviewed external funding',internal:'Internal movement',conversion:'Conversion or other outflow',unclassified:'Source needs review'};
function units(value:string){const n=BigInt(value),u=10n**18n,f=(n%u).toString().padStart(18,'0').replace(/0+$/,'');return (n/u).toLocaleString('en-US')+(f?'.'+f:'');}
export default function InflowsPanel({saved,scenario,fresh,dirty,busy,request,run,onProposal,onReview}:{saved:SavedInvestmentMandate|null;scenario:MandateInput['scenario'];fresh:boolean;dirty:boolean;busy:boolean;request:(url:string,body?:unknown)=>Promise<any>;run:(action:()=>Promise<void>)=>Promise<void>;onProposal:(proposal:ResearchProposal,capital?:CapitalView)=>void;onReview:(capital:CapitalView)=>void}){
 const [hash,setHash]=useState(''),[review,setReview]=useState<InflowReview>('unclassified'),[items,setItems]=useState<{record:InflowRecord;proposalId:string|null}[]>([]),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState('');const retry=useRef<Record<string,string>>({});
 const valid=/^0x[0-9a-fA-F]{64}$/.test(hash);
 async function history(){const v=await request('/inflows');setItems(v.items);setError('');}
 useEffect(()=>{let active=true;void request('/inflows').then(v=>{if(active)setItems(v.items);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function check(){const transactionHash=hash.toLowerCase(),old=items.find(i=>i.record.proof.transactionHash===transactionHash);const v=await request('/inflows/check',{transactionHash,review,expectedRevision:old?.record.revision??0});setSelected(v.record.id);if(v.capital)onReview(v.capital);await history();}
 async function change(record:InflowRecord,review:InflowReview){const v=await request('/inflows/check',{transactionHash:record.proof.transactionHash,review,expectedRevision:record.revision});setSelected(v.record.id);await history();}
 async function propose(record:InflowRecord){const key=record.proof.transactionHash+':'+saved!.revision+':'+scenario,requestId=retry.current[key]??=crypto.randomUUID();const v=await request('/inflows/propose',{transactionHash:record.proof.transactionHash,expectedReviewRevision:record.revision,mandateRevision:saved!.revision,scenario,requestId});onProposal(v.proposal,v.capital);delete retry.current[key];await history();}
 return <section className="capital-inflows" aria-label="Incoming funds review"><span className="eyebrow">RECEIPT → SOURCE REVIEW → PROPOSAL</span><h3>Review incoming funds</h3><p>Verify an incoming BNB Chain USDT transaction, then review its source. A balance increase alone is never counted as income.</p>
  <div className="capital-fields"><label>Transaction hash<input aria-label="Incoming transaction hash" autoComplete="off" placeholder="0x…" value={hash} disabled={busy} onChange={e=>setHash(e.target.value)}/></label><label>Source review<select aria-label="Incoming source review" value={review} disabled={busy} onChange={e=>setReview(e.target.value as InflowReview)}><option value="unclassified">Leave unclassified</option><option value="external">External funding</option><option value="internal">My own transfer / internal movement</option></select></label></div>
  <p className="footnote">Requires a successful receipt, matching USDT contract, canonical block and at least 12 confirmations. This is a confirmation threshold, not finalized settlement. Source labels are your review; sending-wallet ownership and taxable income are not independently established.</p>
  <button type="button" className="text-button" disabled={busy||!fresh||!valid} onClick={()=>void run(check)}>Verify incoming transfer</button>{!fresh&&<p className="footnote">Refresh capital before reviewing a receipt.</p>}{error&&<p className="wallet-error" role="alert">{error}</p>}
  <p className="footnote">Last 20 transaction reviews. Importing or reviewing a receipt never credits cash. Allocation uses a refreshed wallet checkpoint, excludes protections and holds, and is capped by this transaction’s net USDT inflow.</p>
  {!items.length&&<p>No reviewed incoming transactions.</p>}{items.map(({record:r,proposalId})=><details key={r.id} data-inflow-id={r.id} open={selected===r.id}><summary>{labels[r.classification.kind]} · {units(r.classification.netAtomic)} USDT · review {r.revision}</summary><p>Recorded receipt · block #{r.proof.blockNumber} · {r.classification.confirmations} confirmations at check · {new Date(r.proof.observedAt).toLocaleString()}</p><code>{r.proof.transactionHash}</code>{r.classification.reasons.map((reason,n)=><p key={n}>{reason}</p>)}
   <div className="capital-actions"><button type="button" className="text-button" disabled={busy||!fresh} onClick={()=>void run(()=>change(r,r.review))}>Recheck receipt</button><button type="button" className="text-button" disabled={busy||!fresh||r.classification.kind==='conversion'||r.knownSettlement||r.proof.transactionSender===r.proof.wallet||r.proof.incoming.some(l=>l.from==='0x'+'0'.repeat(40))} onClick={()=>void run(()=>change(r,'external'))}>Review as external funding</button><button type="button" className="text-button" disabled={busy||!fresh} onClick={()=>void run(()=>change(r,'internal'))}>Review as internal movement</button><button type="button" className="text-button" disabled={busy||dirty||!saved||!fresh||!r.classification.eligibleForProposal||!!proposalId} onClick={()=>void run(()=>propose(r))}>Propose allocation from inflow</button></div>
   {proposalId&&<p>Linked initial proposal: <code>{proposalId}</code>. Review it in Research proposal history. Further refreshes keep the same inflow cap.</p>}
   <p className="footnote">Conversions, known Mandate settlements and internal movements do not trigger external-funding proposals. Proposing rechecks the receipt and refreshes capital. No funds are reserved or trade authorized.</p><details><summary>Inspect recorded inflow review</summary><pre>{JSON.stringify(r,null,2)}</pre></details>
  </details>)}</section>;
}
