import type {Metadata} from 'next';
import Link from 'next/link';
import ProductHeader from './product-header';
import './landing.css';

export const metadata:Metadata={title:'Mandate | Know what a tokenized stock really costs',description:'Explore tokenized stocks on BNB Smart Chain. Mandate separates recorded evidence, current routes, wallet state and cash rules before a wallet request.'};

export default function LandingPage(){return <div className="product-site landing-next"><ProductHeader/>
 <main>
  <section className="landing-next-hero"><div className="landing-next-copy"><p className="product-eyebrow">BNB SMART CHAIN · TOKENIZED STOCKS</p><h1>Know what a tokenized stock really costs <em>before you buy it.</em></h1><p className="product-lede">Mandate checks the token, a fresh onchain route, your wallet and your cash rules before you decide whether to authorize a trade.</p><div className="landing-next-actions"><Link className="product-button" href="/market">Check the market</Link><a href="#method">See how Mandate works ↓</a></div><p className="landing-next-signin">Connecting a wallet proves ownership. It cannot move funds.</p></div>
   <div className="landing-next-example" aria-label="How a SPYon decision is checked"><div className="landing-next-example-head"><span className="product-eyebrow">EXAMPLE DECISION</span><strong>SPYon <small>· Ondo</small></strong><p>Tokenized exposure to the SPDR S&amp;P 500 ETF, not an ETF share.</p></div><ol><li><span>01 / IDENTITY</span><strong>Which token and issuer?</strong><small>Sourced contract and underlying</small></li><li><span>02 / CURRENT ROUTE</span><strong>What would this wallet receive?</strong><small>Fresh quote and reference required</small></li><li><span>03 / YOUR MONEY</span><strong>What remains after protected cash?</strong><small>Wallet balance and saved commitments</small></li><li><span>04 / AUTHORIZATION</span><strong>Do you approve the exact request?</strong><small>Separate confirmation in your wallet</small></li></ol><Link href="/asset/SPYon">Understand SPYon <span aria-hidden="true">↗</span></Link></div>
  </section>
  <section id="method" className="landing-next-method"><div><p className="product-eyebrow">ONE DECISION SYSTEM</p><h2>Explore. Understand. Plan. Verify.</h2><p>Every step answers a different question. A recorded observation never becomes a live offer; a valid route never becomes trade permission.</p></div><div className="landing-next-flow"><Link href="/market"><span>01</span><strong>Explore</strong><small>Find sourced stock tokens</small></Link><Link href="/asset/SPYon"><span>02</span><strong>Understand</strong><small>Inspect the issuer and evidence</small></Link><Link href="/portfolio"><span>03</span><strong>Plan</strong><small>Protect cash and set rules</small></Link><Link href="/plan/SPYon"><span>04</span><strong>Verify</strong><small>Check the current wallet route</small></Link></div></section>
  <section className="landing-next-proof"><div><p className="product-eyebrow">WHY ROUTE CHECKS MATTER · RECORDED 20 SEP 2026</p><h2>One recorded NVDA route changed in 15 minutes.</h2><p>For a quoted $10,000 NVDA / Ondo buy, the measured cost versus token reference moved from <strong>+133.71%</strong> at 16:45 UTC to <strong>−0.05%</strong> at 17:00 UTC.</p><p className="product-fine">Historical quotes, not completed trades, current prices or an opportunity. Mandate retains each original data line and SHA-256 proof.</p><Link href="/asset/NVDAon#history">Inspect the evidence ↗</Link></div><div className="landing-next-proof-values"><div><span>16:45 UTC</span><strong>+133.71%</strong><small>Recorded cost above reference</small></div><span aria-hidden="true">→</span><div><span>17:00 UTC</span><strong>−0.05%</strong><small>Recorded cost below reference</small></div></div></section>
  <section className="landing-next-roundtrip"><p className="product-eyebrow">BOUNDED MAINNET PILOT</p><div><h2>A complete SPYon buy and sell is accounted for.</h2><p>A separate 1 USDT wallet trial bought SPYon and sold the exact received quantity back for 0.993895 USDT before BNB network fees. Mandate verified confirmed receipts and token transfers for both swaps. Each approval and swap required its own wallet confirmation.</p><Link className="product-button secondary" href="/proof">Inspect the verified receipts</Link></div><p className="product-fine">This prior result is not a current offer. The broader stock-token catalogue remains research-only until each route passes its own checks.</p></section>
 </main>
 <footer className="landing-next-footer"><strong>Mandate</strong><p>Pre-trade decisions for tokenized stocks on BNB Smart Chain.</p><div><Link href="/market">Explore</Link><Link href="/portfolio">Portfolio</Link><Link href="/activity">Activity</Link><a href="https://github.com/abdoulore/mandate" target="_blank" rel="noreferrer">GitHub ↗</a></div></footer>
 </div>;}
