'use client';
import {useEffect,useState} from 'react';
import {evaluatePassport,type PassportCatalogue} from '@mandate/domain';
export default function Passports(){
 const [catalogue,setCatalogue]=useState<PassportCatalogue|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState('AAOIB'),[allowLeveraged,setAllowLeveraged]=useState(false),[requireDirectOwnership,setRequireDirectOwnership]=useState(false);
 useEffect(()=>{let active=true;const load=async()=>{try{const r=await fetch('/api/v1/instruments/passports',{cache:'no-store'});if(!r.ok)throw new Error();const value:PassportCatalogue=await r.json();if(active){setCatalogue(value);setError('');}}catch{if(active){setCatalogue(null);setError('Passport observations are unavailable. No research candidates are cleared.');}}};void load();const timer=setInterval(load,60000);return ()=>{active=false;clearInterval(timer);};},[]);
 const p=catalogue?.items.find(i=>i.symbol===selected);
 const results=catalogue?.items.map(i=>evaluatePassport(i,{allowLeveraged,requireDirectOwnership}))??[];
 const eligible=results.filter(r=>r.researchEligible).length,result=results.find(r=>r.symbol===selected);
 return <section className="panel passports" aria-label="Sourced instrument passports"><div className="panel-title"><div><h2>Token facts and risks</h2><p>Compare 14 token versions linked to 8 underlying investments. These are research records, not permission to trade.</p></div></div><div className="passport-policy"><label><input type="checkbox" checked={allowLeveraged} onChange={e=>setAllowLeveraged(e.target.checked)}/>Allow leveraged exposure</label><label><input type="checkbox" checked={requireDirectOwnership} onChange={e=>setRequireDirectOwnership(e.target.checked)}/>Require direct share ownership</label></div><p aria-live="polite" className="passport-count">{eligible} of {catalogue?.items.length??0} match your research filters. We still do not know whether your wallet can trade them.</p>{error&&<p role="alert">{error}</p>}{catalogue&&<><label className="passport-select">Choose a token<select value={selected} onChange={e=>setSelected(e.target.value)}>{catalogue.items.map(i=><option key={i.symbol} value={i.symbol}>{i.symbol} · {i.underlying} · {i.category}</option>)}</select></label><div className="passport-candidates">{results.filter(r=>!r.researchEligible).map(r=><p key={r.symbol}><strong>{r.symbol}</strong> — {r.reasons.join('; ')}</p>)}</div></>}{p&&<article><h3>{p.symbol} → {p.underlying}</h3><p>{p.category} · {p.leveraged?'Leveraged':'No leveraged target identified'} · BNB Chain</p><code className="passport-contract">{p.contract}</code><p><strong>{result?.researchEligible?'Matches research filters':'Excluded by research filters'}</strong> · Execution unavailable</p><dl className="passport-facts">{Object.entries(p.facts).map(([key,f])=><div key={key}><dt>{key}</dt><dd>{f.value}<small><a href={f.source} target="_blank" rel="noreferrer">Primary source</a> · {f.scope==='issuer-program'?'Issuer program guidance':'Underlying investment'} · checked {f.checkedAt} · legal effective date unknown</small></dd></div>)}</dl><p><a href={p.leverageSource??p.facts.exposure.source} target="_blank" rel="noreferrer">Leverage classification source</a>{p.category==='Stock'?' · classification inferred from stock exposure':''}</p><div className="passport-observation"><h4>Token-to-underlying profile: {p.profile.state}</h4><p>{p.profile.underlyingName??'Underlying name unconfirmed'}</p><p>Reported shares per raw token: {p.profile.tokenToShareRatio??'Unknown'}. This is an API observation, not a verified display multiplier.</p><p>Observed {p.profile.observedAt?new Date(p.profile.observedAt).toLocaleString():'never'} · expires after 24 hours{p.profile.reason?' · '+p.profile.reason:''}</p></div><h4>Still unknown</h4><ul>{p.unknowns.map(u=><li key={u}>{u}</li>)}</ul><p className="footnote">Matching your filters only permits more research. It does not verify wallet eligibility, transaction safety, or legal rights. The scenario planner is separate.</p></article>}</section>;
}
