'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import './regime.css';

type Source={file:string;line:number;sha256?:string;lineSha256?:string};
type CostPoint={ts:string;pct:number|null;err?:string|number;route?:string;venueCount?:number;source:Source;broken:boolean|null};
type SweepPoint={ts:string;pct:number|null;err?:string|number;source:Source};
type Frame={ts:string;openCount?:number;totalCount?:number;source:Source};
type RegimeResult={token:string;platform:string;side:'buy';usd:10000;points:CostPoint[];sweepObservations?:SweepPoint[];flips:{ts:string;from:'broken'|'healthy';to:'broken'|'healthy'}[];brokenCount:number;observedCount:number;brokenPercent:number|null;windowStart:string|null;windowEnd:string|null;outages:Frame[];coverageGaps?:Frame[];availableTokens:{token:string;platform:string}[]};
export type CostReview={ticker:string;platform:string;side:string;usd:number;observation:'measured'|'none';observedAt:string|null;pct:number|null;route:string|null;errorCode:string|null;source:{file:string;line:number;sha256:string}|null;executable:false;note:string};

const pct=(value:number)=>`${value>=0?'+':''}${value.toFixed(2)}%`;
const utc=(value:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value))+' UTC';
const day=(value:number)=>new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',month:'short',day:'numeric'}).format(value);
const sourceHash=(source:Source)=>source.sha256??source.lineSha256??'Hash unavailable';
const sourceLabel=(source:Source)=>`${source.file}:${source.line}`;

function SourceProof({source}:{source:Source}){
 return <div className="regime-source"><span>Original data line</span><code>{sourceLabel(source)}</code><span>Proof hash (SHA-256)</span><code>{sourceHash(source)}</code></div>;
}

export function CostReviewEvidence({review}:{review:CostReview}){
 const measured=review.observation==='measured'&&review.pct!==null;
 return <div className="cost-review-evidence" aria-label={`${review.ticker} execution cost evidence`}><div className="cost-review-value"><span className="regime-kicker">HISTORICAL · READ ONLY</span><strong>{measured?pct(review.pct!):'No measured cost'}</strong><span>{review.ticker} / {review.platform} · ${review.usd.toLocaleString('en-US')} {review.side}</span>{review.observedAt&&<time dateTime={review.observedAt}>{utc(review.observedAt)}</time>}{review.route&&<span>Recorded route: {review.route}</span>}{!measured&&review.errorCode&&<span>Last recorded error: {review.errorCode}</span>}</div><div className="cost-review-context"><p>{review.note}</p>{review.source&&<SourceProof source={review.source}/>}<small>{measured?'One recorded measurement':'Recorded evidence only'}; no present quote or execution permission.</small></div></div>;
}

function CostChart({result,selectedIndex,onSelect}:{result:RegimeResult;selectedIndex:number;onSelect:(index:number)=>void}){
 const points=result.points;
 const measured=points.map((point,index)=>({point,index,time:Date.parse(point.ts)})).filter(x=>x.point.pct!==null&&Number.isFinite(x.time));
 if(!measured.length)return <div className="regime-no-series"><strong>No $10,000 buy cost series was recorded for this token.</strong><p>A sweep observation, if present below, is one measurement. It cannot establish a regime or recovery.</p></div>;
 const width=960,height=326,left=62,right=20,top=22,bottom=45,plotWidth=width-left-right,plotHeight=height-top-bottom;
 const t0=measured[0]!.time,t1=measured.at(-1)!.time||t0+1;
 const transformed=measured.map(x=>Math.asinh(x.point.pct!));
 const min=Math.min(-Math.asinh(1),...transformed),max=Math.max(Math.asinh(1),...transformed),span=max-min||1;
 const low=min-span*0.07,high=max+span*0.07;
 const x=(time:number)=>left+(time-t0)/Math.max(t1-t0,1)*plotWidth;
 const y=(value:number)=>top+(high-Math.asinh(value))/(high-low)*plotHeight;
 const selected=points[selectedIndex],selectedTime=selected?Date.parse(selected.ts):NaN;
 const yTicks=[-1,0,1,10,100,1000,10000].filter(value=>Math.asinh(value)>=low&&Math.asinh(value)<=high);
 const dayTicks=Array.from({length:7},(_,index)=>t0+(t1-t0)*index/6);
 return <div className="regime-chart-wrap"><div className="regime-chart-scroll"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${result.token} ${result.platform} measured $10,000 buy cost over time; vertical scale is symmetric logarithmic`}>
   <rect x={left} y={top} width={plotWidth} height={plotHeight} className="regime-plot"/>
   {result.outages.filter(frame=>{const time=Date.parse(frame.ts);return time>=t0&&time<=t1;}).map((frame,index)=><g key={`outage-${frame.ts}-${index}`}><rect x={x(Date.parse(frame.ts))-3} y={top} width="6" height={plotHeight} className="regime-pause-band"/><title>{`Ondo recorded platform-wide paused at ${utc(frame.ts)}`}</title></g>)}
   {yTicks.map(value=><g key={value}><line x1={left} x2={width-right} y1={y(value)} y2={y(value)} className={value===1?'regime-threshold':'regime-grid'}/><text x={left-10} y={y(value)+4} textAnchor="end" className="regime-axis">{value===0?'0':`${value>0?'+':''}${value}%`}</text></g>)}
   {dayTicks.map((time,index)=><g key={index}><line x1={x(time)} x2={x(time)} y1={top} y2={height-bottom} className="regime-grid-vertical"/><text x={x(time)} y={height-14} textAnchor="middle" className="regime-axis">{day(time)}</text></g>)}
   {points.slice(1).map((point,index)=>{const previous=points[index];if(point.pct===null||previous?.pct===null)return null;const start=Date.parse(previous.ts),end=Date.parse(point.ts);if(!Number.isFinite(start)||!Number.isFinite(end)||end-start>30*60_000)return null;return <line key={`segment-${index}`} x1={x(start)} y1={y(previous.pct)} x2={x(end)} y2={y(point.pct)} className={point.pct>1||previous.pct>1?'regime-line broken':'regime-line'}/>;})}
   {measured.map(({point,index,time})=><circle key={`${point.source.file}:${point.source.line}`} cx={x(time)} cy={y(point.pct!)} r={selectedIndex===index?6:3.5} className={`regime-dot ${point.pct!>1?'broken':''} ${selectedIndex===index?'selected':''}`} onClick={()=>onSelect(index)}><title>{`${utc(point.ts)} · ${pct(point.pct!)} · ${sourceLabel(point.source)}`}</title></circle>)}
   {points.map((point,index)=>point.pct===null&&Number.isFinite(Date.parse(point.ts))?<rect key={`missing-${index}`} x={x(Date.parse(point.ts))-2} y={height-bottom-4} width="4" height="8" className="regime-missing" onClick={()=>onSelect(index)}><title>{`${utc(point.ts)} · no measured cost · ${sourceLabel(point.source)}`}</title></rect>:null)}
   {Number.isFinite(selectedTime)&&selectedTime>=t0&&selectedTime<=t1&&<line x1={x(selectedTime)} x2={x(selectedTime)} y1={top} y2={height-bottom} className="regime-selection"/>}
  </svg></div><p className="regime-chart-note">Swipe across the chart for the full history. Each dot is one recorded buy quote. Red means the quoted cost was more than 1% above reference value. Bottom ticks have no measured cost. Shading marks reported Ondo pauses. The vertical scale compresses large values; displayed percentages use unscaled data rounded to two decimals.</p></div>;
}

export default function RegimeView(){
 const [token,setToken]=useState('NVDA'),[platform,setPlatform]=useState('ondo');
 const evidenceRef=useRef<HTMLElement|null>(null);
 const [result,setResult]=useState<RegimeResult|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selectedIndex,setSelectedIndex]=useState(0);
 const [reviewExample,setReviewExample]=useState(false),[review,setReview]=useState<CostReview|null>(null),[reviewError,setReviewError]=useState(''),[reviewLoading,setReviewLoading]=useState(true);
 useEffect(()=>{const controller=new AbortController();const ticker=reviewExample?'AAOIB':token,issuer=reviewExample?'bstock':platform,usd=reviewExample?10:10000;setReview(null);setReviewError('');setReviewLoading(true);
  void fetch(`/api/v1/cost-review?ticker=${encodeURIComponent(ticker)}&platform=${encodeURIComponent(issuer)}&side=buy&usd=${usd}`,{signal:controller.signal,cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'Could not read execution cost evidence.');return body as CostReview;}).then(setReview).catch(reason=>{if(!controller.signal.aborted)setReviewError(reason instanceof Error?reason.message:'Execution cost evidence unavailable.');}).finally(()=>{if(!controller.signal.aborted)setReviewLoading(false);});return()=>controller.abort();},[token,platform,reviewExample]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setResult(null);
  void fetch(`/api/v1/regime?token=${encodeURIComponent(token)}&platform=${encodeURIComponent(platform)}`,{signal:controller.signal,cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'Could not read recorded cost data.');return body as RegimeResult;}).then(body=>{setResult(body);const nvdaFocus=token==='NVDA'&&platform==='ondo'?body.points.findIndex(point=>point.ts.startsWith('2026-09-20T16:45:')):-1;const recovery=body.points.findIndex((point,index)=>point.pct!==null&&point.pct>1&&body.points[index+1]?.pct!==null&&body.points[index+1]!.pct!<=1&&Date.parse(body.points[index+1]!.ts)-Date.parse(point.ts)<=30*60_000);setSelectedIndex(nvdaFocus>=0?nvdaFocus:recovery>=0?recovery:0);}).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:'Recorded data unavailable.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[token,platform]);
 const chosen=result?.points[selectedIndex];
 const spanDays=result?.windowStart&&result.windowEnd?(Date.parse(result.windowEnd)-Date.parse(result.windowStart))/86_400_000:null;
 const sweep=result?.sweepObservations??[];
 const pairs=useMemo(()=>result?.availableTokens??[],[result]);
 const nvdaBeforeIndex=result&&token==='NVDA'&&platform==='ondo'?result.points.findIndex(point=>point.ts.startsWith('2026-09-20T16:45:')):-1;
 const nvdaAfterIndex=result&&token==='NVDA'&&platform==='ondo'?result.points.findIndex(point=>point.ts.startsWith('2026-09-20T17:00:')):-1;
 const nvdaBefore=nvdaBeforeIndex>=0?result?.points[nvdaBeforeIndex]:undefined;
 const nvdaAfter=nvdaAfterIndex>=0?result?.points[nvdaAfterIndex]:undefined;
 const inspectObservation=(index:number)=>{setSelectedIndex(index);const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;evidenceRef.current?.scrollIntoView({behavior:reducedMotion?'auto':'smooth',block:'center'});evidenceRef.current?.focus({preventScroll:true});};
 return <section className="regime-view" aria-label="Recorded execution cost regimes">
  {nvdaBefore?.pct!==null&&nvdaBefore?.pct!==undefined&&nvdaAfter?.pct!==null&&nvdaAfter?.pct!==undefined&&<div className="regime-focus" aria-label="Recorded NVDA cost reversal"><div className="regime-focus-copy"><span className="regime-kicker">20 SEP 2026 · HISTORICAL QUOTES</span><h3>The quoted cost changed in 15 minutes.</h3><p>For a recorded $10,000 NVDA / Ondo buy, the first quote implied paying far above the token reference value. The next was just below it.</p><div className="regime-focus-values"><div><span>16:45 UTC · recorded buy quote</span><strong>{pct(nvdaBefore.pct)}</strong></div><span className="regime-focus-arrow" aria-hidden="true">→</span><div><span>17:00 UTC · recorded buy quote</span><strong>{pct(nvdaAfter.pct)}</strong></div></div><p className="regime-focus-limit">These are historical quotes, not completed trades or current offers. The percentages compare quoted cost with the token reference value (NAV).</p></div><div className="regime-focus-actions"><button type="button" onClick={()=>inspectObservation(nvdaBeforeIndex)}>See first quote</button><button type="button" onClick={()=>inspectObservation(nvdaAfterIndex)}>See next quote</button><a href="#regime-chart">Explore six days ↓</a></div></div>}
  <div className="regime-legend" aria-label="Chart legend"><span><i className="regime-legend-dot"/> At or below the 1% warning line</span><span><i className="regime-legend-dot broken"/> Above the 1% warning line</span><span><i className="regime-legend-band"/> Ondo paused frame</span></div>
  <div className="regime-controls"><label>Choose a stock token<select aria-label="Choose a recorded stock token" value={`${token}|${platform}`} onChange={event=>{const [nextToken,nextPlatform]=event.target.value.split('|');setToken(nextToken!);setPlatform(nextPlatform!);setReviewExample(false);}}>{pairs.length?pairs.map(pair=><option key={`${pair.token}|${pair.platform}`} value={`${pair.token}|${pair.platform}`}>{pair.token} · {pair.platform==='ondo'?'Ondo':'bStock'}</option>):<option value={`${token}|${platform}`}>{token} · {platform}</option>}</select></label><div className="regime-shortcuts" aria-label="Evidence examples">{[['NVDA','ondo'],['AMZN','ondo'],['SPY','ondo'],['TQQQ','bstock']].map(([name,issuer])=><button key={`${name}-${issuer}`} type="button" className={name===token&&issuer===platform?'active':''} onClick={()=>{setToken(name!);setPlatform(issuer!);setReviewExample(false);}}>{name} / {issuer}</button>)}</div></div>

  {loading&&<p className="regime-state" role="status">Reading recorded rows…</p>}{error&&<p className="regime-state error" role="alert">{error}</p>}
  {result&&!loading&&<>
   <div className="regime-metrics"><div><span>Quotes above 1%</span><strong>{result.brokenPercent===null?'No cost data':`${result.brokenPercent.toFixed(1)}%`}</strong><small>{result.brokenCount} of {result.observedCount} recorded $10,000 buy quotes were over 1% above the reference value</small></div><div><span>History shown</span><strong>{spanDays===null?'No series':`${spanDays.toFixed(1)} days`}</strong><small>{result.windowStart&&result.windowEnd?`${utc(result.windowStart)} → ${utc(result.windowEnd)}`:'No time series for this token'}</small></div><div><span>Quote attempts</span><strong>{result.points.length} rows</strong><small>{result.points.length-result.observedCount} quotes without a measured cost; none are treated as zero</small></div></div>
   <div id="regime-chart" tabIndex={-1}><div className="regime-chart-heading"><span className="regime-kicker">SIX DAYS OF RECORDED QUOTES</span><h3>Compare recorded buying costs</h3><p>0% matches the token reference value. Positive values are above it; 1% is the warning line used in this research.</p></div><CostChart result={result} selectedIndex={selectedIndex} onSelect={setSelectedIndex}/></div>
   {result.points.length>0&&<div className="regime-scrubber"><label htmlFor="regime-observation">Inspect any recorded point</label><input id="regime-observation" type="range" min="0" max={Math.max(result.points.length-1,0)} value={Math.min(selectedIndex,result.points.length-1)} onChange={event=>setSelectedIndex(Number(event.target.value))}/><span>{Math.min(selectedIndex+1,result.points.length)} / {result.points.length}</span></div>}
   {chosen&&<article ref={evidenceRef} tabIndex={-1} className="regime-evidence" aria-live="polite"><div><span className="regime-kicker">SELECTED HISTORICAL QUOTE</span><h3>{chosen.pct===null?'No measured cost':pct(chosen.pct)}</h3><p>{utc(chosen.ts)} · {token} / {platform} · $10,000 buy{chosen.route?` · ${chosen.route}`:''}</p><p>{chosen.pct===null?`Quote unavailable${chosen.err!==undefined?` (error ${chosen.err})`:''}. This is not a zero-cost route.`:chosen.pct>1?'More than 1% above the reference value.':'At or below the 1% warning line.'}</p></div><SourceProof source={chosen.source}/></article>}
  <details className="regime-secondary"><summary>Check the latest matching quote <span>Optional, read-only</span></summary>
  <section className="regime-cost-review" aria-label="Execution cost review"><div className="regime-cost-heading"><div><span className="regime-kicker">EXECUTION COST REVIEW</span><h3>Latest recorded matching quote</h3><p>Exact token, issuer, buy side and amount, including newer collector files beyond the chart. A failed latest row means no measured cost.</p></div><div className="regime-cost-choices"><button type="button" className={!reviewExample?'active':''} aria-pressed={!reviewExample} onClick={()=>setReviewExample(false)}>{token} / {platform} · $10,000</button><button type="button" className={reviewExample?'active':''} aria-pressed={reviewExample} onClick={()=>setReviewExample(true)}>AAOIB / bStock · $10 example</button></div></div>{reviewLoading?<p className="regime-state" role="status">Reading cost evidence…</p>:reviewError?<p className="regime-state error" role="alert">{reviewError}</p>:review?<CostReviewEvidence review={review}/>:null}</section>
  </details>
   {result.flips.length>0&&<div className="regime-events"><h3>Crossings of the 1% warning line</h3><p>Transitions between consecutive measured quotes. A gap or failed quote is never filled in.</p><div>{result.flips.slice(0,12).map((flip,index)=><button type="button" key={`${flip.ts}-${index}`} onClick={()=>{const found=result.points.findIndex(point=>point.ts===flip.ts);if(found>=0)setSelectedIndex(found);}}><time dateTime={flip.ts}>{utc(flip.ts)}</time><strong>{flip.from==='broken'?'Above 1%':'At or below 1%'} → {flip.to==='broken'?'Above 1%':'At or below 1%'}</strong></button>)}</div>{result.flips.length>12&&<small>{result.flips.length-12} more crossings remain visible in the chart and observation scrubber.</small>}</div>}
   {sweep.length>0&&<div className="regime-sweep"><h3>One-time scan across all tokens</h3><p>These one-time measurements do not record a buy or sell side or a trade size, so they are not compared with the $10,000 buy history.</p>{sweep.map((point,index)=><article key={`${point.source.file}:${point.source.line}-${index}`}><div><strong>{point.pct===null?'No measured cost':pct(point.pct)}</strong><span>{utc(point.ts)}</span></div><SourceProof source={point.source}/></article>)}</div>}
   {(result.outages.length>0||(result.coverageGaps?.length??0)>0)&&<div className="regime-coverage"><h3>Source coverage and reported pauses</h3><p>Reported pauses and missing source coverage are different states. Neither identifies a root cause by itself.</p><div>{result.outages.slice(0,8).map((frame,index)=><details key={`paused-${index}`}><summary><strong>Ondo reported paused</strong><time dateTime={frame.ts}>{utc(frame.ts)}</time><span>{frame.openCount??0}/{frame.totalCount??0} open</span></summary><SourceProof source={frame.source}/></details>)}{result.coverageGaps?.slice(0,8).map((frame,index)=><details key={`gap-${index}`}><summary><strong>Ondo source missing</strong><time dateTime={frame.ts}>{utc(frame.ts)}</time></summary><SourceProof source={frame.source}/></details>)}</div></div>}
   <p className="regime-limit">The percentage above 1% counts recorded quotes, not continuous market time. Historical quotes cannot price or authorize a trade now.</p>
  </>}
 </section>;
}
