'use client';
import Image from 'next/image';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import Passports from './passports';
import CapitalPanel from './capital';
import ReplayLab from './replay-lab';
import SavedEvidenceLab from './saved-evidence-lab';
import RegimeView,{CostReviewEvidence,type CostReview} from './regime';
import {primaryNavigation,primaryViewFor,viewName,type WorkspaceView} from './view-routes';
import {listInjectedWalletProviders,waitForInjectedWalletProviders,type Eip1193Provider,type WalletProviderChoice} from './wallet-providers';
import type {MandateInput,PlanResult} from '@mandate/domain';
type CatalogItem={id:string;symbol:string;underlying:string;issuer:string;tokenPrice:string|null;ratio:string;reportedStatus:string;reportedOpen:boolean|null;discoveryState:'OBSERVED';identityState:'VERIFIED'|'UNVERIFIED';marketDataState:'OBSERVED'|'UNKNOWN';lastKnownAgeSeconds:number|null;executionState:'UNVERIFIED'};
type Catalogue={mode:string;source:string|null;observedAt:string|null;collectorStaleMs:number|null;stale:boolean;completeIssuers:boolean;issuerStates:{issuer:string;state:'OBSERVED'|'UNKNOWN';lastObservedAt:string|null;lastKnownAgeSeconds:number|null}[];items:CatalogItem[]};
type Capability={checkedAt:string|null;checks:{endpoint:string;platform:string|null;state:string;code:string;executionMode:string|null}[]};
declare global{interface Window{binancew3w?:{ethereum?:Eip1193Provider};ethereum?:Eip1193Provider}}
type WalletSession={address:string;chainId:56;expiresAt:number};
type WalletReadings={blockNumber:string;bnb:string;paymentToken:{name:string;symbol:string;decimals:number;balance:string;contract:string};passport:{symbol:string;matchesCatalogue:boolean;decimals:number;rawSupply:string;adjustedSupply:string;rawBalance:string;adjustedBalance:string;multiplier:string;pendingMultiplier:string|null;pendingEffectiveAt:string|null;codePresent:boolean;contract:string};observedAt:string};
type WalletCheck={state:'OBSERVED';blockNumber:string;observedAt:string;paymentDecimals:number;paymentBalanceAtomic:string;requiredAtomic:string;balanceCoversAmount:boolean|null;allowanceAtomic:string|null;allowanceCoversAmount:boolean|null;bnbBalanceAtomic:string;bnbPresent:boolean;paymentPrecisionMatches:boolean;routerFingerprintMatches:boolean;spenderCandidate:string|null;executionCertified:false;note:string}|{state:'UNKNOWN'|'NOT_CHECKED';reason:string};
type ExecutionReview={state:'BLOCKED';preparationAllowed:false;executable:false;note:string;gates:{id:string;label:string;state:'CHECKED'|'BLOCKED'|'UNKNOWN'|'NOT_RUN';detail:string}[]};
type RouteResearch={instrument:string;state:'UNAVAILABLE'|'SHAPE_CHECKED'|'UNVERIFIED';mode?:string;vendorName?:string|null;toTokenAmount?:string;validUntil?:string;walletCheck?:WalletCheck;executionReview?:ExecutionReview;costEvidence?:CostReview;note:string};
const BSC_DOLLAR_TOKEN='0x55d398326f99059fF775485246999027B3197955';
const AAOI_CONTRACT='0x10343ef7da3301493d7ecb647d68a288c6c1db2f';
const label=(issuer:string)=>issuer==='ondo'?'Ondo':'bStocks';
const money=(atomic:string|undefined)=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(atomic||0)/1e6);
const number=(value:string)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(value));
const age=(seconds:number|null)=>seconds===null?'No prior observation':seconds<60?`${seconds}s old`:seconds<3600?`${Math.floor(seconds/60)}m old`:seconds<86400?`${Math.floor(seconds/3600)}h old`:`${Math.floor(seconds/86400)}d old`;
function formatAtomic(value:string,decimals:number,digits=6){const amount=BigInt(value),unit=10n**BigInt(decimals),whole=amount/unit,fraction=(amount%unit).toString().padStart(decimals,'0').slice(0,digits).replace(/0+$/,'');return whole.toLocaleString('en-US')+(fraction?'.'+fraction:'');}
const hexWord=(n:bigint)=>n.toString(16).padStart(64,'0');
function decodeSymbol(hex:string){if(!/^0x[0-9a-fA-F]+$/.test(hex)||hex.length<66)throw new Error('Token symbol could not be read.');const raw=hex.slice(2);const offset=Number(BigInt('0x'+raw.slice(0,64)))*2;let bytes:string;if(Number.isSafeInteger(offset)&&offset>=64&&offset+64<=raw.length){const length=Number(BigInt('0x'+raw.slice(offset,offset+64)));bytes=raw.slice(offset+64,offset+64+length*2);}else bytes=raw.slice(0,64);const decoded=BufferlessFromHex(bytes).replace(/\0+$/,'');if(!decoded||decoded.length>40)throw new Error('Token symbol response is invalid.');return decoded;}
function BufferlessFromHex(hex:string){let out='';for(let i=0;i+1<hex.length;i+=2)out+=String.fromCharCode(parseInt(hex.slice(i,i+2),16));return out;}
async function readWalletChain(provider:Eip1193Provider,address:string):Promise<WalletReadings>{
 const chain=String(await provider.request({method:'eth_chainId'}));if(Number.parseInt(chain,chain.startsWith('0x')?16:10)!==56)throw new Error('Switch the wallet to BNB Smart Chain to read this account.');
 const block=String(await provider.request({method:'eth_blockNumber'}));if(!/^0x[0-9a-f]+$/i.test(block))throw new Error('The wallet returned an invalid block number.');
 const blockHex=block;
 const code=String(await provider.request({method:'eth_getCode',params:[AAOI_CONTRACT,blockHex]}));
 if(!/^0x[0-9a-f]+$/i.test(code)||code==='0x'||/^0x0+$/i.test(code))throw new Error('The recorded AAOI contract has no code at this block.');
 const call=async(to:string,data:string)=>String(await provider.request({method:'eth_call',params:[{to,data},blockHex]}));
 const balanceOf='0x70a08231'+address.toLowerCase().slice(2).padStart(64,'0');
 const [nativeRaw,paymentRaw,paymentDecimalRaw,paymentNameRaw,paymentSymbolRaw,symbolRaw,decimalsRaw,supplyRaw,holderRaw,multiplierRaw,nextMultiplierRaw,effectiveAtRaw,adjustedSupplyRaw]=await Promise.all([
  provider.request({method:'eth_getBalance',params:[address,blockHex]}),call(BSC_DOLLAR_TOKEN,balanceOf),call(BSC_DOLLAR_TOKEN,'0x313ce567'),call(BSC_DOLLAR_TOKEN,'0x06fdde03'),call(BSC_DOLLAR_TOKEN,'0x95d89b41'),call(AAOI_CONTRACT,'0x95d89b41'),call(AAOI_CONTRACT,'0x313ce567'),call(AAOI_CONTRACT,'0x18160ddd'),call(AAOI_CONTRACT,balanceOf),call(AAOI_CONTRACT,'0xa60bf13d'),call(AAOI_CONTRACT,'0xdc767007'),call(AAOI_CONTRACT,'0x97a4064f'),call(AAOI_CONTRACT,'0x9bea6429')
 ]);
 const quantities=[nativeRaw,paymentRaw,paymentDecimalRaw,decimalsRaw,supplyRaw,holderRaw,multiplierRaw,nextMultiplierRaw,effectiveAtRaw,adjustedSupplyRaw].map(v=>String(v));if(quantities.some(v=>!/^0x[0-9a-f]+$/i.test(v)))throw new Error('The wallet returned malformed token data.');
 const paymentDecimals=Number(BigInt(quantities[2])),decimals=Number(BigInt(quantities[3]));if(paymentDecimals>36||decimals>36)throw new Error('A token reported unsupported decimal precision.');
 const symbol=decodeSymbol(symbolRaw),rawSupply=BigInt(quantities[4]),rawBalance=BigInt(quantities[5]),multiplier=BigInt(quantities[6]),nextMultiplier=BigInt(quantities[7]),effectiveAt=BigInt(quantities[8]),reportedAdjustedSupply=BigInt(quantities[9]);
 if(multiplier<=0n)throw new Error('The AAOIB Display multiplier is invalid.');
 const adjustedSupply=rawSupply*multiplier/10n**18n,adjustedBalance=rawBalance*multiplier/10n**18n;
 if(adjustedSupply!==reportedAdjustedSupply)throw new Error('AAOIB adjusted supply does not match the multiplier calculation.');
 return {blockNumber:(BigInt(block).toString()),bnb:formatAtomic(BigInt(quantities[0]).toString(),18),paymentToken:{name:decodeSymbol(paymentNameRaw),symbol:decodeSymbol(paymentSymbolRaw),decimals:paymentDecimals,balance:formatAtomic(BigInt(quantities[1]).toString(),paymentDecimals),contract:BSC_DOLLAR_TOKEN},passport:{symbol,matchesCatalogue:symbol.toUpperCase()==='AAOIB',decimals,rawSupply:formatAtomic(rawSupply.toString(),decimals,4),adjustedSupply:formatAtomic(adjustedSupply.toString(),decimals,4),rawBalance:formatAtomic(rawBalance.toString(),decimals,6),adjustedBalance:formatAtomic(adjustedBalance.toString(),decimals,6),multiplier:formatAtomic(multiplier.toString(),18,8),pendingMultiplier:effectiveAt>0n?formatAtomic(nextMultiplier.toString(),18,8):null,pendingEffectiveAt:effectiveAt>0n?new Date(Number(effectiveAt)*1000).toISOString():null,codePresent:true,contract:AAOI_CONTRACT},observedAt:new Date().toISOString()};
}
async function json(url:string,body?:unknown){const r=await fetch('/api'+url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const value=await r.json();if(!r.ok)throw new Error(value.issues?.[0]?.message||value.message||value.error||'Request failed');return value;}
function missingProviderMessage(){return 'No EVM wallet provider was found in this tab. Open Mandate in a wallet DApp browser or a desktop browser with an EVM wallet extension, then try again.';}

function WalletPreflight({check}:{check:WalletCheck}){
 if(check.state!=='OBSERVED')return <p className="wallet-error">Wallet check unavailable ({check.reason}). The quote remains read-only.</p>;
 const amount=formatAtomic(check.paymentBalanceAtomic,check.paymentDecimals,4),allowance=check.allowanceAtomic===null?null:formatAtomic(check.allowanceAtomic,check.paymentDecimals,4);
 return <div className="readiness" aria-label="Wallet preflight observations"><div className="readiness-heading"><strong>Wallet readings at block #{check.blockNumber}</strong><span>Read-only snapshot · no trade permission</span></div><div className="readiness-grid"><div><span>USDT balance</span><strong>{amount} USDT</strong><small>{check.balanceCoversAmount===null?'Token precision changed; comparison unavailable':check.balanceCoversAmount?'Covers the 10 USDT research amount':'Below the 10 USDT research amount'}</small></div><div><span>USDT spending limit for unverified address</span><strong>{allowance===null?'Unknown':allowance+' USDT'}</strong><small>{!check.paymentPrecisionMatches?'Token precision changed; comparison unavailable':check.allowanceCoversAmount===null?'No spender was identified':check.allowanceCoversAmount?'Covers the amount; approval history is not assessed':'Below the amount; no approval requested'}</small></div><div><span>BNB balance</span><strong>{formatAtomic(check.bnbBalanceAtomic,18,6)} BNB</strong><small>{check.bnbPresent?'Present; gas sufficiency not assessed':'No BNB in this wallet for network fees'}</small></div><div><span>Router code comparison</span><strong>{check.routerFingerprintMatches?'Same as earlier reading':'Different or unknown'}</strong><small>{check.paymentPrecisionMatches?'USDT token reports 18 decimal places':'USDT precision changed'}</small></div></div><p className="footnote">Read from BNB Smart Chain at one block. These numbers do not confirm that this wallet can trade or what a transaction would do. Trading remains disabled.</p></div>;
}

function ResearchResult({result,decimals}:{result:RouteResearch;decimals:number}){
 const [expired,setExpired]=useState(false);
 useEffect(()=>{
  const deadline=Date.parse(result.validUntil??'');
  const refresh=()=>setExpired(!Number.isFinite(deadline)||Date.now()>=deadline);
  refresh();
  const timer=Number.isFinite(deadline)?window.setTimeout(refresh,Math.max(0,deadline-Date.now())):null;
  document.addEventListener('visibilitychange',refresh);
  return()=>{if(timer!==null)window.clearTimeout(timer);document.removeEventListener('visibilitychange',refresh);};
 },[result.validUntil]);
 const gateNames:Record<string,string>={response:'Requested quote matched',freshness:'Quote still fresh',interface:'What the transaction would do',eligibility:'Can this wallet trade it?',funding:'Enough USDT',spender:'USDT spending approval',gas:'BNB for network fees',simulation:'Transaction test',authorization:'Trade approval'};
 return <div aria-live="polite">
  <p><strong>{result.state==='SHAPE_CHECKED'?'Quote received; trading not verified':result.state==='UNAVAILABLE'?'No route returned for this request':'Quote response needs review'}</strong></p>
  {result.toTokenAmount&&<><p>{expired?'Expired quote estimated':'Estimated output'}: {formatAtomic(result.toTokenAmount,decimals,6)} AAOIB token units before the token's display multiplier. Your wallet may show a different amount.</p>{expired&&<p className="quote-expired" role="status">This research quote expired. Request a new one to see a current estimate.</p>}</>}
  <p className="footnote">This read-only quote does not confirm trading access, transaction contents, network fees, or approval. Quotes expire in about 30 seconds.</p>
  <details><summary>Technical route details</summary><p>{result.mode?`Mode: ${result.mode}. `:''}{result.vendorName?`Source: ${result.vendorName}. `:''}{result.note}</p></details>
  {result.costEvidence&&<div className="route-cost-review"><h3>Historical cost for this exact request</h3><CostReviewEvidence review={result.costEvidence}/></div>}
  {result.executionReview&&<div className="execution-review"><h3>Trading is unavailable</h3><p>This result is for research. Mandate has not verified what the transaction would do or whether this wallet can trade the token.</p><details><summary>See {result.executionReview.gates.length} trade-readiness checks</summary><p>{result.executionReview.note}</p><div className="execution-gates">{result.executionReview.gates.map(gate=>{const stale=gate.id==='freshness'&&expired;const state=stale?'BLOCKED':gate.state;return <div className="execution-gate" key={gate.id}><div><strong>{gateNames[gate.id]??gate.label}</strong><span className={'status '+(state!=='CHECKED'?'attention':'')}>{state==='CHECKED'?'Checked':state==='NOT_RUN'?'Not run':state==='UNKNOWN'?'Unknown':'Blocked'}</span></div><p>{stale?'The research quote expired. Request a fresh quote.':gate.detail}</p></div>;})}</div></details></div>}
 </div>;
}

export default function Home({initialView='Regime'}:{initialView?:WorkspaceView}){
 const [tab,setTab]=useState<WorkspaceView>(initialView),[input,setInput]=useState<MandateInput|null>(null),[plan,setPlan]=useState<PlanResult|null>(null),[catalogue,setCatalogue]=useState<Catalogue|null>(null),[capability,setCapability]=useState<Capability|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[extra,setExtra]=useState('0'),[filter,setFilter]=useState(''),[target,setTarget]=useState('400'),[withdraw,setWithdraw]=useState<{coveredAtomic:string;shortfallAtomic:string;legs:{id:string;netAtomic:string}[];note:string}|null>(null);
 const [dirty,setDirty]=useState(false);
 const [showAllTokens,setShowAllTokens]=useState(false);
 const [wallet,setWallet]=useState<WalletSession|null>(null),[walletBusy,setWalletBusy]=useState(false),[walletError,setWalletError]=useState(''),[walletReads,setWalletReads]=useState<WalletReadings|null>(null),[walletReadError,setWalletReadError]=useState('');
 const [providerChoices,setProviderChoices]=useState<WalletProviderChoice[]>([]);
 const [routeResearch,setRouteResearch]=useState<RouteResearch|null>(null),[routeBusy,setRouteBusy]=useState(false),[routeError,setRouteError]=useState('');
 const providerRef=useRef<Eip1193Provider|null>(null),walletRef=useRef<WalletSession|null>(null);
 useEffect(()=>{walletRef.current=wallet;},[wallet]);
 async function load(){setBusy(true);setError('');try{const [workspace,cat]=await Promise.all([json('/v1/workspace'),json('/v1/instruments')]);setInput(workspace.mandate);setCapability(workspace.capabilities);setCatalogue(cat);setPlan(await json('/v1/plans/preview',workspace.mandate));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 async function clearWalletSession(){try{await fetch('/api/v1/wallet/session',{method:'DELETE',credentials:'same-origin'});}catch{}setWallet(null);walletRef.current=null;providerRef.current=null;setProviderChoices([]);setWalletReads(null);setRouteResearch(null);}
 async function connectWallet(choice?:WalletProviderChoice){
  setWalletBusy(true);setWalletError('');setWalletReadError('');
  try{
   let selected=choice;
   if(!selected){const providers=await waitForInjectedWalletProviders(window);if(!providers.length)throw new Error(missingProviderMessage());if(providers.length>1){setProviderChoices(providers);return;}selected=providers[0];}
   setProviderChoices([]);const provider=selected.provider;providerRef.current=provider;
   const accounts=await provider.request({method:'eth_requestAccounts'});if(!Array.isArray(accounts)||typeof accounts[0]!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(accounts[0]))throw new Error('The wallet did not return an account.');const address=accounts[0];
   let chain=String(await provider.request({method:'eth_chainId'}));let chainNumber=Number.parseInt(chain,chain.startsWith('0x')?16:10);
   if(chainNumber!==56){try{await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x38'}]});chain=String(await provider.request({method:'eth_chainId'}));chainNumber=Number.parseInt(chain,chain.startsWith('0x')?16:10);}catch{throw new Error('Select BNB Smart Chain in your wallet, then connect again.');}}
   if(chainNumber!==56)throw new Error('The wallet is not on BNB Smart Chain.');
   const challengeResponse=await fetch('/api/v1/wallet/challenge',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({address,chainId:56})});const challenge=await challengeResponse.json();if(!challengeResponse.ok)throw new Error(challenge.error||'Could not start wallet sign-in.');
   const messageHex='0x'+Array.from(new TextEncoder().encode(challenge.message),byte=>byte.toString(16).padStart(2,'0')).join('');
   const signature=await provider.request({method:'personal_sign',params:[messageHex,address]});if(typeof signature!=='string')throw new Error('The wallet returned an invalid message signature.');
   const verifyResponse=await fetch('/api/v1/wallet/verify',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({challengeId:challenge.id,signature})});const session=await verifyResponse.json();if(!verifyResponse.ok)throw new Error(session.error||'The server could not verify wallet ownership.');
   const nextWallet=session as WalletSession;walletRef.current=nextWallet;setWallet(nextWallet);try{setWalletReads(await readWalletChain(provider,address));}catch(e){setWalletReadError((e as Error).message);}
  }catch(e){setWalletError((e as Error).message);}finally{setWalletBusy(false);}
 }
 useEffect(()=>{
  let active=true;
  const refresh=async()=>{
   try{const response=await fetch('/api/v1/wallet/session',{credentials:'same-origin',cache:'no-store'});const body=await response.json();if(!active||!body.session)return;const providers=listInjectedWalletProviders(window);for(const choice of providers){const provider=choice.provider;let accounts:unknown,chain:string;try{accounts=await provider.request({method:'eth_accounts'});chain=String(await provider.request({method:'eth_chainId'}));}catch{continue;}if(!Array.isArray(accounts)||String(accounts[0]||'').toLowerCase()!==String(body.session.address).toLowerCase()||Number.parseInt(chain,chain.startsWith('0x')?16:10)!==56)continue;if(!active)return;providerRef.current=provider;const session=body.session as WalletSession;walletRef.current=session;setWallet(session);setWalletReads(await readWalletChain(provider,session.address));return;}if(providers.length)await clearWalletSession();
   }catch(e){if(active)setWalletReadError((e as Error).message);}
  };
  void refresh();
  return()=>{active=false;};
 },[]);
 useEffect(()=>{
  const provider=providerRef.current;if(!wallet||!provider)return;
  const onAccounts=(value:unknown)=>{const accounts=value as string[];if(!Array.isArray(accounts)||!accounts.length||accounts[0]?.toLowerCase()!==wallet.address.toLowerCase())void clearWalletSession();else void refreshWallet();};
  const onChain=(value:unknown)=>{const chain=String(value);if(Number.parseInt(chain,chain.startsWith('0x')?16:10)!==56){void clearWalletSession();setWalletError('Wallet network changed. Reconnect on BNB Smart Chain.');}else void refreshWallet();};
  provider.on?.('accountsChanged',onAccounts);provider.on?.('chainChanged',onChain);
  return()=>{provider.removeListener?.('accountsChanged',onAccounts);provider.removeListener?.('chainChanged',onChain);};
 },[wallet?.address]);
 async function refreshWallet(){const provider=providerRef.current;if(!provider||!wallet)return;setWalletReadError('');try{const sessionResponse=await fetch('/api/v1/wallet/session',{credentials:'same-origin',cache:'no-store'}),session=await sessionResponse.json();if(!sessionResponse.ok||session.session?.address?.toLowerCase()!==wallet.address.toLowerCase())throw new Error('Wallet session expired. Reconnect to refresh.');const accounts=await provider.request({method:'eth_accounts'});if(!Array.isArray(accounts)||accounts[0]?.toLowerCase()!==wallet.address.toLowerCase())throw new Error('The connected wallet account changed. Reconnect to continue.');setWalletReads(await readWalletChain(provider,wallet.address));}catch(e){setWalletReadError((e as Error).message);}}
 async function researchRoute(){if(!wallet)return;setRouteBusy(true);setRouteError('');setRouteResearch(null);try{const provider=providerRef.current;if(!provider)throw new Error('Connected wallet is unavailable. Reconnect first.');const matches=async()=>{const accounts=await provider.request({method:'eth_accounts'}),chain=String(await provider.request({method:'eth_chainId'}));return Array.isArray(accounts)&&String(accounts[0]||'').toLowerCase()===wallet.address.toLowerCase()&&Number.parseInt(chain,chain.startsWith('0x')?16:10)===56;};if(!await matches())throw new Error('Wallet account or network changed. Reconnect first.');const result=await json('/v1/routes/AAOIB/research',{amount:'10'}) as RouteResearch;if(!await matches())throw new Error('Wallet changed while checking the route. Reconnect first.');setRouteResearch(result);}catch(e){setRouteError((e as Error).message);}finally{setRouteBusy(false);}}
 function update(patch:Partial<MandateInput>){setInput(prev=>prev?{...prev,...patch}:prev);setDirty(true);}
 async function preview(event?:FormEvent){event?.preventDefault();if(!input)return;setBusy(true);setError('');try{const obligations=[{id:'monthly',label:'Monthly commitments',amount:input.reserveFloor},...(extra&&extra!=='0'?[{id:'additional',label:'Additional expense',amount:extra}]:[])];const revised={...input,obligations};setPlan(await json('/v1/plans/preview',revised));setInput(revised);setDirty(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const filtered=catalogue?.items.filter(i=>(i.symbol+' '+i.underlying+' '+i.issuer).toLowerCase().includes(filter.toLowerCase()))||[];
 const state=dirty?'Changes not previewed':plan?.status==='feasible'?'Fits your rules':'Review the rules';
 const primary=primaryViewFor(tab);
 const portfolioView=primary==='Portfolio/exit';
 const catalogueView=tab==='Execution review'||tab==='Instruments';
 const walletResearchView=tab==='Execution review'||tab==='Instruments'||tab==='Passports'||tab==='Lab';
 const capitalView=portfolioView||tab==='Lab'||tab==='Instruments'||tab==='Passports';
 const planView=portfolioView;
 const withdrawView=tab==='Portfolio/exit'||tab==='Withdraw'||tab==='Cash raising';
 const pageTitle:Record<WorkspaceView,string>={Regime:'See when buying got expensive.','Execution review':'Research a token before deciding.','Portfolio/exit':'Plan around your cash needs.',Overview:'Make every allocation intentional.',Portfolio:'Build around your priorities.',Plans:'Understand every decision.',Instruments:'Know what sits behind a ticker.',Withdraw:'Plan the way back to cash.',Lab:'Put your rules to the test.','Cash raising':'Plan how to raise cash.',Inflows:'Review incoming funds.',Recurring:'Schedule regular checks.',Passports:'Compare token facts and risks.'};
 return <div className="shell">
   <aside className="sidebar"><a className="brand" href="/" aria-label="Mandate home"><Image className="mark" src="/mandate-mark-mint.svg" alt="" width={32} height={32}/>Mandate</a><div className="workspace-label">YOUR WORKSPACE</div><nav aria-label="Workspace navigation">{primaryNavigation.map((item,i)=><a key={item.href} href={item.href} aria-current={primary===item.label?'page':undefined} className={primary===item.label?'nav-item active':'nav-item'}><span className="nav-index">{String(i+1).padStart(2,'0')}</span>{item.text}</a>)}</nav><div className="sidebar-note"><div className="mode-label">Planning workspace</div><p>Explore the decisions.<br/>Understand the trade-offs.</p><span>Live execution is disabled</span></div></aside>
  <div className="main"><header className="topbar"><span>Workspace <span className="breadcrumb">/</span> <strong>{viewName(tab)}</strong></span><div className="topbar-right"><span className="scenario-pill">{tab==='Regime'?'Historical quotes':primary==='Execution review'?'Read-only research':'Illustrative plan'}</span>{wallet?<span className="wallet-state">{wallet.address.slice(0,6)}…{wallet.address.slice(-4)} · BSC</span>:<span className="wallet-state">Wallet not connected</span>}<button className="wallet-connect" disabled={walletBusy} onClick={()=>wallet?void clearWalletSession():void connectWallet()}>{walletBusy?'Connecting…':wallet?'Disconnect':'Connect wallet'}</button></div></header>
  <main id="main-content">{providerChoices.length>0&&<section className="wallet-picker" aria-label="Choose a wallet"><strong>Choose a wallet for a read-only account check</strong><p>This optional sign-in lets Mandate read your BNB Smart Chain account. It cannot move funds.</p><div>{providerChoices.map(choice=><button key={choice.id} disabled={walletBusy} onClick={()=>void connectWallet(choice)}>{choice.name}</button>)}</div></section>}<div className="page-heading"><div><p className="eyebrow">{tab==='Regime'?'HISTORICAL BUY QUOTES':primary==='Execution review'?'TOKEN FACTS AND OPTIONAL WALLET QUOTE':'ILLUSTRATIVE CASH PLAN'}</p><h1>{pageTitle[tab]}</h1>{tab!=='Regime'&&<p className="intro">{primary==='Execution review'?'Browse recorded token information. Connect a wallet only if you want a fresh, read-only quote for your wallet. A quote does not approve a trade.':withdrawView?'Set money aside for commitments, then explore a hypothetical allocation or cash need. No trade is placed.':'Set money aside before exploring a hypothetical allocation.'}</p>}</div><span className="network-label">BNB Smart Chain</span></div>
  {tab==='Regime'&&<RegimeView/>}
  {tab!=='Regime'&&<>
  {walletResearchView&&wallet&&<section className="wallet-panel" aria-label="Read-only wallet and instrument proof"><div className="wallet-panel-heading"><div><span className="eyebrow">CONNECTED WALLET · READ ONLY</span><h2>Wallet balance snapshot</h2><p>A one-time signature verified this wallet address for read-only access. It did not approve a transaction.</p></div><button className="text-button" onClick={()=>void refreshWallet()}>Refresh</button></div>{walletReadError&&<p className="wallet-error" role="alert">{walletReadError}</p>}{walletReads?<><div className="wallet-metrics"><div><span>BNB balance</span><strong>{walletReads.bnb} BNB</strong></div><div><span>{walletReads.paymentToken.name} balance</span><strong>{walletReads.paymentToken.balance} {walletReads.paymentToken.symbol}</strong><small>{walletReads.paymentToken.decimals} decimals · {walletReads.paymentToken.contract.slice(0,8)}…</small></div><div><span>Read at block</span><strong>#{walletReads.blockNumber}</strong></div></div><div className="passport-proof"><div><span className="proof-kicker">RECORDED CANDIDATE · AAOI / AAOIB · BSC STOCK SNAPSHOT</span><strong>{walletReads.passport.symbol} · {walletReads.passport.decimals} decimals</strong><small>{walletReads.passport.contract}</small><p>Your displayed balance is {walletReads.passport.adjustedBalance} AAOIB (raw: {walletReads.passport.rawBalance}). Displayed supply is {walletReads.passport.adjustedSupply} (raw: {walletReads.passport.rawSupply}); Display multiplier {walletReads.passport.multiplier}× at block #{walletReads.blockNumber}.{walletReads.passport.pendingEffectiveAt?` A change to ${walletReads.passport.pendingMultiplier}× is scheduled for ${walletReads.passport.pendingEffectiveAt}.`:''} Symbol {walletReads.passport.matchesCatalogue?'matches':'does not match'} the catalogue candidate.</p><span className="proof-limit">BTech-issued certificate linked to AAOI; it is not a direct share. Wallet eligibility, collateral, market depth and execution remain unverified.</span></div><a href={'https://bscscan.com/token/'+walletReads.passport.contract} target="_blank" rel="noreferrer">View on BscScan ↗</a></div><p className="wallet-footnote">Snapshot at {new Date(walletReads.observedAt).toLocaleTimeString()} from your wallet's BSC RPC. These readings do not change the scenario planner's illustrative balance.</p></>:!walletReadError&&<p className="wallet-footnote">Reading balances and the recorded AAOI contract from BNB Smart Chain…</p>}</section>}
   {capitalView&&wallet&&input&&<CapitalPanel key={wallet.address.toLowerCase()} mandate={input}/>}
  {walletResearchView&&wallet&&walletReads&&<section className="panel" aria-label="Connected-wallet route research"><div className="panel-title"><div><h2>Request a read-only 10 USDT → AAOIB quote</h2><p>AAOIB is a certificate linked to AAOI, not a share. This check requests a quote and unsigned transaction data; it does not place a trade.</p></div><button className="text-button" disabled={routeBusy} onClick={()=>void researchRoute()}>{routeBusy?'Requesting quote…':'Get read-only quote'}</button></div>{routeError&&<p className="wallet-error" role="alert">{routeError}</p>}{routeResearch&&<ResearchResult result={routeResearch} decimals={walletReads.passport.decimals}/>}</section>}
  {walletResearchView&&wallet&&routeResearch?.walletCheck&&<section className="panel wallet-readiness-panel" aria-label="Connected-wallet preflight"><WalletPreflight check={routeResearch.walletCheck}/></section>}
  </>}
  {walletError&&<div role="alert" className="error-box">{walletError}<button className="text-button" onClick={()=>setWalletError('')}>Dismiss</button></div>}
  {error&&<div role="alert" className="error-box">{error}<button className="text-button" onClick={()=>void load()}>Reload workspace</button></div>}
  {tab!=='Regime'&&!input&&!error&&<div className="empty">Loading your workspace…</div>}
  {input&&plan&&<>
   {planView&&<>
    <section className="balance-strip" aria-label="Illustrative scenario cash allocation"><p className="balance-caption">ILLUSTRATIVE EXAMPLE · COMMITMENTS COME FIRST</p><div><span>Example balance</span><strong>{money(plan.balanceAtomic)}<small>USDT</small></strong></div><div><span>Protected commitments</span><strong>{money(plan.reserveAtomic)}<small>USDT</small></strong></div><div><span>Operating budget</span><strong>{money(plan.operatingAtomic)}<small>USDT</small></strong></div><div className="balance-emphasis"><span>Available in this example</span><strong>{money(plan.investableAtomic)}<small>USDT</small></strong></div></section>
    <div className="planning-grid"><section className="panel allocation-panel"><div className="panel-title"><div><h2>Illustrative allocation</h2><p>Example amounts after protected cash; modeled costs are included.</p></div><span className={'status '+(dirty||plan.status!=='feasible'?'attention':'')}>{state}</span></div>
    {plan.legs.length>0?<><div className="allocation-bar" aria-label="Allocation weights">{plan.legs.map((leg,n)=><div key={leg.instrumentId} style={{width:leg.weightBps/100+'%'}} className={'segment segment-'+n}><span>{leg.weightBps/100}%</span></div>)}</div><div className="table-wrap"><table><thead><tr><th>Underlying</th><th>Token issuer</th><th>Budget</th><th>Scenario cost</th></tr></thead><tbody>{plan.legs.map((leg,n)=><tr key={leg.instrumentId}><td><span className={'asset-mark asset-'+n}>{leg.underlying.slice(0,2)}</span><strong>{leg.underlying}</strong></td><td>{label(leg.issuer)}</td><td>{money(leg.grossAtomic)}<small> USDT</small></td><td>{leg.costBps} bps</td></tr>)}</tbody></table></div><div className="cost-line"><span>Total scenario cost</span><strong>{money(plan.modeledCostAtomic)} USDT</strong></div></>:<div className="empty"><strong>This example needs a change.</strong><p>{plan.reasons[0]}</p></div>}
    <div className="issuer-block"><div><h3>Share by token issuer</h3><p>How much of the example investment uses each token issuer. Protected cash is separate.</p></div><div className="issuer-values">{plan.issuerExposure.length?plan.issuerExposure.map(i=><div key={i.issuer}><span>{label(i.issuer)}</span><strong>{(i.shareBps/100).toFixed(2)}%</strong></div>):<span>No feasible mix</span>}</div></div></section>
    <section className="panel rules-panel"><div className="panel-title"><div><h2>Your rules</h2><p>Change an assumption to see how the example changes.</p></div></div><form onSubmit={preview}>
    <div className="field-pair"><label>Example balance · USDT<input inputMode="decimal" value={input.balance} onChange={e=>update({balance:e.target.value})}/></label><label>Cash to set aside · USDT<input inputMode="decimal" value={input.reserveFloor} onChange={e=>update({reserveFloor:e.target.value})}/></label></div>
    <label>Additional commitment · USDT<input aria-label="Additional commitment in USDT" inputMode="decimal" value={extra} onChange={e=>{setExtra(e.target.value);setDirty(true);}}/></label>
    <div className="field-pair"><label>Maximum with one issuer · %<input type="number" min="1" max="100" value={input.maxIssuerBps/100} onChange={e=>update({maxIssuerBps:Math.round(Number(e.target.value)*100)})}/></label><label>Maximum scenario cost · bps<input type="number" min="0" max="1000" value={input.maxCostBps} onChange={e=>update({maxCostBps:Number(e.target.value)})}/><small className="field-help">100 bps = 1%. This is a scenario limit, not a live quote.</small></label></div>
    {(tab==='Portfolio'||tab==='Portfolio/exit')&&<fieldset><legend>Target weights · %</legend>{input.allocations.map((a,n)=><label key={a.underlying}>{a.underlying}<input type="number" min="1" max="100" value={a.weightBps/100} onChange={e=>update({allocations:input.allocations.map((v,i)=>i===n?{...v,weightBps:Number(e.target.value)*100}:v)})}/></label>)}</fieldset>}
    <label>Illustrative cost condition<select value={input.scenario} onChange={e=>update({scenario:e.target.value as MandateInput['scenario']})}><option value="normal">Typical costs (illustrative)</option><option value="expensive">Higher NVIDIA cost (illustrative)</option><option value="missing">No Treasury quote (illustrative)</option></select></label>
    <label className="checkbox"><input type="checkbox" checked={!input.allowLeveraged} onChange={e=>update({allowLeveraged:!e.target.checked})}/>Exclude leveraged products</label><button className="primary" disabled={busy} type="submit">{busy?'Checking your rules…':'Preview allocation'}<span aria-hidden="true">↗</span></button><p className="form-note">A preview changes no balances and requires no wallet signature.</p></form></section></div>
    <section className="decision-section"><div className="section-label"><h2>Why this plan</h2><span>Decision {plan.decisionId.slice(0,8)}</span></div><div className="decision-grid">{plan.reasons.map((r,n)=><div key={r}><span className="reason-number">{n+1}</span><p>{r}</p></div>)}</div>{plan.excluded.length>0&&<details open={tab==='Plans'}><summary>{plan.excluded.length} excluded candidate{plan.excluded.length!==1?'s':''}</summary>{plan.excluded.map(e=><p key={e.instrumentId}><strong>{e.instrumentId.replaceAll('scenario:','').replaceAll(':',' / ')}</strong> · {e.reason}</p>)}</details>}</section>
   </>}
   {(tab==='Instruments'||tab==='Passports')&&<Passports/>}
   {catalogueView&&catalogue?.stale&&catalogue.observedAt&&<p className="catalogue-stale" role="status"><strong>Collector data is stale.</strong> Last recorded frame {age(Math.floor((catalogue.collectorStaleMs??0)/1000))} ago. Historical identities remain visible; current prices and market status are unavailable.</p>}
   {catalogueView&&<section className="panel"><div className="panel-title"><div><h2>Recorded token list <span className="count">{catalogue?.items.length||0}</span></h2><p>{catalogue?.observedAt?'Token data recorded '+new Date(catalogue.observedAt).toLocaleString():'No recorded token data available'} · {catalogue?.completeIssuers?'Data from both issuers available':'Data from one or more issuers missing'}</p></div><label className="search-label">Search<input aria-label="Search instruments" placeholder="Ticker or issuer" value={filter} onChange={e=>setFilter(e.target.value)}/></label></div><div className="catalogue-issuers" aria-label="Issuer source state">{catalogue?.issuerStates.map(s=><div key={s.issuer}><strong>{label(s.issuer)}</strong><span className={'status '+(s.state==='UNKNOWN'?'attention':'')}>{s.state==='OBSERVED'?'Observed':'Unknown'}</span><small>Last known {age(s.lastKnownAgeSeconds)}</small></div>)}</div><p className="catalogue-scroll-hint">Swipe sideways to inspect token identity, recorded data and trade-access status.</p><div className="table-wrap" role="region" aria-label="Instrument evidence table" tabIndex={0}><table><thead><tr><th>Token</th><th>Underlying</th><th>Issuer</th><th>Recorded token price</th><th>Listed</th><th>Token identity</th><th>Data age</th><th>Trade access</th></tr></thead><tbody>{filtered.slice(0,filter.trim()||showAllTokens?40:8).map(i=><tr key={i.id}><td><strong>{i.symbol}</strong></td><td>{i.underlying}</td><td>{label(i.issuer)}</td><td>{i.tokenPrice===null?'Unknown':number(i.tokenPrice)}</td><td>Observed</td><td>{i.identityState==='VERIFIED'?'Verified':'Unverified'}</td><td>{i.marketDataState==='UNKNOWN'?`Unknown · last known ${age(i.lastKnownAgeSeconds)}`:`Recorded · ${age(i.lastKnownAgeSeconds)}`}</td><td><span className="muted">Unverified</span></td></tr>)}</tbody></table></div><p className="footnote">Showing {Math.min(filter.trim()||showAllTokens?40:8,filtered.length)} of {filtered.length} matches. AAOIB's contract identity check does not confirm that it can be traded. Recorded token prices are not buy quotes. A listed token may be unavailable to your wallet.</p>{!filter.trim()&&!showAllTokens&&filtered.length>8&&<button type="button" className="text-button" onClick={()=>setShowAllTokens(true)}>Show first 40 tokens</button>}</section>}
   {withdrawView&&<div className="planning-grid"><section className="panel"><h2>Explore a new cash need</h2><p className="intro">This hypothetical exit keeps 1,200 USDT for existing commitments and 20 USDT for operations before estimating cash available for a new need.</p><form className="withdraw-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{setWithdraw(await json('/v1/withdrawals/preview',{target,scenario:input.scenario}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Additional net amount · USDT<input inputMode="decimal" value={target} onChange={e=>setTarget(e.target.value)}/></label><button className="primary" disabled={busy}>Estimate cash available <span>↗</span></button></form>{withdraw&&<div aria-live="polite"><div className="withdraw-result"><div><span>Modeled coverage</span><strong>{money(withdraw.coveredAtomic)} USDT</strong></div><div><span>Uncovered amount</span><strong>{money(withdraw.shortfallAtomic)} USDT</strong></div></div>{withdraw.legs.map(l=><div className="quote-row" key={l.id}><span>{l.id.replace('scenario:','').replace(':',' / ')}</span><strong>{money(l.netAtomic)} USDT net</strong></div>)}<p className="footnote">{withdraw.note}</p></div>}</section><section className="panel quiet-panel"><h2>Three different numbers</h2><h3>Already available</h3><p>Uncommitted stablecoins after reserves and pending commitments.</p><h3>Currently quoted</h3><p>Estimated net proceeds for a specific quantity and quote window.</p><h3>Actually raised</h3><p>Confirmed proceeds after settlement and reconciliation. This scenario has no settled proceeds.</p></section></div>}
   {tab==='Lab'&&<><ReplayLab/><SavedEvidenceLab key={wallet?.address.toLowerCase()??'disconnected'} wallet={wallet?.address??null}/><div className="planning-grid"><section className="panel"><h2>Scenario workbench</h2><p className="intro">Run the same deterministic policy under a different condition. Cases below are synthetic, not historical fills.</p>{(['normal','expensive','missing'] as const).map((s,n)=><button className="scenario-row" key={s} onClick={async()=>{setBusy(true);try{const next={...input,scenario:s};setInput(next);setPlan(await json('/v1/plans/preview',next));setDirty(false);setTab('Plans');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><span className="reason-number">0{n+1}</span><div><strong>{s==='normal'?'Respect the issuer limit':s==='expensive'?'Reject a costly route':'Handle a missing source'}</strong><small>{s==='normal'?'Find a permitted representation mix':s==='expensive'?'Compare against the approved cost limit':'Keep unknown data distinct from closure'}</small></div><span>↗</span></button>)}</section><section className="panel"><h2>Integration evidence</h2><p className="intro">{capability?.checkedAt?'Read-only probe: '+new Date(capability.checkedAt).toLocaleString():'The capability probe has not run yet.'}</p>{capability?.checks.map((c,n)=><div className="capability-row" key={n}><div><strong>{c.endpoint.split('/').at(-1)}{c.platform?' / '+c.platform:''}</strong><small>{c.executionMode?'Execution mode: '+c.executionMode:'Response code: '+c.code}</small></div><span className={'status '+(c.state!=='AVAILABLE'?'attention':'')}>{c.state==='AVAILABLE'?'Responded':'Unverified'}</span></div>)}<p className="footnote">Signing, transaction building and mainnet reconciliation are not verified by a quote response. Execution remains disabled.</p></section></div></>}
  </>}
  <footer><span>Mandate</span><p>Make a plan. Understand the evidence.</p><span>Local development</span></footer>
  </main></div>
 </div>;
 }
