import {afterEach,describe,expect,it} from 'vitest';
import {Ledger,embeddedDatabase} from '@mandate/store';
import {capitalProtection,previewInvestment,defaultMandate,instruments,quotesFor} from '@mandate/core';
import type {CapitalCheckpoint,CapitalFunding,PlanRevisionRecord} from '@mandate/domain';
import {capitalAccountId,capitalView} from '../apps/api/src/capital.ts';
import {createApp} from '../apps/api/src/app.ts';
import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
const wallet='0x'+'2'.repeat(40),asset={chainId:56,contract:'0x55d398326f99059ff775485246999027b3197955',decimals:18};
const unit=10n**18n;const atomic=(n:number)=>(BigInt(n)*unit).toString();
function checkpoint(block=100,balance=4000,multiplier=unit):CapitalCheckpoint{return {accountId:capitalAccountId(wallet),wallet,asset,balanceAtomic:atomic(balance),blockNumber:String(block),blockHash:'0x'+block.toString(16).padStart(64,'0'),observedAt:new Date().toISOString(),positions:[{contract:'0x10343ef7da3301493d7ecb647d68a288c6c1db2f',symbol:'AAOIB',decimals:18,rawAtomic:'3',multiplierAtomic:multiplier.toString(),adjustedAtomic:(3n*multiplier/unit).toString(),accountingVersion:'bep677-floor-v1'}],evidenceMode:'observed'};}
const policy={reserveFloor:'1200',operatingBudget:'20',obligations:[{id:'rent',label:'Rent',amount:'900',coverage:'reserve' as const},{id:'tax',label:'Extra tax',amount:'400',coverage:'additional' as const}]};
let ledgers:Ledger[]=[];const directories:string[]=[];afterEach(async()=>{for(const ledger of ledgers)await ledger.close();ledgers=[];for(const directory of directories.splice(0))await fs.rm(directory,{recursive:true,force:true});});
async function setup(){const ledger=new Ledger(embeddedDatabase());ledgers.push(ledger);await ledger.migrate();await ledger.applyCapitalCheckpoint(checkpoint());return ledger;}
async function plan(ledger:Ledger,id:string):Promise<PlanRevisionRecord>{const state=(await ledger.capitalState(capitalAccountId(wallet)))!;const value:PlanRevisionRecord={schemaVersion:'1.0.0',id,createdAt:new Date().toISOString(),accountId:state.accountId,revision:1,accountRevision:state.revision,decisionId:'decision',inputHash:'a'.repeat(64),maximumDebit:{asset,atomic:atomic(2380)},evidenceMode:'live',expiresAt:new Date(Date.now()+60000).toISOString()};await ledger.savePlan(value);return value;}
describe('capital checkpoints and planning',{timeout:60000},()=>{
 it('protects reserve-linked obligations once, additional obligations separately and exact dust',()=>{expect(capitalProtection(policy,18).protectedAtomic).toBe(atomic(1620));expect(capitalProtection({...policy,obligations:[{...policy.obligations[0],amount:'1400'},policy.obligations[1]]},18).protectedAtomic).toBe(atomic(1820));expect(capitalProtection({reserveFloor:'0.000000000000000001',operatingBudget:'0',obligations:[]},18).protectedAtomic).toBe('1');});
 it('checkpoints idempotently, keeps accounting history and rejects conflicts or backward blocks',async()=>{const ledger=await setup(),before=await ledger.snapshot(capitalAccountId(wallet));await ledger.applyCapitalCheckpoint(checkpoint());expect((await ledger.snapshot(before.id)).revision).toBe(before.revision);await expect(ledger.applyCapitalCheckpoint({...checkpoint(),balanceAtomic:'1'})).rejects.toThrow('CHECKPOINT_CONFLICT');await expect(ledger.applyCapitalCheckpoint(checkpoint(99))).rejects.toThrow('CHECKPOINT_NON_FORWARD');await ledger.applyCapitalCheckpoint(checkpoint(101,4000,2n*unit));const history=await ledger.capitalHistory(before.id);expect(history).toHaveLength(2);expect(history[0].record.positions[0].adjustedAtomic).toBe('6');expect(history[1].record.positions[0].adjustedAtomic).toBe('3');});
 it('subtracts pending holds from the planner and includes revisions in decision identity',async()=>{const ledger=await setup(),id=capitalAccountId(wallet);await ledger.saveCapitalPolicy(id,policy,1);await plan(ledger,'p');await ledger.reserve({accountId:id,planRevisionId:'p',idempotencyKey:'p',amountAtomic:atomic(500)});const s=(await ledger.capitalState(id))!;const funding:CapitalFunding={accountId:id,accountRevision:s.revision,checkpointId:s.checkpointId,blockNumber:s.checkpoint.blockNumber,observedAt:s.checkpoint.observedAt,balanceAtomic:s.balanceAtomic,protectedAtomic:s.protectedAtomic,heldAtomic:s.heldAtomic,decimals:18};const result=previewInvestment(defaultMandate,instruments,quotesFor('normal'),new Date(),funding);expect(result.investableAtomic).toBe(atomic(1880));expect(result.decimals).toBe(18);expect(result.legs.reduce((total,leg)=>total+BigInt(leg.grossAtomic),0n)).toBe(BigInt(atomic(1880)));expect(result.executable).toBe(false);expect(previewInvestment(defaultMandate,instruments,quotesFor('normal'),new Date(),{...funding,accountRevision:s.revision+1}).decisionId).not.toBe(result.decisionId);});
 it('keeps holds when an external balance drop causes a deficit and invalidates old plans',async()=>{const ledger=await setup(),id=capitalAccountId(wallet);await ledger.saveCapitalPolicy(id,policy,1);await plan(ledger,'first');await plan(ledger,'old');await ledger.reserve({accountId:id,planRevisionId:'first',idempotencyKey:'first',amountAtomic:atomic(500)});await ledger.applyCapitalCheckpoint(checkpoint(101,1000));const s=(await ledger.capitalState(id))!;expect(s.heldAtomic).toBe(atomic(500));expect(s.protectedAtomic).toBe(atomic(1620));expect(s.availableAtomic).toBe('0');expect(s.shortfallAtomic).toBe(atomic(1120));await expect(ledger.reserve({accountId:id,planRevisionId:'old',idempotencyKey:'old',amountAtomic:'1'})).rejects.toThrow('STALE_PLAN');});
 it('rejects competing reservations and stale policy writes on an observed account',async()=>{const ledger=await setup(),id=capitalAccountId(wallet);await ledger.saveCapitalPolicy(id,policy,1);await plan(ledger,'a');await plan(ledger,'b');const results=await Promise.allSettled(['a','b'].map(p=>ledger.reserve({accountId:id,planRevisionId:p,idempotencyKey:p,amountAtomic:atomic(2000)})));expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);await expect(ledger.saveCapitalPolicy(id,{...policy,reserveFloor:'100'},2)).rejects.toThrow('STALE_ACCOUNT');expect((await ledger.capitalState(id))?.protectedAtomic).toBe(atomic(1620));});
 it('retains unknown state after failed reads and rejects expired/unknown capacity for new reservations',async()=>{const ledger=await setup(),id=capitalAccountId(wallet);await plan(ledger,'known');await ledger.invalidateCapital(id);expect((await capitalView(ledger,wallet)).state).toBe('UNKNOWN');await expect(ledger.reserve({accountId:id,planRevisionId:'known',idempotencyKey:'known',amountAtomic:'1'})).rejects.toThrow('CAPITAL_UNKNOWN');await ledger.applyCapitalCheckpoint(checkpoint());expect((await capitalView(ledger,wallet,Date.now()+61000)).state).toBe('STALE');});
 it('rejects a same-height changed hash and invalid multiplier accounting',async()=>{const ledger=await setup();await expect(ledger.applyCapitalCheckpoint({...checkpoint(),blockHash:'0x'+'f'.repeat(64)})).rejects.toThrow('CHECKPOINT_NON_FORWARD');await expect(ledger.applyCapitalCheckpoint({...checkpoint(101),positions:[{...checkpoint().positions[0],adjustedAtomic:'4'}]})).rejects.toThrow('INVALID_POSITION_ACCOUNTING');});
 it('preserves checkpoints, policy versions and reservations across restart',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'mandate-capital-'));directories.push(directory);let ledger=new Ledger(embeddedDatabase(directory));await ledger.migrate();await ledger.applyCapitalCheckpoint(checkpoint());const id=capitalAccountId(wallet);await ledger.saveCapitalPolicy(id,policy,1);await plan(ledger,'restart');await ledger.reserve({accountId:id,planRevisionId:'restart',idempotencyKey:'restart',amountAtomic:atomic(500)});await ledger.saveCapitalPolicy(id,{...policy,operatingBudget:'30'},3);await ledger.close();ledger=new Ledger(embeddedDatabase(directory));ledgers.push(ledger);await ledger.migrate();const state=(await ledger.capitalState(id))!;expect(state.heldAtomic).toBe(atomic(500));expect(state.protectedAtomic).toBe(atomic(1630));expect(state.policyRevision).toBe(2);expect(await ledger.capitalPolicyHistory(id)).toHaveLength(2);expect(await ledger.capitalHistory(id)).toHaveLength(1);});
 it('closes stale funding previews and never rounds fractional atomic units up',()=>{const funding:CapitalFunding={accountId:'a',accountRevision:1,checkpointId:'c',blockNumber:'1',observedAt:'2026-09-27T00:00:00Z',balanceAtomic:'1000000000000000001',protectedAtomic:'1',heldAtomic:'2',decimals:18};const old=previewInvestment(defaultMandate,instruments,quotesFor('normal'),new Date('2026-09-27T00:01:01Z'),funding);expect(old.status).toBe('infeasible');expect(old.investableAtomic).toBe('0');const fresh=previewInvestment(defaultMandate,instruments,quotesFor('normal'),new Date('2026-09-27T00:00:30Z'),funding);expect(fresh.investableAtomic).toBe('999999999999999998');expect(fresh.legs.reduce((n,leg)=>n+BigInt(leg.grossAtomic),0n)).toBe(999999999999999998n);});
 it('binds capital reads to signed sessions, rejects supplied wallets and fails closed on read failure',async()=>{const ledger=new Ledger(embeddedDatabase());ledgers.push(ledger);await ledger.migrate();let fail=false;const signer=privateKeyToAccount(generatePrivateKey());const app=createApp('unused',{ledger,capitalReader:async address=>{if(fail)throw new Error('RPC unavailable');return {...checkpoint(),accountId:capitalAccountId(address),wallet:address.toLowerCase()};}});const origin='http://127.0.0.1:3110';try{expect((await app.inject({url:'/v1/capital'})).statusCode).toBe(401);const c=(await app.inject({method:'POST',url:'/v1/wallet/challenge',headers:{origin},payload:{address:signer.address,chainId:56}})).json();const signature=await signer.signMessage({message:c.message});const v=await app.inject({method:'POST',url:'/v1/wallet/verify',headers:{origin},payload:{challengeId:c.id,signature}});const cookie=String(v.headers['set-cookie']).split(';')[0],headers={cookie,origin};expect((await app.inject({method:'POST',url:'/v1/capital/refresh',headers,payload:{wallet}})).statusCode).toBe(400);const refresh=await app.inject({method:'POST',url:'/v1/capital/refresh',headers,payload:{}});expect(refresh.json()).toMatchObject({state:'OBSERVED',executionAllowed:false});expect((await app.inject({method:'POST',url:'/v1/capital/preview',headers,payload:defaultMandate})).json().capitalBasis.balanceAtomic).toBe(atomic(4000));expect((await app.inject({method:'POST',url:'/v1/capital/policy',headers:{cookie,origin:'https://wrong.example'},payload:{policy,expectedRevision:1}})).statusCode).toBe(403);fail=true;expect((await app.inject({method:'POST',url:'/v1/capital/refresh',headers,payload:{}})).statusCode).toBe(503);expect((await app.inject({method:'POST',url:'/v1/capital/preview',headers,payload:defaultMandate})).statusCode).toBe(409);}finally{await app.close();}});
});
