import {afterEach,describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';
import {Ledger,embeddedDatabase} from '@mandate/store';
import type {CapitalCheckpoint,ResearchCashRaising,PlanRevisionRecord} from '@mandate/domain';
import {createApp} from '../apps/api/src/app.ts';
import {passportDefinitions} from '../apps/api/src/passports.ts';
import {capitalAccountId} from '../apps/api/src/capital.ts';
import {freshPassportRoot} from './fresh-passport-root.ts';
import fs from 'node:fs';
const defs=passportDefinitions(),origin='http://127.0.0.1:3110',atomic=(n:number)=>(BigInt(n)*10n**18n).toString();
const ledgers:Ledger[]=[],apps:ReturnType<typeof createApp>[]=[],roots:string[]=[];
afterEach(async()=>{for(const app of apps.splice(0))await app.close();for(const ledger of ledgers.splice(0))await ledger.close();for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});
async function login(app:ReturnType<typeof createApp>,signer=privateKeyToAccount(generatePrivateKey())){const c=(await app.inject({method:'POST',url:'/v1/wallet/challenge',headers:{origin},payload:{address:signer.address,chainId:56}})).json();const v=await app.inject({method:'POST',url:'/v1/wallet/verify',headers:{origin},payload:{challengeId:c.id,signature:await signer.signMessage({message:c.message})}});expect(v.statusCode).toBe(200);return {origin,cookie:String(v.headers['set-cookie']).split(';')[0]};}
async function setup(){const ledger=new Ledger(embeddedDatabase());ledgers.push(ledger);await ledger.migrate();await ledger.migrate();const signer=privateKeyToAccount(generatePrivateKey()),id=capitalAccountId(signer.address),now=new Date().toISOString();
 const checkpoint:CapitalCheckpoint={accountId:id,wallet:signer.address.toLowerCase(),asset:{chainId:56,contract:'0x55d398326f99059ff775485246999027b3197955',decimals:18},balanceAtomic:atomic(100),blockNumber:'100',blockHash:'0x'+'2'.repeat(64),observedAt:now,evidenceMode:'observed',positions:defs.map(p=>({contract:p.contract,symbol:p.symbol,decimals:18,rawAtomic:atomic(p.symbol==='SPYon'?70:p.symbol==='NVDAon'?30:0),multiplierAtomic:null,adjustedAtomic:null,accountingVersion:'raw-token-v1',state:'OBSERVED'}))};
 await ledger.applyCapitalCheckpoint(checkpoint);await ledger.saveCapitalPolicy(id,{reserveFloor:'20',operatingBudget:'0',obligations:[]},(await ledger.capitalState(id))!.revision);const policy={allocations:[{underlying:'SPY',weightBps:5000},{underlying:'NVDA',weightBps:5000}],maxIssuerBps:10000,maxCostBps:30,allowLeveraged:false,representationAllowlist:defs.map(p=>p.contract),exposureScope:'tracked-holdings-pending-proposed' as const};await ledger.saveInvestmentMandate(id,policy,0);
 const root=freshPassportRoot();roots.push(root);const app=createApp(root,{ledger,marketReader:async()=>({source:'Synthetic test marks',observedAt:new Date().toISOString(),items:defs.map(p=>({contract:p.contract,issuer:p.issuer,price:'1',updatedAt:new Date().toISOString()}))})});apps.push(app);const headers=await login(app,signer),body=()=>({mandateRevision:1,scenario:'normal' as const,target:'100',requestId:randomUUID()});return {ledger,app,headers,body,id,policy,checkpoint};
}
describe('saved cash-raising research',{timeout:60000},()=>{
 it('stores server evidence, replays identical requests and never creates a hold',async()=>{const {app,headers,body,ledger,id}=await setup(),payload=body(),r=await app.inject({method:'POST',url:'/v1/capital/cash-raising',headers,payload});expect(r.statusCode).toBe(200);const record:ResearchCashRaising=r.json().cashRaising;expect(record.result.executable).toBe(false);expect(record.result.status).toBe('feasible');expect(record.inputs.checkpoint.positions).toHaveLength(14);expect(record.inputs.marks.items).toHaveLength(14);expect(record.inputs.passports.items).toHaveLength(14);expect(record.result.legs.some(l=>l.side==='SELL'&&l.funding==='modeled-sale-proceeds')).toBe(true);expect((await app.inject({method:'POST',url:'/v1/capital/cash-raising',headers,payload})).json().cashRaising).toEqual(record);expect((await app.inject({method:'POST',url:'/v1/capital/cash-raising',headers,payload:{...payload,target:'100.0'}})).json().cashRaising).toEqual(record);expect(await ledger.cashRaisingHistory(id)).toEqual([record]);expect((await ledger.capitalState(id))!.heldAtomic).toBe('0');expect((await app.inject({method:'POST',url:'/v1/capital/cash-raising',headers,payload:{...payload,target:'200'}})).statusCode).toBe(409);});
 it('isolates wallet history and rejects injected inputs, origin changes and absent sessions',async()=>{const {app,headers,body}=await setup(),payload=body();expect((await app.inject({method:'GET',url:'/v1/capital/cash-raising'})).statusCode).toBe(401);expect((await app.inject({method:'POST',url:'/v1/capital/cash-raising',payload})).statusCode).toBe(401);expect((await app.inject({method:'POST',url:'/v1/capital/cash-raising',headers:{...headers,origin:'https://wrong.example'},payload})).statusCode).toBe(403);expect((await app.inject({method:'POST',url:'/v1/capital/cash-raising',headers,payload:{...payload,balanceAtomic:atomic(999)}})).statusCode).toBe(400);for(const target of ['0','-1','1e2','0.0000000000000000001'])expect((await app.inject({method:'POST',url:'/v1/capital/cash-raising',headers,payload:{...payload,target}})).statusCode).toBe(400);await app.inject({method:'POST',url:'/v1/capital/cash-raising',headers,payload});expect((await app.inject({method:'GET',url:'/v1/capital/cash-raising',headers:await login(app)})).json().items).toEqual([]);});
 it('rejects changed rules and tampered results without rewriting recorded history',async()=>{const {app,headers,body,ledger,id,policy}=await setup();const record=(await app.inject({method:'POST',url:'/v1/capital/cash-raising',headers,payload:body()})).json().cashRaising;await expect(ledger.saveResearchCashRaising({...record,id:randomUUID(),requestId:randomUUID(),result:{...record.result,feeAtomic:'0'}})).rejects.toThrow('INVALID_RESEARCH_CASH_RAISING');await ledger.saveInvestmentMandate(id,{...policy,maxIssuerBps:7000},1);await expect(ledger.saveResearchCashRaising({...record,id:randomUUID(),requestId:randomUUID()})).rejects.toThrow('STALE_MANDATE');expect((await app.inject({method:'POST',url:'/v1/capital/cash-raising',headers,payload:body()})).statusCode).toBe(409);expect(await ledger.cashRaisingHistory(id)).toEqual([record]);});
 it('rejects a submission barrier race even when the account revision is unchanged',async()=>{const {app,headers,body,ledger,id,checkpoint}=await setup(),capital=(await ledger.capitalState(id))!,spy=defs.find(p=>p.symbol==='SPYon')!;const plan:PlanRevisionRecord={schemaVersion:'1.0.0',id:randomUUID(),accountId:id,revision:1,accountRevision:capital.revision,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+60000).toISOString(),decisionId:'test',inputHash:'a'.repeat(64),maximumDebit:{asset:checkpoint.asset,atomic:atomic(1)},evidenceMode:'live',exposureModel:{currency:'USD-nominal-USDT-parity',legs:[{instrumentId:spy.contract,underlying:'SPY',issuer:'ondo',valueAtomic:atomic(1)}]}};await ledger.savePlan(plan);const hold=await ledger.reserve({accountId:id,planRevisionId:plan.id,idempotencyKey:'held',amountAtomic:atomic(1)});const record=(await app.inject({method:'POST',url:'/v1/capital/cash-raising',headers,payload:body()})).json().cashRaising;await ledger.beginSubmission(hold.id,'attempt');await expect(ledger.saveResearchCashRaising({...record,id:randomUUID(),requestId:randomUUID()})).rejects.toThrow('STALE_PROPOSAL_INPUTS');const r=(await app.inject({method:'POST',url:'/v1/capital/cash-raising',headers,payload:body()})).json().cashRaising;expect(r.result.status).toBe('blocked');expect(r.inputs.portfolio.state).toBe('UNKNOWN');expect((await ledger.capitalState(id))!.heldAtomic).toBe(atomic(1));});
});
