import {describe,it,expect} from 'vitest';
import {assessPortfolio,previewCashRaising,defaultMandate} from '@mandate/core';
import type {ResearchProposal,CapitalCheckpoint} from '@mandate/domain';
import {passportDefinitions} from '../apps/api/src/passports.ts';
const defs=passportDefinitions(),unit=10n**18n,atomic=(n:number)=>(BigInt(n)*unit).toString(),now=new Date();
const contract=(symbol:string)=>defs.find(p=>p.symbol===symbol)!.contract;
function fixture(holdings:Record<string,number>={SPYon:70,NVDAon:30}):ResearchProposal['inputs']{
 const checkpoint:CapitalCheckpoint={accountId:'a',wallet:'0x'+'1'.repeat(40),asset:{chainId:56,contract:'0x55d398326f99059ff775485246999027b3197955',decimals:18},balanceAtomic:atomic(20),blockNumber:'100',blockHash:'0x'+'2'.repeat(64),observedAt:now.toISOString(),evidenceMode:'observed',positions:defs.map(p=>({contract:p.contract,symbol:p.symbol,decimals:18,rawAtomic:atomic(holdings[p.symbol]??0),multiplierAtomic:null,adjustedAtomic:null,accountingVersion:'raw-token-v1',state:'OBSERVED'}))};
 const marks={source:'synthetic test marks',observedAt:now.toISOString(),items:defs.map(p=>({contract:p.contract,issuer:p.issuer,price:'1',updatedAt:now.toISOString()}))};
 const candidates=defs.map(p=>({id:p.contract,contract:p.contract,name:p.symbol,underlying:p.underlying,issuer:p.issuer,category:p.category,accounting:'raw' as const,leveraged:false,evidenceMode:'research' as const,executionCertified:false as const,researchEligible:true}));
 return {cashPolicyRevision:0,cashPolicy:{reserveFloor:'20',operatingBudget:'0',obligations:[]},mandate:{...defaultMandate,allocations:[{underlying:'SPY',weightBps:5000},{underlying:'NVDA',weightBps:5000}],maxIssuerBps:10000,maxCostBps:30,representationAllowlist:defs.map(p=>p.contract)},funding:{accountId:'a',accountRevision:1,checkpointId:'c',blockNumber:'100',observedAt:now.toISOString(),balanceAtomic:atomic(20),protectedAtomic:atomic(20),heldAtomic:'0',decimals:18},checkpoint,marks,portfolio:assessPortfolio(checkpoint,defs,marks,[],now.getTime()),pending:[],candidates,quotes:candidates.map(i=>({instrumentId:i.id,costBps:10,available:true,evidenceMode:'synthetic' as const})),passports:{schemaVersion:'1.0',checkedAt:now.toISOString(),items:[]}};
}
describe('net cash-raising research',()=>{
 it('uses only free cash and leaves protections plus holds intact',()=>{const i=fixture();i.funding.balanceAtomic=atomic(100);i.funding.heldAtomic=atomic(10);const r=previewCashRaising(i,'50',now);expect(r.status).toBe('feasible');expect(r.availableCashAtomic).toBe(atomic(70));expect(r.legs).toHaveLength(0);expect(r.projectedCashAfterPayoutAtomic).toBe(atomic(50));});
 it('sizes a raw-token sale to cover net proceeds after upward-rounded fees',()=>{const i=fixture(),r=previewCashRaising(i,'30',now);expect(r.status).toBe('feasible');expect(BigInt(r.netSaleAtomic)).toBeGreaterThanOrEqual(30n*unit);expect(BigInt(r.grossSaleAtomic)).toBeGreaterThan(30n*unit);expect(BigInt(r.feeAtomic)).toBeGreaterThan(0n);expect(BigInt(r.projectedCashAfterPayoutAtomic!)).toBeGreaterThanOrEqual(20n*unit);expect(r.legs.every(l=>l.side==='SELL'&&l.funding==='modeled-sale-proceeds')).toBe(true);expect(r.executable).toBe(false);});
 it('restores an existing protection gap before covering the payout',()=>{const i=fixture();i.funding.balanceAtomic=atomic(5);i.funding.heldAtomic=atomic(10);const r=previewCashRaising(i,'20',now);expect(r.status).toBe('feasible');expect(r.protectionGapAtomic).toBe(atomic(25));expect(r.saleNeededAtomic).toBe(atomic(45));expect(BigInt(r.projectedCashAfterPayoutAtomic!)).toBeGreaterThanOrEqual(30n*unit);});
 it('reports a precise shortfall and never spends protected cash',()=>{const r=previewCashRaising(fixture(),'150',now);expect(r.status).toBe('shortfall');expect(BigInt(r.shortfallAtomic!)).toBe(150n*unit-BigInt(r.netSaleAtomic));expect(r.remainingExposureAtomic).toBe('0');expect(r.projectedCashAfterPayoutAtomic).toBe(atomic(20));});
 it('keeps a remaining protection gap explicit when even restoration is impossible',()=>{const i=fixture({SPYon:1});i.funding.balanceAtomic='0';const r=previewCashRaising(i,'10',now);expect(r.status).toBe('shortfall');expect(r.modeledPayoutAtomic).toBe('0');expect(BigInt(r.protectionGapAfterAtomic!)).toBeGreaterThan(0n);expect(r.shortfallAtomic).toBe(atomic(10));});
 it('requires exact sale selection and fresh permitted quotes',()=>{const i=fixture();i.mandate.representationAllowlist=[];const r=previewCashRaising(i,'10',now);expect(r.status).toBe('shortfall');expect(r.legs).toHaveLength(0);expect(r.excluded.every(e=>e.reason.includes('not selected'))).toBe(true);i.mandate.representationAllowlist=i.candidates.map(c=>c.id);i.quotes.forEach(q=>q.available=false);expect(previewCashRaising(i,'10',now).excluded.every(e=>e.reason.includes('unavailable'))).toBe(true);});
 it('repairs remaining issuer concentration rather than blindly selling the cheapest minority',()=>{const i=fixture({SPYon:70,SPYB:30});i.mandate.allocations=[{underlying:'SPY',weightBps:10000}];i.mandate.maxIssuerBps=7000;i.quotes.forEach(q=>q.costBps=q.instrumentId===contract('SPYB')?0:10);const r=previewCashRaising(i,'10',now);expect(r.status).toBe('feasible');for(const e of r.issuerExposure)expect(BigInt(e.exposureAtomic)*10000n<=BigInt(r.remainingExposureAtomic!)*7000n).toBe(true);});
 it('does not sell pending positions or double-use pending cash',()=>{const i=fixture({SPYon:70,SPYB:30});i.funding.heldAtomic=atomic(10);i.funding.balanceAtomic=atomic(30);i.portfolio.pending=[{symbol:'SPYB',instrumentId:contract('SPYB'),issuer:'bstock',underlying:'SPY',valueAtomic:atomic(10)}];const r=previewCashRaising(i,'50',now);expect(r.availableCashAtomic).toBe('0');expect(r.remaining.find(g=>g.underlying==='SPY')?.pendingAtomic).toBe(atomic(10));for(const l of r.legs)expect(BigInt(l.quantityAtomic)).toBeLessThanOrEqual(BigInt(i.checkpoint.positions.find(p=>p.contract===l.instrumentId)!.rawAtomic!));});
 it('blocks sales when fixed pending exposure cannot satisfy remaining issuer policy',()=>{const i=fixture({SPYon:10});i.mandate.maxIssuerBps=7000;i.portfolio.pending=[{symbol:'SPYon',instrumentId:contract('SPYon'),issuer:'ondo',underlying:'SPY',valueAtomic:atomic(100)}];const r=previewCashRaising(i,'1',now);expect(r.status).toBe('blocked');expect(r.legs).toHaveLength(0);expect(r.shortfallAtomic).toBeNull();expect(r.reasons[0]).toContain('fixed pending');});
 it('blocks unknown/stale evidence and rejects zero or excess-precision targets',()=>{const i=fixture();i.portfolio.state='UNKNOWN';expect(previewCashRaising(i,'1',now).shortfallAtomic).toBeNull();i.portfolio.state='KNOWN';expect(previewCashRaising(i,'1',new Date(now.getTime()+60001)).status).toBe('blocked');expect(()=>previewCashRaising(i,'0',now)).toThrow();expect(()=>previewCashRaising(i,'0.0000000000000000001',now)).toThrow();});
 it('uses precise raw marks once and meets an atomic-unit payout',()=>{const i=fixture();i.marks.items.forEach(m=>m.price='3.123456789123456789');i.portfolio=assessPortfolio(i.checkpoint,defs,i.marks,[],now.getTime());const r=previewCashRaising(i,'0.000000000000000001',now);expect(r.status).toBe('feasible');expect(BigInt(r.netSaleAtomic)).toBeGreaterThanOrEqual(1n);for(const l of r.legs)expect(BigInt(l.markNotionalAtomic)).toBe(BigInt(l.quantityAtomic)*3123456789123456789n/unit);});
});
