import {describe,it,expect} from 'vitest';
import {assessPortfolio,previewInvestment,classifyInflow,defaultMandate} from '@mandate/core';
import type {ResearchProposal,CapitalCheckpoint} from '@mandate/domain';
import {passportDefinitions} from '../apps/api/src/passports.ts';
const defs=passportDefinitions(),unit=10n**18n,atomic=(n:number)=>(BigInt(n)*unit).toString(),now=new Date();
const contract=(symbol:string)=>defs.find(p=>p.symbol===symbol)!.contract;
function fixture(holdings:Record<string,number>={SPYon:70,NVDAon:30}):ResearchProposal['inputs']{
 const checkpoint:CapitalCheckpoint={accountId:'a',wallet:'0x'+'1'.repeat(40),asset:{chainId:56,contract:'0x55d398326f99059ff775485246999027b3197955',decimals:18},balanceAtomic:atomic(20),blockNumber:'100',blockHash:'0x'+'2'.repeat(64),observedAt:now.toISOString(),evidenceMode:'observed',positions:defs.map(p=>({contract:p.contract,symbol:p.symbol,decimals:18,rawAtomic:atomic(holdings[p.symbol]??0),multiplierAtomic:null,adjustedAtomic:null,accountingVersion:'raw-token-v1',state:'OBSERVED'}))};
 const marks={source:'synthetic test marks',observedAt:now.toISOString(),items:defs.map(p=>({contract:p.contract,issuer:p.issuer,price:'1',updatedAt:now.toISOString()}))};
 const candidates=defs.map(p=>({id:p.contract,contract:p.contract,name:p.symbol,underlying:p.underlying,issuer:p.issuer,category:p.category,accounting:'raw' as const,leveraged:false,evidenceMode:'research' as const,executionCertified:false as const,researchEligible:true}));
 return {cashPolicyRevision:0,cashPolicy:{reserveFloor:'20',operatingBudget:'0',obligations:[]},mandate:{...defaultMandate,allocations:[{underlying:'SPY',weightBps:5000},{underlying:'NVDA',weightBps:5000}],maxIssuerBps:10000,maxCostBps:30,representationAllowlist:defs.map(p=>p.contract)},funding:{accountId:'a',accountRevision:1,checkpointId:'c',blockNumber:'100',observedAt:now.toISOString(),balanceAtomic:atomic(20),protectedAtomic:atomic(20),heldAtomic:'0',decimals:18},checkpoint,marks,portfolio:assessPortfolio(checkpoint,defs,marks,[],now.getTime()),pending:[],candidates,quotes:candidates.map(i=>({instrumentId:i.id,costBps:10,available:true,evidenceMode:'synthetic' as const})),passports:{schemaVersion:'1.0',checkedAt:now.toISOString(),items:[]}};
}
const proof=()=>({chainId:56 as const,token:'0x55d398326f99059ff775485246999027b3197955' as const,decimals:18 as const,wallet:'0x'+'1'.repeat(40),transactionHash:'0x'+'a'.repeat(64),transactionSender:'0x'+'2'.repeat(40),blockNumber:'90',blockHash:'0x'+'b'.repeat(64),headNumber:'105',headHash:'0x'+'c'.repeat(64),observedAt:now.toISOString(),incoming:[{logIndex:1,from:'0x'+'2'.repeat(40),to:'0x'+'1'.repeat(40),amountAtomic:atomic(10)}],usdtOutgoingAtomic:'0',outgoingAssets:[] as {contract:string;logIndex:number;amountAtomic:string}[]});
describe('incoming-funds classification',()=>{
 it('requires source review; a receipt does not automatically establish external funding',()=>{expect(classifyInflow(proof(),'unclassified',now.getTime())).toMatchObject({kind:'unclassified',eligibleForProposal:false,netAtomic:atomic(10),confirmations:'16'});expect(classifyInflow(proof(),'external',now.getTime())).toMatchObject({kind:'external',eligibleForProposal:true});});
 it('excludes reviewed internal transfers and known app settlements',()=>{expect(classifyInflow(proof(),'internal',now.getTime()).eligibleForProposal).toBe(false);expect(classifyInflow(proof(),'external',now.getTime(),true).kind).toBe('internal');});
 it('excludes sale/conversion activity even when labeled external',()=>{const p=proof();p.outgoingAssets=[{contract:contract('SPYon'),logIndex:0,amountAtomic:atomic(1)}];expect(classifyInflow(p,'external',now.getTime())).toMatchObject({kind:'conversion',eligibleForProposal:false});p.usdtOutgoingAtomic=atomic(2);expect(classifyInflow(p,'external',now.getTime()).netAtomic).toBe(atomic(8));});
 it('does not promote self-initiated or mint-origin receipts to external funding',()=>{const p=proof();p.transactionSender=p.wallet;expect(classifyInflow(p,'external',now.getTime()).kind).toBe('unclassified');p.transactionSender='0x'+'2'.repeat(40);p.incoming[0].from='0x'+'0'.repeat(40);expect(classifyInflow(p,'external',now.getTime()).eligibleForProposal).toBe(false);});
 it('rejects wrong payment identity, insufficient confirmations and stale observations',()=>{const p=proof();p.token=contract('SPYon') as typeof p.token;expect(()=>classifyInflow(p,'external',now.getTime())).toThrow();const q=proof();q.headNumber='100';expect(()=>classifyInflow(q,'external',now.getTime())).toThrow();expect(()=>classifyInflow(proof(),'external',now.getTime()+60001)).toThrow();});
 it('rejects duplicate/self/foreign incoming logs and non-positive net amounts',()=>{const p=proof();p.incoming.push(p.incoming[0]);expect(()=>classifyInflow(p,'external',now.getTime())).toThrow();p.incoming=[p.incoming[0]];p.incoming[0].from=p.wallet;expect(()=>classifyInflow(p,'external',now.getTime())).toThrow();const q=proof();q.usdtOutgoingAtomic=atomic(10);expect(()=>classifyInflow(q,'external',now.getTime())).toThrow();});
 it('caps all allocation legs without changing the observed cash basis',()=>{const i=fixture();i.funding.balanceAtomic=atomic(120);const r=previewInvestment(i.mandate,i.candidates,i.quotes,now,i.funding,i.portfolio,atomic(7));expect(r.status).toBe('feasible');expect(r.capitalBasis?.balanceAtomic).toBe(atomic(120));expect(r.investableAtomic).toBe(atomic(7));expect(r.legs.reduce((a,l)=>a+BigInt(l.grossAtomic),0n)).toBe(7n*unit);expect(previewInvestment(i.mandate,i.candidates,i.quotes,now,i.funding,i.portfolio).investableAtomic).toBe(atomic(100));});
 it('caps contributions again when current protections and holds leave less free cash',()=>{const i=fixture();i.funding.balanceAtomic=atomic(30);i.funding.heldAtomic=atomic(8);const r=previewInvestment(i.mandate,i.candidates,i.quotes,now,i.funding,i.portfolio,atomic(10));expect(r.investableAtomic).toBe(atomic(2));expect(r.legs.reduce((a,l)=>a+BigInt(l.grossAtomic),0n)).toBe(2n*unit);expect(()=>previewInvestment(i.mandate,i.candidates,i.quotes,now,i.funding,i.portfolio,'-1')).toThrow();});
});
