import {afterEach,describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';
import {Ledger,embeddedDatabase} from '@mandate/store';
import type {CapitalCheckpoint,InflowProof,ResearchProposal} from '@mandate/domain';
import {createApp} from '../apps/api/src/app.ts';
import {passportDefinitions} from '../apps/api/src/passports.ts';
import {capitalAccountId} from '../apps/api/src/capital.ts';
import {freshPassportRoot} from './fresh-passport-root.ts';
import fs from 'node:fs';
const defs=passportDefinitions(),origin='http://127.0.0.1:3110',atomic=(n:number)=>(BigInt(n)*10n**18n).toString(),hash='0x'+'a'.repeat(64);
const ledgers:Ledger[]=[],apps:ReturnType<typeof createApp>[]=[],roots:string[]=[];
afterEach(async()=>{for(const app of apps.splice(0))await app.close();for(const ledger of ledgers.splice(0))await ledger.close();for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});
async function login(app:ReturnType<typeof createApp>,signer=privateKeyToAccount(generatePrivateKey())){const c=(await app.inject({method:'POST',url:'/v1/wallet/challenge',headers:{origin},payload:{address:signer.address,chainId:56}})).json();const v=await app.inject({method:'POST',url:'/v1/wallet/verify',headers:{origin},payload:{challengeId:c.id,signature:await signer.signMessage({message:c.message})}});return {origin,cookie:String(v.headers['set-cookie']).split(';')[0]};}
async function setup(){const ledger=new Ledger(embeddedDatabase());ledgers.push(ledger);await ledger.migrate();await ledger.migrate();const signer=privateKeyToAccount(generatePrivateKey()),id=capitalAccountId(signer.address),state={block:100,cash:100,fail:false,outgoing:false,reads:0};
 const cp=(wallet:string):CapitalCheckpoint=>({accountId:capitalAccountId(wallet),wallet:wallet.toLowerCase(),asset:{chainId:56,contract:'0x55d398326f99059ff775485246999027b3197955',decimals:18},balanceAtomic:atomic(state.cash),blockNumber:String(state.block),blockHash:'0x'+BigInt(state.block).toString(16).padStart(64,'0'),observedAt:new Date().toISOString(),evidenceMode:'observed',positions:defs.map(p=>({contract:p.contract,symbol:p.symbol,decimals:18,rawAtomic:'0',multiplierAtomic:null,adjustedAtomic:null,accountingVersion:'raw-token-v1',state:'OBSERVED'}))});
 await ledger.applyCapitalCheckpoint(cp(signer.address));await ledger.saveCapitalPolicy(id,{reserveFloor:'20',operatingBudget:'0',obligations:[]},(await ledger.capitalState(id))!.revision);await ledger.saveInvestmentMandate(id,{allocations:[{underlying:'SPY',weightBps:10000}],maxIssuerBps:10000,maxCostBps:30,allowLeveraged:false,representationAllowlist:defs.map(p=>p.contract),exposureScope:'tracked-holdings-pending-proposed'},0);
 const root=freshPassportRoot();roots.push(root);const app=createApp(root,{ledger,capitalReader:async wallet=>{state.block++;return cp(wallet);},marketReader:async()=>({observedAt:new Date().toISOString(),source:'test',items:[]}),inflowReader:async(wallet,transactionHash):Promise<InflowProof>=>{state.reads++;if(state.fail)throw new Error('RPC failed');return {chainId:56,token:'0x55d398326f99059ff775485246999027b3197955',decimals:18,wallet:wallet.toLowerCase(),transactionHash,transactionSender:'0x'+'2'.repeat(40),blockNumber:'90',blockHash:'0x'+'b'.repeat(64),headNumber:String(state.block+12),headHash:'0x'+'c'.repeat(64),observedAt:new Date().toISOString(),incoming:[{logIndex:1,from:'0x'+'2'.repeat(40),to:wallet.toLowerCase(),amountAtomic:atomic(25)}],usdtOutgoingAtomic:'0',outgoingAssets:state.outgoing?[{contract:defs[0].contract,logIndex:0,amountAtomic:atomic(1)}]:[]};}});apps.push(app);const headers=await login(app,signer);
 const check=(review='unclassified',expectedRevision=0)=>app.inject({method:'POST',url:'/v1/capital/inflows/check',headers,payload:{transactionHash:hash,review,expectedRevision}});
 const propose=(expectedReviewRevision:number,requestId=randomUUID())=>({transactionHash:hash,mandateRevision:1,scenario:'normal' as const,expectedReviewRevision,requestId});return {app,ledger,headers,id,state,check,propose};
}
describe('reviewed incoming-funds proposals',{timeout:60000},()=>{
 it('records receipt review without crediting cash and requires explicit source review',async()=>{const {check,app,headers,propose,ledger,id}=await setup();const r=await check();expect(r.statusCode).toBe(200);const record=r.json().record;expect(record.classification.kind).toBe('unclassified');expect((await ledger.capitalState(id))!.balanceAtomic).toBe(atomic(100));expect((await app.inject({method:'POST',url:'/v1/capital/inflows/propose',headers,payload:propose(record.revision)})).statusCode).toBe(409);const next=(await check('external',record.revision)).json().record;expect(next.classification.eligibleForProposal).toBe(true);expect(next.revision).toBe(2);expect((await ledger.capitalState(id))!.balanceAtomic).toBe(atomic(100));});
 it('refreshes cash, caps source budgets and records one initial proposal with retry replay',async()=>{const {check,app,headers,propose,ledger,id,state}=await setup();const r=(await check('external')).json().record;state.cash=30;const payload=propose(r.revision),response=await app.inject({method:'POST',url:'/v1/capital/inflows/propose',headers,payload});expect(response.statusCode).toBe(200);const p:ResearchProposal=response.json().proposal;expect(p.inputs.inflowProof?.transactionHash).toBe(hash);expect(p.inflow?.budgetCapAtomic).toBe(atomic(25));expect(p.inputs.funding.balanceAtomic).toBe(atomic(30));expect(p.result.investableAtomic).toBe(atomic(10));expect(p.result.legs.reduce((a,l)=>a+BigInt(l.grossAtomic),0n)).toBe(10n*10n**18n);expect(p.result.executable).toBe(false);const reads=state.reads;expect((await app.inject({method:'POST',url:'/v1/capital/inflows/propose',headers,payload})).json().proposal).toEqual(p);expect(state.reads).toBe(reads);const current=(await ledger.inflowRecord(id,hash))!;expect((await app.inject({method:'POST',url:'/v1/capital/inflows/propose',headers,payload:propose(current.revision)})).statusCode).toBe(409);expect((await ledger.capitalState(id))!.heldAtomic).toBe('0');expect((await ledger.inflowHistory(id))[0].proposalId).toBe(p.id);expect((await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload:{mandateRevision:1,scenario:'normal',requestId:payload.requestId}})).statusCode).toBe(409);});
 it('preserves inflow caps through revalidation and blocks a later internal-source review',async()=>{const {check,app,headers,propose,ledger,id}=await setup();const r=(await check('external')).json().record,p=(await app.inject({method:'POST',url:'/v1/capital/inflows/propose',headers,payload:propose(r.revision)})).json().proposal;const body=()=>({proposalId:p.id,mandateRevision:1,scenario:'normal',requestId:randomUUID()});const next=await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers,payload:body()});expect(next.statusCode).toBe(200);const q=next.json().proposal;expect(q.inflow.transactionHash).toBe(hash);expect(q.result.investableAtomic).toBe(atomic(25));expect(q.inputs.allocationBudgetCapAtomic).toBe(atomic(25));expect((await ledger.inflowHistory(id))[0].proposalId).toBe(p.id);expect(await ledger.researchProposalById(id,p.id)).toEqual(p);const current=(await ledger.inflowRecord(id,hash))!;await check('internal',current.revision);expect((await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers,payload:body()})).statusCode).toBe(409);});
 it('excludes conversion receipts and retains unknown proof failures',async()=>{const {state,check,app,headers,propose,ledger,id}=await setup();state.outgoing=true;const record=(await check('external')).json().record;expect(record.classification.kind).toBe('conversion');expect((await app.inject({method:'POST',url:'/v1/capital/inflows/propose',headers,payload:propose(record.revision)})).statusCode).toBe(409);state.fail=true;expect((await check('external',record.revision)).statusCode).toBe(503);expect(await ledger.inflowRecord(id,hash)).toEqual(record);expect(await ledger.researchHistory(id)).toHaveLength(0);});
 it('isolates wallets/origins and rejects caller amounts or proof fields',async()=>{const {app,headers,check,state}=await setup(),payload={transactionHash:hash,review:'external',expectedRevision:0};expect((await app.inject({method:'GET',url:'/v1/capital/inflows'})).statusCode).toBe(401);expect((await app.inject({method:'POST',url:'/v1/capital/inflows/check',payload})).statusCode).toBe(401);expect((await app.inject({method:'POST',url:'/v1/capital/inflows/check',headers:{...headers,origin:'https://wrong.example'},payload})).statusCode).toBe(403);expect((await app.inject({method:'POST',url:'/v1/capital/inflows/check',headers,payload:{...payload,netAtomic:atomic(999)}})).statusCode).toBe(400);expect(state.reads).toBe(0);await check('external');expect((await app.inject({method:'GET',url:'/v1/capital/inflows',headers:await login(app)})).json().items).toEqual([]);});
 it('prevents concurrent duplicate triggers and rejects modified source budgets',async()=>{const {check,app,headers,propose,ledger,id}=await setup();const record=(await check('external')).json().record;const results=await Promise.all([app.inject({method:'POST',url:'/v1/capital/inflows/propose',headers,payload:propose(record.revision)}),app.inject({method:'POST',url:'/v1/capital/inflows/propose',headers,payload:propose(record.revision)})]);expect(results.filter(r=>r.statusCode===200)).toHaveLength(1);const p=(await ledger.researchHistory(id))[0];await expect(ledger.saveResearchProposal({...p,id:randomUUID(),requestId:randomUUID(),inflow:{...p.inflow!,budgetCapAtomic:atomic(99)},inputs:{...p.inputs,allocationBudgetCapAtomic:atomic(99)}})).rejects.toThrow('INELIGIBLE_INFLOW');expect(await ledger.researchHistory(id)).toHaveLength(1);});
});
