import {afterEach,describe,expect,it} from 'vitest';
import {assessPortfolio,previewInvestment,defaultMandate} from '@mandate/core';
import {Ledger,embeddedDatabase} from '@mandate/store';
import type {CapitalCheckpoint,CapitalFunding,MarketMarks,Instrument,ScenarioQuote,PendingExposure,PlanRevisionRecord} from '@mandate/domain';
import {passportDefinitions} from '../apps/api/src/passports.ts';
import {capitalAccountId} from '../apps/api/src/capital.ts';
const defs=passportDefinitions(),spy=defs.find(p=>p.symbol==='SPYon')!,spyb=defs.find(p=>p.symbol==='SPYB')!,unit=10n**18n,amount=(n:number)=>(BigInt(n)*unit).toString();
const wallet='0x'+'2'.repeat(40),now=new Date(),asset={chainId:56,contract:'0x55d398326f99059ff775485246999027b3197955',decimals:18};
function cp():CapitalCheckpoint{return {accountId:capitalAccountId(wallet),wallet,asset,balanceAtomic:amount(1000),blockNumber:'123',blockHash:'0x'+'3'.repeat(64),observedAt:now.toISOString(),evidenceMode:'observed',positions:defs.map(p=>({contract:p.contract,symbol:p.symbol,decimals:18,rawAtomic:'0',multiplierAtomic:unit.toString(),adjustedAtomic:'0',accountingVersion:'bep677-floor-v1',state:'OBSERVED'}))};}
function marks():MarketMarks{return {observedAt:now.toISOString(),source:'test model',items:defs.map(p=>({contract:p.contract,issuer:p.issuer,price:'1',updatedAt:now.toISOString()}))};}
function holdings(){const c=cp();c.positions.find(p=>p.contract===spy.contract)!.rawAtomic=amount(80);c.positions.find(p=>p.contract===spy.contract)!.adjustedAtomic=amount(80);c.positions.find(p=>p.contract===spyb.contract)!.rawAtomic=amount(20);c.positions.find(p=>p.contract===spyb.contract)!.adjustedAtomic=amount(20);return c;}
const funding:CapitalFunding={accountId:capitalAccountId(wallet),accountRevision:1,checkpointId:'checkpoint',blockNumber:'123',observedAt:now.toISOString(),balanceAtomic:amount(100),protectedAtomic:'0',heldAtomic:'0',decimals:18};
const candidates:Instrument[]=[spy,spyb].map(p=>({id:p.contract,contract:p.contract,underlying:'SPY',name:p.symbol,issuer:p.issuer,category:'ETF',accounting:'raw',leveraged:false,evidenceMode:'research',executionCertified:false,researchEligible:true}));
const quotes:ScenarioQuote[]=candidates.map(i=>({instrumentId:i.id,costBps:i.issuer==='ondo'?4:15,available:true,evidenceMode:'synthetic'}));
const input={...defaultMandate,allocations:[{underlying:'SPY',weightBps:10000}],representationAllowlist:[spy.contract,spyb.contract]};
function pending(value=60):PendingExposure{return {reservationId:'r',planId:'p',amountAtomic:amount(value),submissionStarted:false,model:{currency:'USD-nominal-USDT-parity',legs:[{instrumentId:spy.contract,issuer:'ondo',underlying:'SPY',valueAtomic:amount(value)}]}};}
let ledgers:Ledger[]=[];afterEach(async()=>{for(const l of ledgers)await l.close();ledgers=[];});
describe('portfolio-aware allocation',{timeout:60000},()=>{
 it('aggregates both representations by underlying and keeps issuer exposure separate',()=>{const book=assessPortfolio(holdings(),defs,marks(),[pending()],now.getTime());expect(book.state).toBe('KNOWN');expect(book.byUnderlying.find(g=>g.underlying==='SPY')).toMatchObject({existingAtomic:amount(100),pendingAtomic:amount(60)});expect(book.byIssuer.find(g=>g.issuer==='ondo')).toMatchObject({existingAtomic:amount(80),pendingAtomic:amount(60)});});
 it('values raw units once instead of applying a UI multiplier twice',()=>{const c=holdings(),p=c.positions.find(p=>p.contract===spy.contract)!;p.multiplierAtomic=amount(2);p.adjustedAtomic=amount(160);expect(assessPortfolio(c,defs,marks(),[],now.getTime()).existing.find(l=>l.instrumentId===spy.contract)?.valueAtomic).toBe(amount(80));});
 it('changes a real representation choice when the issuer cap changes',()=>{const book=assessPortfolio(holdings(),defs,marks(),[],now.getTime());const loose=previewInvestment({...input,maxIssuerBps:9500},candidates,quotes,now,funding,book),tight=previewInvestment({...input,maxIssuerBps:7000},candidates,quotes,now,funding,book);expect(loose.legs[0].instrumentId).toBe(spy.contract);expect(tight.legs[0].instrumentId).toBe(spyb.contract);expect(tight.executable).toBe(false);expect(tight.issuerExposure.find(e=>e.issuer==='ondo')?.shareBps).toBeLessThanOrEqual(7000);});
 it('does not substitute a matching ticker without selecting its exact contract',()=>{const book=assessPortfolio(holdings(),defs,marks(),[],now.getTime());const result=previewInvestment({...input,representationAllowlist:[spy.contract],maxIssuerBps:7000},candidates,quotes,now,funding,book);expect(result.status).toBe('infeasible');expect(result.excluded.find(e=>e.instrumentId===spyb.contract)?.reason).toContain('not been selected');});
 it('includes pending issuer exposure in the concentration test and blocks unresolved submissions',()=>{const book=assessPortfolio(holdings(),defs,marks(),[pending(120)],now.getTime());expect(previewInvestment({...input,maxIssuerBps:6000},candidates,quotes,now,{...funding,balanceAtomic:amount(220),heldAtomic:amount(120)},book).status).toBe('infeasible');expect(assessPortfolio(holdings(),defs,marks(),[{...pending(),submissionStarted:true}],now.getTime()).state).toBe('UNKNOWN');expect(assessPortfolio(cp(),defs,marks(),[{...pending(),model:null}],now.getTime()).state).toBe('UNKNOWN');});
 it('never treats missing positions or stale marks as zero, while observed emptiness needs no price',()=>{const c=holdings(),m=marks();m.items.find(m=>m.contract===spy.contract)!.updatedAt=new Date(now.getTime()-900001).toISOString();expect(assessPortfolio(c,defs,m,[],now.getTime()).state).toBe('UNKNOWN');expect(assessPortfolio({...c,positions:c.positions.slice(1)},defs,marks(),[],now.getTime()).state).toBe('UNKNOWN');expect(assessPortfolio(cp(),defs,{...marks(),items:[]},[],now.getTime()).state).toBe('KNOWN');});
 it('keeps decision identity stable across presentation timestamps, but binds exposure changes',()=>{const book=assessPortfolio(holdings(),defs,marks(),[],now.getTime());const a=previewInvestment(input,candidates,quotes,now,funding,book),b=previewInvestment(input,candidates,quotes,new Date(now.getTime()+1000),funding,{...book,checkedAt:new Date(now.getTime()+1000).toISOString()});expect(a.decisionId).toBe(b.decisionId);expect(previewInvestment(input,candidates,quotes,now,funding,assessPortfolio(holdings(),defs,marks(),[pending()],now.getTime())).decisionId).not.toBe(a.decisionId);});
 it('persists exact plan exposure, forbids partial holds and exposes uncertain legacy holds',async()=>{const ledger=new Ledger(embeddedDatabase());ledgers.push(ledger);await ledger.migrate();const c=cp();await ledger.applyCapitalCheckpoint(c);const plan:PlanRevisionRecord={schemaVersion:'1.0.0',id:'p',accountId:c.accountId,createdAt:now.toISOString(),revision:1,accountRevision:1,decisionId:'d',inputHash:'a'.repeat(64),maximumDebit:{asset,atomic:amount(60)},evidenceMode:'live',expiresAt:new Date(Date.now()+60000).toISOString(),exposureModel:pending().model!};await ledger.savePlan(plan);await expect(ledger.reserve({accountId:c.accountId,planRevisionId:'p',idempotencyKey:'partial',amountAtomic:amount(30)})).rejects.toThrow('EXPOSURE_RESERVATION_MUST_COVER_PLAN');const r=await ledger.reserve({accountId:c.accountId,planRevisionId:'p',idempotencyKey:'whole',amountAtomic:amount(60)});const state=(await ledger.capitalState(c.accountId))!;expect(state.pending[0].model?.legs[0].issuer).toBe('ondo');expect(assessPortfolio(c,defs,marks(),state.pending,Date.now()).state).toBe('KNOWN');await ledger.beginSubmission(r.id,'attempt');expect(assessPortfolio(c,defs,marks(),(await ledger.capitalState(c.accountId))!.pending,Date.now()).state).toBe('UNKNOWN');});
});
