import {describe,it,expect} from 'vitest';
import {assessPortfolio,previewRebalance,defaultMandate} from '@mandate/core';
import type {ResearchProposal,CapitalCheckpoint} from '@mandate/domain';
import {passportDefinitions} from '../apps/api/src/passports.ts';
const defs=passportDefinitions(),unit=10n**18n,atomic=(n:number)=>(BigInt(n)*unit).toString(),now=new Date();
const contract=(symbol:string)=>defs.find(p=>p.symbol===symbol)!.contract;
function fixture(holdings:Record<string,number>={SPYon:70,NVDAon:30}):ResearchProposal['inputs']{
 const checkpoint:CapitalCheckpoint={accountId:'a',wallet:'0x'+'1'.repeat(40),asset:{chainId:56,contract:'0x55d398326f99059ff775485246999027b3197955',decimals:18},balanceAtomic:atomic(20),blockNumber:'100',blockHash:'0x'+'2'.repeat(64),observedAt:now.toISOString(),evidenceMode:'observed',positions:defs.map(p=>({contract:p.contract,symbol:p.symbol,decimals:18,rawAtomic:atomic(holdings[p.symbol]??0),multiplierAtomic:null,adjustedAtomic:null,accountingVersion:'raw-token-v1',state:'OBSERVED'}))};
 const marks={source:'synthetic test marks',observedAt:now.toISOString(),items:defs.map(p=>({contract:p.contract,issuer:p.issuer,price:'1',updatedAt:now.toISOString()}))};
 const candidates=defs.map(p=>({id:p.contract,contract:p.contract,name:p.symbol,underlying:p.underlying,issuer:p.issuer,category:p.category,accounting:'raw' as const,leveraged:false,evidenceMode:'research' as const,executionCertified:false as const,researchEligible:true}));
 return {cashPolicyRevision:0,cashPolicy:{reserveFloor:'20',operatingBudget:'0',obligations:[]},mandate:{...defaultMandate,allocations:[{underlying:'SPY',weightBps:5000},{underlying:'NVDA',weightBps:5000}],maxIssuerBps:10000,maxCostBps:30,representationAllowlist:defs.map(p=>p.contract)},funding:{accountId:'a',accountRevision:1,checkpointId:'c',blockNumber:'100',observedAt:now.toISOString(),balanceAtomic:atomic(20),protectedAtomic:atomic(20),heldAtomic:'0',decimals:18},checkpoint,marks,portfolio:assessPortfolio(checkpoint,defs,marks,[],now.getTime()),pending:[],candidates,quotes:candidates.map(i=>({instrumentId:i.id,costBps:10,available:true,evidenceMode:'synthetic' as const})),passports:{schemaVersion:'1.0',checkedAt:now.toISOString(),items:[]}};
}
describe('rebalance research',()=>{
 it('sells overweight raw holdings, models fees and waits for sale settlement before buying',()=>{const i=fixture(),r=previewRebalance(i,false,now);expect(r.status).toBe('feasible');expect(r.executable).toBe(false);expect(r.legs.find(l=>l.side==='SELL')).toMatchObject({underlying:'SPY',funding:'modeled-sale-proceeds'});expect(r.legs.find(l=>l.side==='BUY')).toMatchObject({underlying:'NVDA',funding:'requires-sale-settlement'});expect(BigInt(r.feeAtomic)).toBeGreaterThan(0n);expect(BigInt(r.projectedCashAtomic!)).toBeGreaterThanOrEqual(BigInt(i.funding.protectedAtomic));for(const d of r.drift)expect(Math.abs(d.afterWeightBps!-d.targetWeightBps)).toBeLessThanOrEqual(1);});
 it('repairs issuer concentration even when underlying weights already match',()=>{const i=fixture({SPYon:80,SPYB:20});i.mandate.allocations=[{underlying:'SPY',weightBps:10000}];i.mandate.maxIssuerBps=7000;const r=previewRebalance(i,false,now);expect(r.status).toBe('feasible');expect(r.legs.some(l=>l.side==='SELL'&&l.issuer==='ondo')).toBe(true);expect(r.legs.some(l=>l.side==='BUY'&&l.issuer==='bstock')).toBe(true);for(const e of r.issuerExposure)expect(BigInt(e.exposureAtomic)*10000n<=BigInt(r.afterExposureAtomic!)*7000n).toBe(true);});
 it('leaves unused cash alone by default and contributes it only when selected',()=>{const i=fixture({SPYon:50,NVDAon:50});i.funding.balanceAtomic=atomic(100);expect(previewRebalance(i,false,now).status).toBe('unchanged');const r=previewRebalance(i,true,now);expect(r.status).toBe('feasible');expect(BigInt(r.cashUsedAtomic)).toBeGreaterThan(0n);expect(BigInt(r.projectedCashAtomic!)).toBeGreaterThanOrEqual(20n*unit);expect(r.legs.every(l=>l.side==='BUY'&&l.funding==='wallet-cash')).toBe(true);});
 it('counts pending exposure but never sells it or spends its held cash',()=>{const i=fixture();i.portfolio.pending=[{symbol:'SPYon',instrumentId:contract('SPYon'),issuer:'ondo',underlying:'SPY',valueAtomic:atomic(200)}];i.portfolio.byUnderlying.find(g=>g.underlying==='SPY')!.pendingAtomic=atomic(200);i.funding.heldAtomic=atomic(10);i.funding.balanceAtomic=atomic(40);const r=previewRebalance(i,true,now);expect(r.availableCashAtomic).toBe(atomic(10));expect(r.status).toBe('blocked');expect(r.reasons.join(' ')).toContain('pending exposure exceeds');expect(r.legs).toHaveLength(0);});
 it('blocks cash shortfall, unknown exposure and stale checkpoints',()=>{const i=fixture();i.funding.balanceAtomic='0';expect(previewRebalance(i,false,now).reasons[0]).toContain('cash-raising');i.funding.balanceAtomic=atomic(20);i.portfolio.state='UNKNOWN';expect(previewRebalance(i,false,now).status).toBe('blocked');i.portfolio.state='KNOWN';expect(previewRebalance(i,false,new Date(now.getTime()+60001)).reasons[0]).toContain('Refresh');});
 it('requires exact contract selection for a necessary sale',()=>{const i=fixture();i.mandate.representationAllowlist=i.mandate.representationAllowlist!.filter(c=>c!==contract('SPYon'));const r=previewRebalance(i,false,now);expect(r.status).toBe('blocked');expect(r.reasons.join(' ')).toContain('Exact contract is not selected');});
 it('rejects missing buy marks and costs over the saved limit',()=>{const i=fixture();i.marks.items=i.marks.items.filter(m=>!['NVDAon','NVDAB'].map(contract).includes(m.contract));expect(previewRebalance(i,false,now).status).toBe('blocked');const j=fixture();j.quotes.forEach(q=>q.costBps=31);expect(previewRebalance(j,false,now).reasons.join(' ')).toContain('cost exceeds');});
 it('includes holdings outside targets and sells all their raw units',()=>{const i=fixture({SPYon:70,NVDAon:30});i.mandate.allocations=[{underlying:'SPY',weightBps:10000}];const r=previewRebalance(i,false,now);expect(r.status).toBe('feasible');expect(r.drift.find(d=>d.underlying==='NVDA')).toMatchObject({targetWeightBps:0,afterAtomic:'0'});expect(r.legs.find(l=>l.side==='SELL'&&l.underlying==='NVDA')?.quantityAtomic).toBe(atomic(30));});
 it('does not show zero weight as a known percentage for an empty portfolio',()=>{const r=previewRebalance(fixture({}),false,now);expect(r.status).toBe('unchanged');expect(r.drift.every(d=>d.currentWeightBps===null&&d.driftBps===null)).toBe(true);});
 it('keeps large 18-decimal positions exact and never sells more raw units than held',()=>{const i=fixture({SPYon:7000000,NVDAon:3000000});i.marks.items.forEach(m=>m.price=m.contract===contract('SPYon')?'3.123456789123456789':'1.987654321987654321');i.portfolio=assessPortfolio(i.checkpoint,defs,i.marks,[],now.getTime());const r=previewRebalance(i,false,now);expect(r.status).toBe('feasible');for(const l of r.legs.filter(l=>l.side==='SELL'))expect(BigInt(l.quantityAtomic)).toBeLessThanOrEqual(BigInt(i.checkpoint.positions.find(p=>p.contract===l.instrumentId)!.rawAtomic!));expect(BigInt(r.projectedCashAtomic!)).toBeGreaterThanOrEqual(20n*unit);expect(BigInt(r.feeAtomic)).toBeGreaterThan(0n);});
 it('blocks an immutable pending position outside the saved targets',()=>{const i=fixture();i.portfolio.pending=[{symbol:'MSFTon',instrumentId:contract('MSFTon'),issuer:'ondo',underlying:'MSFT',valueAtomic:atomic(1)}];const r=previewRebalance(i,false,now);expect(r.status).toBe('blocked');expect(r.reasons.join(' ')).toContain('outside the saved targets');});
});
