import {afterEach,describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';
import {Ledger,embeddedDatabase} from '@mandate/store';
import {defaultMandate} from '@mandate/core';
import type {InvestmentPolicy,CapitalCheckpoint} from '@mandate/domain';
import {createApp} from '../apps/api/src/app.ts';
import {capitalAccountId} from '../apps/api/src/capital.ts';
import {passportDefinitions} from '../apps/api/src/passports.ts';
const defs=passportDefinitions(),origin='http://127.0.0.1:3110';
const policy:InvestmentPolicy={allocations:defaultMandate.allocations,maxIssuerBps:7000,maxCostBps:30,allowLeveraged:false,representationAllowlist:defs.map(p=>p.contract).sort(),exposureScope:'tracked-holdings-pending-proposed'};
const ledgers:Ledger[]=[],dirs:string[]=[];
afterEach(async()=>{for(const l of ledgers.splice(0))await l.close();for(const d of dirs.splice(0))await fs.rm(d,{recursive:true,force:true});});
function checkpoint(wallet:string):CapitalCheckpoint{return {accountId:capitalAccountId(wallet),wallet:wallet.toLowerCase(),asset:{chainId:56,contract:'0x55d398326f99059ff775485246999027b3197955',decimals:18},balanceAtomic:'100000000000000000000',blockNumber:'123',blockHash:'0x'+'3'.repeat(64),observedAt:new Date().toISOString(),evidenceMode:'observed',positions:defs.map(p=>({contract:p.contract,symbol:p.symbol,decimals:18,rawAtomic:'0',multiplierAtomic:null,adjustedAtomic:null,accountingVersion:'raw-token-v1',state:'OBSERVED'}))};}
async function setup(directory?:string){const ledger=new Ledger(embeddedDatabase(directory));ledgers.push(ledger);await ledger.migrate();const signer=privateKeyToAccount(generatePrivateKey());const cp=checkpoint(signer.address);await ledger.applyCapitalCheckpoint(cp);return {ledger,signer,cp,id:cp.accountId};}
async function signIn(app:ReturnType<typeof createApp>,signer:ReturnType<typeof privateKeyToAccount>){const c=(await app.inject({method:'POST',url:'/v1/wallet/challenge',headers:{origin},payload:{address:signer.address,chainId:56}})).json();const r=await app.inject({method:'POST',url:'/v1/wallet/verify',headers:{origin},payload:{challengeId:c.id,signature:await signer.signMessage({message:c.message})}});return {origin,cookie:String(r.headers['set-cookie']).split(';')[0]};}
describe('saved research mandates and proposals',{timeout:60000},()=>{
 it('versions exact choices, normalizes ordering and rejects concurrent stale editors',async()=>{const {ledger,id}=await setup();const first=await ledger.saveInvestmentMandate(id,policy,0);expect((await ledger.capitalState(id))!.revision).toBe(2);expect((await ledger.saveInvestmentMandate(id,{...policy,representationAllowlist:[...policy.representationAllowlist].reverse()},1)).id).toBe(first.id);const writes=await Promise.allSettled([6000,8000].map(maxIssuerBps=>ledger.saveInvestmentMandate(id,{...policy,maxIssuerBps},1)));expect(writes.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(writes.find(r=>r.status==='rejected')).toMatchObject({reason:{code:'STALE_MANDATE'}});expect(await ledger.investmentMandates(id)).toHaveLength(2);expect((await ledger.capitalState(id))!.revision).toBe(3);});
 it('keeps wallet isolation and rejects untrusted proposal fields and wrong origins',async()=>{const {ledger,signer}=await setup();const app=createApp(process.cwd(),{ledger,marketReader:async()=>({observedAt:new Date().toISOString(),items:[],source:'fixture'})});try{expect((await app.inject({url:'/v1/capital/mandates'})).statusCode).toBe(401);const headers=await signIn(app,signer);expect((await app.inject({method:'POST',url:'/v1/capital/mandates',headers:{...headers,origin:'https://wrong.example'},payload:{policy,expectedRevision:0}})).statusCode).toBe(403);expect((await app.inject({method:'POST',url:'/v1/capital/mandates',headers,payload:{policy:{...policy,representationAllowlist:['0x'+'f'.repeat(40)]},expectedRevision:0}})).statusCode).toBe(400);expect((await app.inject({method:'POST',url:'/v1/capital/mandates',headers,payload:{policy,expectedRevision:0}})).statusCode).toBe(200);expect((await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload:{mandateRevision:1,scenario:'normal',requestId:randomUUID(),balance:'9000'}})).statusCode).toBe(400);const other=await signIn(app,privateKeyToAccount(generatePrivateKey()));expect((await app.inject({url:'/v1/capital/mandates',headers:other})).json().latest).toBeNull();expect((await app.inject({url:'/v1/capital/proposals',headers:other})).json().items).toEqual([]);}finally{await app.close();}});
 it('persists the complete server input snapshot and idempotent outcome without creating holds',async()=>{const {ledger,id,signer}=await setup();const app=createApp(process.cwd(),{ledger,marketReader:async()=>({observedAt:new Date().toISOString(),items:[],source:'fixture'})});try{const headers=await signIn(app,signer);await ledger.saveInvestmentMandate(id,policy,0);const payload={mandateRevision:1,scenario:'normal',requestId:randomUUID()};const first=await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload});expect(first.statusCode).toBe(200);const p=first.json().proposal;expect(p).toMatchObject({researchOnly:true,mandateRevision:1,inputs:{funding:{balanceAtomic:'100000000000000000000',accountRevision:2},checkpoint:{blockNumber:'123'},cashPolicyRevision:0},result:{executable:false}});expect(p.inputs.candidates).toHaveLength(14);expect(p.inputs.passports.items).toHaveLength(14);expect(p.inputs.marks.source).toBe('fixture');expect(p.inputs.cashPolicy).toMatchObject({reserveFloor:'0'});expect(p.inputs.pending).toEqual([]);expect(p.inputs.quotes.every((q:any)=>q.evidenceMode==='synthetic')).toBe(true);expect((await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload})).json().proposal).toEqual(p);expect((await ledger.capitalState(id))!.heldAtomic).toBe('0');expect(await ledger.researchHistory(id)).toHaveLength(1);expect((await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload:{...payload,scenario:'missing'}})).statusCode).toBe(409);await ledger.saveInvestmentMandate(id,{...policy,maxIssuerBps:8000},1);expect((await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload:{...payload,requestId:randomUUID()}})).statusCode).toBe(409);expect((await ledger.researchHistory(id))[0]).toEqual(p);const another=await signIn(app,privateKeyToAccount(generatePrivateKey()));expect((await app.inject({url:'/v1/capital/proposals',headers:another})).json().items).toEqual([]);}finally{await app.close();}});
 it('rejects changed capital or mandate evidence between calculation and persistence',async()=>{const {ledger,id,signer}=await setup();await ledger.saveInvestmentMandate(id,policy,0);const app=createApp(process.cwd(),{ledger,marketReader:async()=>({observedAt:new Date().toISOString(),items:[],source:'fixture'})});try{const headers=await signIn(app,signer);const p=(await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload:{mandateRevision:1,scenario:'normal',requestId:randomUUID()}})).json().proposal;await ledger.saveCapitalPolicy(id,{reserveFloor:'1',operatingBudget:'0',obligations:[]},2);await expect(ledger.saveResearchProposal({...p,id:randomUUID(),requestId:randomUUID()})).rejects.toThrow('STALE_PROPOSAL_INPUTS');await ledger.saveInvestmentMandate(id,{...policy,maxCostBps:20},1);await expect(ledger.saveResearchProposal({...p,id:randomUUID(),requestId:randomUUID()})).rejects.toThrow('STALE_MANDATE');expect(await ledger.researchHistory(id)).toHaveLength(1);}finally{await app.close();}});
 it('records infeasible explanations but blocks new proposals on unknown or expired capital',async()=>{const {ledger,id,signer,cp}=await setup();await ledger.saveInvestmentMandate(id,{...policy,representationAllowlist:[]},0);const app=createApp(process.cwd(),{ledger,marketReader:async()=>({observedAt:new Date().toISOString(),items:[],source:'fixture'})});try{const headers=await signIn(app,signer),payload={mandateRevision:1,scenario:'normal',requestId:randomUUID()};const p=(await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload})).json().proposal;expect(p.result.status).toBe('infeasible');expect(p.result.excluded.some((e:any)=>e.reason.includes('not been selected'))).toBe(true);await ledger.invalidateCapital(id);expect((await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload:{...payload,requestId:randomUUID()}})).statusCode).toBe(409);expect((await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload})).json().proposal.id).toBe(p.id);await ledger.applyCapitalCheckpoint({...cp,blockNumber:'124',blockHash:'0x'+'4'.repeat(64),observedAt:new Date(Date.now()-61000).toISOString()});expect((await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload:{...payload,requestId:randomUUID()}})).statusCode).toBe(409);}finally{await app.close();}});
 it('retains mandate and immutable proposal evidence across restart and additive migration',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'mandate-research-'));dirs.push(directory);const {ledger,id,signer}=await setup(directory);await ledger.saveInvestmentMandate(id,policy,0);const app=createApp(process.cwd(),{ledger,marketReader:async()=>({observedAt:new Date().toISOString(),items:[],source:'fixture'})});const headers=await signIn(app,signer);const p=(await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload:{mandateRevision:1,scenario:'normal',requestId:randomUUID()}})).json().proposal;await app.close();ledgers.splice(ledgers.indexOf(ledger),1);await ledger.close();const reopened=new Ledger(embeddedDatabase(directory));ledgers.push(reopened);await reopened.migrate();await reopened.migrate();expect((await reopened.investmentMandates(id))[0].policy).toEqual(policy);expect((await reopened.researchHistory(id))[0]).toEqual(p);expect((await reopened.capitalState(id))!.heldAtomic).toBe('0');});
});
