import {afterEach,describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';
import {Ledger,embeddedDatabase} from '@mandate/store';
import {compareResearchProposals,defaultMandate} from '@mandate/core';
import type {ResearchProposal,CapitalCheckpoint,InvestmentPolicy,PlanRevisionRecord} from '@mandate/domain';
import {createApp} from '../apps/api/src/app.ts';
import {passportDefinitions} from '../apps/api/src/passports.ts';
import {capitalAccountId} from '../apps/api/src/capital.ts';
const defs=passportDefinitions(),origin='http://127.0.0.1:3110',atomic=(n:number)=>(BigInt(n)*10n**18n).toString();
const policy:InvestmentPolicy={allocations:defaultMandate.allocations,maxIssuerBps:7000,maxCostBps:30,allowLeveraged:false,representationAllowlist:defs.map(p=>p.contract).sort(),exposureScope:'tracked-holdings-pending-proposed'};
const ledgers:Ledger[]=[],apps:ReturnType<typeof createApp>[]=[];
afterEach(async()=>{for(const a of apps.splice(0))await a.close();for(const l of ledgers.splice(0))await l.close();});
async function signIn(app:ReturnType<typeof createApp>,signer=privateKeyToAccount(generatePrivateKey())){const c=(await app.inject({method:'POST',url:'/v1/wallet/challenge',headers:{origin},payload:{address:signer.address,chainId:56}})).json();const v=await app.inject({method:'POST',url:'/v1/wallet/verify',headers:{origin},payload:{challengeId:c.id,signature:await signer.signMessage({message:c.message})}});return {cookie:String(v.headers['set-cookie']).split(';')[0],origin};}
async function setup(){const ledger=new Ledger(embeddedDatabase());ledgers.push(ledger);await ledger.migrate();const signer=privateKeyToAccount(generatePrivateKey()),id=capitalAccountId(signer.address);const state={block:100,cash:100,reads:0,marks:0,fail:false};
 const checkpoint=(wallet:string):CapitalCheckpoint=>({accountId:capitalAccountId(wallet),wallet:wallet.toLowerCase(),asset:{chainId:56,contract:'0x55d398326f99059ff775485246999027b3197955',decimals:18},balanceAtomic:atomic(state.cash),blockNumber:String(state.block),blockHash:'0x'+BigInt(state.block).toString(16).padStart(64,'0'),observedAt:new Date().toISOString(),evidenceMode:'observed',positions:defs.map(p=>({contract:p.contract,symbol:p.symbol,decimals:18,rawAtomic:'0',multiplierAtomic:null,adjustedAtomic:null,accountingVersion:'raw-token-v1',state:'OBSERVED'}))});
 await ledger.applyCapitalCheckpoint(checkpoint(signer.address));await ledger.saveInvestmentMandate(id,policy,0);
 const app=createApp(process.cwd(),{ledger,capitalReader:async wallet=>{state.reads++;if(state.fail)throw new Error('RPC failed');state.block++;return checkpoint(wallet);},marketReader:async()=>{state.marks++;return {observedAt:new Date().toISOString(),source:'test',items:[]};}});apps.push(app);const headers=await signIn(app,signer);
 const initial=await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload:{mandateRevision:1,scenario:'normal',requestId:randomUUID()}});expect(initial.statusCode).toBe(200);const parent:ResearchProposal=initial.json().proposal;
 const body=()=>({proposalId:parent.id,mandateRevision:1,scenario:'normal' as const,requestId:randomUUID()});return {ledger,app,headers,parent,id,state,body};
}
describe('proposal revalidation',{timeout:60000},()=>{
 it('ignores clocks and block references while comparing financial evidence',async()=>{const {parent}=await setup(),next=structuredClone(parent);next.id=randomUUID();next.inputs.checkpoint.blockNumber='101';next.inputs.checkpoint.blockHash='0x'+'e'.repeat(64);next.inputs.funding.accountRevision++;next.inputs.portfolio.checkedAt=new Date(Date.now()+1000).toISOString();next.result.decisionId='a-different-input-revision';expect(compareResearchProposals(parent,next)).toMatchObject({state:'UNCHANGED',changes:[]});next.inputs.funding.balanceAtomic=atomic(90);next.inputs.mandate.maxIssuerBps=6000;next.inputs.checkpoint.positions[0].rawAtomic=atomic(2);next.inputs.quotes[0].available=false;next.result.status=next.result.status==='feasible'?'infeasible':'feasible';const report=compareResearchProposals(parent,next);expect(new Set(report.changes.map(c=>c.category))).toEqual(new Set(['cash','mandate','holdings','quotes','allocation']));expect(report.changes.find(c=>c.label==='Observed cash · USDT')).toMatchObject({before:'100',after:'90'});});
 it('keeps missing historical source inputs explicit instead of treating them as empty evidence',async()=>{const {parent}=await setup(),old=structuredClone(parent);delete (old.inputs as any).pending;delete (old.inputs as any).marks;delete (old.inputs as any).passports;const report=compareResearchProposals(old,parent);expect(report.changes.find(c=>c.category==='pending')).toMatchObject({before:'null',after:'[]'});expect(report.changes.find(c=>c.label==='Market observation source')).toMatchObject({before:'Unknown',after:'test'});expect(report.changes.some(c=>c.category==='eligibility')).toBe(true);});
 it('refreshes chain and market observations, links a new record and replays the same request once',async()=>{const {app,headers,parent,state,ledger,id,body}=await setup();const payload=body();const r=await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers,payload});expect(r.statusCode).toBe(200);const p=r.json().proposal;expect(p.id).not.toBe(parent.id);expect(p.revalidation).toMatchObject({parentProposalId:parent.id,state:'UNCHANGED'});expect(state.reads).toBe(1);expect(state.marks).toBe(2);expect((await ledger.researchProposalById(id,parent.id))).toEqual(parent);expect((await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers,payload})).json().proposal).toEqual(p);expect(state.reads).toBe(1);expect((await ledger.researchHistory(id))).toHaveLength(2);expect((await app.inject({method:'POST',url:'/v1/capital/proposals',headers,payload:{mandateRevision:1,scenario:'normal',requestId:payload.requestId}})).statusCode).toBe(409);});
 it('uses the latest saved rules and reports a changed budget without modifying the original',async()=>{const {app,headers,parent,state,ledger,id,body}=await setup();await ledger.saveInvestmentMandate(id,{...policy,maxIssuerBps:6000},1);state.cash=80;expect((await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers,payload:body()})).statusCode).toBe(409);expect(state.reads).toBe(0);const p=(await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers,payload:{...body(),mandateRevision:2}})).json().proposal;expect(p.revalidation.state).toBe('CHANGED');expect(p.revalidation.changes.find((c:any)=>c.label==='Research budget · USDT')).toMatchObject({before:'100',after:'80'});expect(p.mandateRevision).toBe(2);expect(await ledger.researchProposalById(id,parent.id)).toEqual(parent);});
 it('rejects foreign parents, absent sessions, wrong origins and injected balances before refreshing',async()=>{const {app,headers,parent,state,body}=await setup();expect((await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',payload:body()})).statusCode).toBe(401);const other=await signIn(app);expect((await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers:other,payload:body()})).statusCode).toBe(404);expect((await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers:{...headers,origin:'https://wrong.example'},payload:body()})).statusCode).toBe(403);expect((await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers,payload:{...body(),balance:999}})).statusCode).toBe(400);expect(state.reads).toBe(0);expect(parent.revalidation).toBeUndefined();});
 it('retains ambiguous held exposure and records infeasibility without releasing or duplicating it',async()=>{const {app,headers,parent,ledger,id,body}=await setup();const account=(await ledger.capitalState(id))!;const spy=defs.find(p=>p.symbol==='SPYon')!;const record:PlanRevisionRecord={schemaVersion:'1.0.0',id:randomUUID(),accountId:id,revision:1,accountRevision:account.revision,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+60000).toISOString(),decisionId:'hold-test',inputHash:'a'.repeat(64),maximumDebit:{asset:account.checkpoint.asset,atomic:atomic(20)},evidenceMode:'live',exposureModel:{currency:'USD-nominal-USDT-parity',legs:[{instrumentId:spy.contract,issuer:'ondo',underlying:'SPY',valueAtomic:atomic(20)}]}};await ledger.savePlan(record);const hold=await ledger.reserve({accountId:id,planRevisionId:record.id,idempotencyKey:'held',amountAtomic:atomic(20)});const ready=(await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers,payload:body()})).json().proposal;await ledger.beginSubmission(hold.id,randomUUID());await expect(ledger.saveResearchProposal({...ready,id:randomUUID(),requestId:randomUUID()})).rejects.toThrow('STALE_PROPOSAL_INPUTS');const p=(await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers,payload:body()})).json().proposal;expect(p.result.status).toBe('infeasible');expect(p.inputs.portfolio.state).toBe('UNKNOWN');expect(p.inputs.pending[0].submissionStarted).toBe(true);expect((await ledger.capitalState(id))!.heldAtomic).toBe(atomic(20));expect(p.revalidation.changes.some((c:any)=>c.category==='pending')).toBe(true);});
 it('fails closed on a refresh failure and verifies comparisons before persisting',async()=>{const {app,headers,parent,ledger,id,state,body}=await setup();state.fail=true;expect((await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers,payload:body()})).statusCode).toBe(503);expect((await ledger.capitalState(id))!.health).toBe('UNKNOWN');expect(await ledger.researchHistory(id)).toHaveLength(1);expect(await ledger.researchProposalById(id,parent.id)).toEqual(parent);state.fail=false;const p=(await app.inject({method:'POST',url:'/v1/capital/proposals/revalidate',headers,payload:body()})).json().proposal;await expect(ledger.saveResearchProposal({...p,id:randomUUID(),requestId:randomUUID(),revalidation:{...p.revalidation,state:'CHANGED',changes:[]}})).rejects.toThrow('INVALID_PROPOSAL_COMPARISON');});
});
