'use client';
import {useEffect,useRef,useState} from 'react';
import {listInjectedWalletProviders,waitForInjectedWalletProviders,type Eip1193Provider,type WalletProviderChoice} from '../wallet-providers';
import './trade.css';

type Session={address:string;chainId:56;expiresAt:number};
type Direction='BUY'|'SELL';
type Preflight={state:string;checkedAt:string;blockNumber:string;direction:Direction;amountInAtomic:string;quotedOutAtomic:string;minimumOutAtomic:string;wallet:{balanceAtomic:string;allowanceAtomic:string;bnbAtomic:string};approvalPreview?:{simulation:string;gas:string;gasBudgetAtomic:string|null;reason:string};gates:{poolIdentity:string;referenceCost:string;funds:string;spendingPermission:string;simulation:string;gas:string};reference:{price:string|null;deviationBps:string|null;reason:string};note:string};
type Attempt={id:string;kind:'approval'|'swap';direction:Direction;state:string;amountInAtomic:string;minimumOutAtomic:string;expiresAt:string;transactionHash:string|null;settlement:null|{status:string;confirmations:string;blockNumber:string}};
const endpoint='/api/v1/routes/SPYon';
function amount(raw:string,asset:'USDT'|'SPYon'){const [whole,fraction='']=raw.split('.');if(!/^(0|[1-9]\d*)$/.test(whole)||!/^[0-9]{0,18}$/.test(fraction))throw new Error(`Enter a ${asset} amount with at most 18 decimal places.`);const atomic=BigInt(whole)*10n**18n+BigInt((fraction+'0'.repeat(18)).slice(0,18));const cap=asset==='USDT'?10n*10n**18n:2n*10n**16n;if(atomic<=0n||atomic>cap)throw new Error(`Use an amount above zero and at most ${asset==='USDT'?'10 USDT':'0.02 SPYon'}.`);return atomic.toString();}
function display(raw:string){const value=BigInt(raw),whole=value/10n**18n,part=(value%10n**18n).toString().padStart(18,'0').slice(0,8).replace(/0+$/,'');return whole.toString()+(part?'.'+part:'');}
function displayPrice(raw:string|null){if(raw===null)return 'unavailable';const value=Number(raw);return Number.isFinite(value)&&value>0?'≈ $'+value.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'unavailable';}
async function ensureBsc(wallet:Eip1193Provider){const read=async()=>{const chain=String(await wallet.request({method:'eth_chainId'}));return Number.parseInt(chain,chain.startsWith('0x')?16:10);};if(await read()===56)return;try{await wallet.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x38'}]});}catch{throw new Error('Select BNB Smart Chain in your wallet, then tap Connect wallet again.');}if(await read()!==56)throw new Error('The wallet is still on another network. Select BNB Smart Chain, then reconnect.');}
async function api(path:string,body?:unknown){const response=await fetch(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error==='PROTECTED_CASH_OR_POLICY_BLOCKS_TRADE'?'Your saved cash rules or current wallet balance leave less than this amount available. Review your cash rules in Plan and exit, refresh capital, then check the route again.':value.message||value.error||'Request failed');return value;}
function status(state:string){return state==='CHECKED'||state==='PASSED'?'ready':state==='BLOCKED'||state==='FAILED'?'blocked':'waiting';}

export default function DirectTradePage(){
 const [session,setSession]=useState<Session|null>(null),[choices,setChoices]=useState<WalletProviderChoice[]>([]),[approvalEnabled,setApprovalEnabled]=useState(false),[swapEnabled,setSwapEnabled]=useState(false),[fullRouteEnabled,setFullRouteEnabled]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[walletMessage,setWalletMessage]=useState(''),[direction,setDirection]=useState<Direction>('BUY'),[buyAmount,setBuyAmount]=useState('1'),[sellAmount,setSellAmount]=useState('0.01'),[preflight,setPreflight]=useState<Preflight|null>(null),[attempts,setAttempts]=useState<Attempt[]>([]),[prepared,setPrepared]=useState<Attempt|null>(null),[recoveryHash,setRecoveryHash]=useState('');
 const provider=useRef<Eip1193Provider|null>(null);
 async function refresh(){const {items,executionEnabled,approvalEnabled,fullRouteEnabled}=await api(endpoint+'/attempts');setAttempts(items);setSwapEnabled(executionEnabled===true);setApprovalEnabled(approvalEnabled===true);setFullRouteEnabled(fullRouteEnabled===true);}
 useEffect(()=>{let live=true;(async()=>{try{const current=await api('/api/v1/wallet/session');if(!live||!current.session)return;const found=listInjectedWalletProviders(window);for(const choice of found){const accounts=await choice.provider.request({method:'eth_accounts'}),chain=String(await choice.provider.request({method:'eth_chainId'}));if(Array.isArray(accounts)&&String(accounts[0]).toLowerCase()===current.session.address.toLowerCase()&&Number.parseInt(chain,16)===56){provider.current=choice.provider;setSession(current.session);const next=await api(endpoint+'/attempts');if(live){setAttempts(next.items);setSwapEnabled(next.executionEnabled===true);setApprovalEnabled(next.approvalEnabled===true);setFullRouteEnabled(next.fullRouteEnabled===true);}return;}}}catch{}})();return()=>{live=false;};},[]);
 async function connect(choice?:WalletProviderChoice){setBusy(true);setMessage('');try{let selected=choice;if(!selected){const found=await waitForInjectedWalletProviders(window);if(!found.length)throw new Error('Open this page in a wallet DApp browser or a desktop browser with an EVM wallet.');if(found.length>1){setChoices(found);return;}selected=found[0];}setChoices([]);const wallet=selected.provider,accounts=await wallet.request({method:'eth_requestAccounts'});if(!Array.isArray(accounts)||typeof accounts[0]!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(accounts[0]))throw new Error('No wallet account was returned.');const address=accounts[0];await ensureBsc(wallet);const challenge=await api('/api/v1/wallet/challenge',{address,chainId:56});const hex='0x'+Array.from(new TextEncoder().encode(challenge.message),byte=>byte.toString(16).padStart(2,'0')).join('');const signature=await wallet.request({method:'personal_sign',params:[hex,address]});const verified=await api('/api/v1/wallet/verify',{challengeId:challenge.id,signature});provider.current=wallet;setSession(verified);await refresh();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 async function verifiedWallet(){const wallet=provider.current;if(!wallet||!session)throw new Error('Connect the signing wallet again.');const accounts=await wallet.request({method:'eth_accounts'}),chain=String(await wallet.request({method:'eth_chainId'}));if(!Array.isArray(accounts)||String(accounts[0]).toLowerCase()!==session.address.toLowerCase()||Number.parseInt(chain,16)!==56)throw new Error('Wallet account or network changed. Reconnect before continuing.');return wallet;}
 async function check(){if(!session)return;setBusy(true);setMessage('');setPreflight(null);try{const body=direction==='BUY'?{direction,buyAmountAtomic:amount(buyAmount,'USDT')}:{direction,sellAmountAtomic:amount(sellAmount,'SPYon')};setPreflight(await api(endpoint+'/preflight',body));await refresh();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 async function prepare(kind:'approval'|'swap'){setBusy(true);setMessage('');setWalletMessage('');try{await verifiedWallet();const body=direction==='BUY'?{direction,buyAmountAtomic:amount(buyAmount,'USDT')}:{direction,sellAmountAtomic:amount(sellAmount,'SPYon')};const result=await api(endpoint+(kind==='approval'?'/approval/prepare':'/prepare'),body);setPrepared(result.attempt);await refresh();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 async function send(){if(!prepared)return;setBusy(true);setMessage('');setWalletMessage('Checking this request before opening Binance Wallet…');let begun=false,returnedHash:string|null=null;try{const wallet=await verifiedWallet();const begin=await api(endpoint+'/begin',{attemptId:prepared.id});begun=true;setPrepared(null);setWalletMessage('');setMessage('Waiting for your wallet to review this request. Do not send it again if the result is unclear.');setAttempts(current=>current.map(item=>item.id===prepared.id?{...item,state:'submission_unknown'}:item));const hash=await wallet.request({method:'eth_sendTransaction',params:[begin.transaction]});if(typeof hash!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(hash))throw new Error('The wallet did not return a transaction hash.');returnedHash=hash;await api(endpoint+'/hash',{attemptId:prepared.id,transactionHash:hash});await refresh();setMessage('Wallet returned a transaction hash. Wait for 12 confirmations, then check settlement.');}catch(error){if(returnedHash)setRecoveryHash(returnedHash);const reason=(error as Error).message==='DIRECT_ATTEMPT_EXPIRED'?'This review expired before the wallet request. Discard it, then check the route again.':(error as Error).message;if(begun)setMessage('The wallet result is uncertain. Do not send again. '+(returnedHash?'The returned hash is filled in below; attach it to this attempt. ':'If the wallet shows a transaction hash, attach it below. ')+reason);else setWalletMessage(reason);await refresh().catch(()=>{});}finally{setBusy(false);}}
 async function abandon(id:string){setBusy(true);try{await api(endpoint+'/abandon',{attemptId:id});setPrepared(null);await refresh();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 async function attach(id:string){setBusy(true);setMessage('');try{if(!/^0x[0-9a-fA-F]{64}$/.test(recoveryHash))throw new Error('Enter the 66-character transaction hash shown by the wallet.');await api(endpoint+'/hash',{attemptId:id,transactionHash:recoveryHash});setRecoveryHash('');await refresh();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 async function reconcile(id:string){setBusy(true);setMessage('');try{await api(endpoint+'/reconcile',{attemptId:id});await refresh();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 const active=attempts.find(item=>['prepared','submission_unknown','submitted'].includes(item.state));
 const trialAmount=preflight?.direction==='BUY'&&BigInt(preflight.amountInAtomic)<=10n**18n;
 const canSwap=preflight?.gates.poolIdentity==='CHECKED'&&preflight.gates.referenceCost==='CHECKED'&&preflight.gates.funds==='CHECKED'&&preflight.gates.spendingPermission==='CHECKED'&&preflight.gates.simulation==='PASSED'&&preflight.gates.gas==='CHECKED'&&(fullRouteEnabled||trialAmount);
 const canApprove=preflight?.gates.poolIdentity==='CHECKED'&&preflight.gates.referenceCost==='CHECKED'&&preflight.gates.funds==='CHECKED'&&preflight.gates.spendingPermission==='BLOCKED'&&preflight.approvalPreview?.simulation==='PASSED'&&preflight.approvalPreview.gas==='CHECKED'&&(fullRouteEnabled||trialAmount);
 return <div className="direct-page"><header><a href="/">Mandate</a><a href="/execution-review">Token research ↗</a></header><main><p className="direct-kicker">SPYon · BNB SMART CHAIN</p><h1>Review one direct route.</h1><p className="direct-lede">A capped Pancake V3 pilot for SPYon and USDT. Each approval or swap needs a separate wallet confirmation. A wallet request is never sent automatically.</p>
  <div className="direct-grid"><section className="direct-card"><div className="direct-card-heading"><span>01 / WALLET</span><h2>{session?'Connected account':'Connect your wallet'}</h2></div>{session?<p className="direct-address">{session.address}</p>:<><p>Connect a wallet for a current quote and balance check. If it is on another network, we will ask it to switch to BNB Smart Chain.</p><button disabled={busy} onClick={()=>void connect()}>Connect wallet</button>{choices.length>0&&<div className="direct-choices">{choices.map(choice=><button key={choice.id} disabled={busy} onClick={()=>void connect(choice)}>{choice.name}</button>)}</div>}</>}{session&&<p className="direct-small">Signing in reads your address. It does not approve a token or transaction.</p>}</section>
  <section className="direct-card"><div className="direct-card-heading"><span>02 / ROUTE</span><h2>Check current conditions</h2></div><div className="direct-toggle"><button className={direction==='BUY'?'selected':''} onClick={()=>{setDirection('BUY');setPreflight(null);}} disabled={busy||!!prepared}>Buy SPYon</button><button className={direction==='SELL'?'selected':''} onClick={()=>{setDirection('SELL');setPreflight(null);}} disabled={busy||!!prepared}>Sell SPYon</button></div>{direction==='BUY'?<label>USDT to check<input inputMode="decimal" value={buyAmount} disabled={busy||!!prepared} onChange={event=>{setBuyAmount(event.target.value);setPreflight(null);}}/><small>{swapEnabled&&!fullRouteEnabled?'This trial can buy up to 1 USDT. A quote does not spend funds.':'Choose any positive amount up to 10 USDT. A quote does not spend funds.'}</small></label>:<label>SPYon to sell<input inputMode="decimal" value={sellAmount} disabled={busy||!!prepared} onChange={event=>{setSellAmount(event.target.value);setPreflight(null);}}/></label>}<button disabled={!session||busy||!!prepared} onClick={()=>void check()}>{busy?'Working…':'Check route and wallet'}</button></section></div>
  {message&&<p className="direct-message" role="status">{message}</p>}
  {preflight&&<section className="direct-card direct-review"><div className="direct-card-heading"><span>03 / CURRENT CHECK</span><h2>Route at block #{preflight.blockNumber}</h2></div><p>{display(preflight.amountInAtomic)} {preflight.direction==='BUY'?'USDT':'SPYon'} → estimated {display(preflight.quotedOutAtomic)} {preflight.direction==='BUY'?'SPYon':'USDT'}</p><p>Minimum output in a possible swap: {display(preflight.minimumOutAtomic)} {preflight.direction==='BUY'?'SPYon':'USDT'}. Reference price: {displayPrice(preflight.reference.price)}.</p><div className="direct-wallet"><h3>Wallet observed at this block</h3><div><span>{preflight.direction==='BUY'?'USDT':'SPYon'} balance<strong>{display(preflight.wallet.balanceAtomic)}</strong></span><span>Approved for Pancake V3<strong>{display(preflight.wallet.allowanceAtomic)}</strong></span><span>BNB for network fees<strong>{display(preflight.wallet.bnbAtomic)}</strong></span></div></div><div className="direct-gates">{Object.entries(preflight.gates).map(([name,state])=><div key={name}><span>{name.replace(/([A-Z])/g,' $1')}</span><strong className={status(state)}>{state.toLowerCase().replace('_',' ')}</strong></div>)}</div>{preflight.approvalPreview&&preflight.gates.spendingPermission==='BLOCKED'&&<div className="direct-approval"><strong>Exact-amount approval check · {preflight.approvalPreview.simulation.toLowerCase().replace('_',' ')}</strong><p>{preflight.approvalPreview.reason}{preflight.approvalPreview.gasBudgetAtomic!==null?` Indicative approval gas budget: ${display(preflight.approvalPreview.gasBudgetAtomic)} BNB.`:''} No approval has been requested.</p></div>}<p className="direct-small">Checked at {new Date(preflight.checkedAt).toLocaleTimeString()}. A new quote and simulation run before preparing a wallet request.</p>{(approvalEnabled||swapEnabled)&&!active&&<div className="direct-actions">{approvalEnabled&&canApprove&&<button disabled={busy} onClick={()=>void prepare('approval')}>Prepare exact-amount approval</button>}{swapEnabled&&canSwap&&<button disabled={busy} onClick={()=>void prepare('swap')}>Prepare this swap</button>}</div>}{swapEnabled&&!fullRouteEnabled?<p className="direct-disabled">{preflight.gates.spendingPermission==='CHECKED'?'Your wallet already approved enough USDT for this amount. No second approval is needed. Tap Prepare this swap to review a separate swap request.':'1 USDT buy-only swap trial for this wallet. Check the route and wallet again to see what is needed.'} A fresh quote and simulation run before any wallet request.</p>:approvalEnabled&&!swapEnabled?<p className="direct-disabled">Approval-only trial: this wallet may request an exact approval for at most 1 USDT after saved cash rules leave that amount available. <a href="/portfolio-exit">Review cash rules</a>. Swaps remain disabled.</p>:!approvalEnabled&&!swapEnabled?<p className="direct-disabled">Live wallet requests are disabled in this deployment. This check is research only.</p>:null}</section>}
  {prepared&&<section className="direct-card direct-review"><div className="direct-card-heading"><span>04 / WALLET CONFIRMATION</span><h2>{prepared.kind==='approval'?'Exact spending approval':'One capped swap'}</h2></div><p>{prepared.kind==='approval'?'Allow Pancake V3 to spend exactly ': 'Spend '}{display(prepared.amountInAtomic)} {prepared.direction==='BUY'?'USDT':'SPYon'}{prepared.kind==='swap'?` for at least ${display(prepared.minimumOutAtomic)} ${prepared.direction==='BUY'?'SPYon':'USDT'}.`:'.'}</p><p className="direct-small">Expires {new Date(prepared.expiresAt).toLocaleTimeString()}. The wallet will show the final transaction. Check it before confirming.</p>{walletMessage&&<p className="direct-message" role="status">{walletMessage}</p>}<div className="direct-actions"><button disabled={busy} onClick={()=>void send()}>{busy?'Opening wallet…':'Review in wallet'}</button><button className="direct-secondary" disabled={busy} onClick={()=>void abandon(prepared.id)}>Discard before wallet request</button></div></section>}
  <section className="direct-card direct-review"><div className="direct-card-heading"><span>ATTEMPT RECORD</span><h2>What happened after the wallet prompt</h2></div>{!session?<p>Connect to view your records.</p>:attempts.length===0?<p>No approval or swap attempts recorded for this wallet.</p>:attempts.map(item=><div className="direct-attempt" key={item.id}><div><strong>{item.direction} · {item.kind}</strong><span>{item.state.replace('_',' ')}{item.transactionHash?' · '+item.transactionHash.slice(0,12)+'…':''}</span></div>{item.state==='prepared'&&item.id!==prepared?.id&&<button className="direct-secondary" disabled={busy} onClick={()=>void abandon(item.id)}>Discard prepared request</button>}{item.state==='submission_unknown'&&<div className="direct-recover"><p>The result is unknown. Do not repeat the wallet request. If your wallet shows a hash, attach it here.</p><input aria-label="Transaction hash" placeholder="0x…" value={recoveryHash} onChange={event=>setRecoveryHash(event.target.value)}/><button disabled={busy} onClick={()=>void attach(item.id)}>Attach hash</button></div>}{item.state==='submitted'&&<button disabled={busy} onClick={()=>void reconcile(item.id)}>Check 12 confirmations</button>}{item.settlement&&<small>Block #{item.settlement.blockNumber} · {item.settlement.confirmations} confirmations</small>}</div>)}<p className="direct-small">Unknown attempts stay blocked across reloads. A successful on-chain receipt and token flow must be verified before another request can start.</p></section>
 </main></div>;
}
