import {NextRequest} from 'next/server';
async function proxy(request:NextRequest,context:{params:Promise<{path:string[]}>}){
 const {path}=await context.params;const route='/'+path.join('/');
 const passportRoutes=['GET /v1/instruments/passports','POST /v1/instruments/eligibility','GET /v1/capital','GET /v1/capital/history','POST /v1/capital/refresh','POST /v1/capital/policy','POST /v1/capital/preview','GET /v1/capital/mandates','POST /v1/capital/mandates','GET /v1/capital/proposals','POST /v1/capital/proposals','POST /v1/capital/proposals/revalidate','GET /v1/capital/rebalances','POST /v1/capital/rebalances','GET /v1/capital/cash-raising','POST /v1/capital/cash-raising','GET /v1/capital/inflows','POST /v1/capital/inflows/check','POST /v1/capital/inflows/propose','GET /v1/capital/recurring','POST /v1/capital/recurring','POST /v1/capital/recurring/pause','POST /v1/capital/recurring/resume','POST /v1/capital/recurring/revoke'];
 const permitted=['GET /v1/workspace','GET /v1/instruments','GET /v1/regime','GET /v1/cost-review','GET /v1/health','POST /v1/plans/preview','POST /v1/withdrawals/preview','GET /v1/wallet/session','POST /v1/wallet/challenge','POST /v1/wallet/verify','DELETE /v1/wallet/session','POST /v1/routes/AAOIB/research','POST /v1/routes/SPYon/preflight','POST /v1/routes/SPYon/mandate-review','GET /v1/routes/SPYon/attempts','POST /v1/routes/SPYon/plan/prepare','POST /v1/routes/SPYon/prepare','POST /v1/routes/SPYon/approval/prepare','POST /v1/routes/SPYon/begin','POST /v1/routes/SPYon/abandon','POST /v1/routes/SPYon/hash','POST /v1/routes/SPYon/reconcile','POST /v1/routes/SPYon/recover-expired'];
 if(![...permitted,...passportRoutes].includes(request.method+' '+route))return Response.json({error:'NOT_FOUND'},{status:404});
  try{const headers=new Headers({'Content-Type':'application/json'});const cookie=request.headers.get('cookie');if(cookie)headers.set('Cookie',cookie);const origin=request.headers.get('origin');if(origin)headers.set('Origin',origin);const timeout=route==='/v1/routes/SPYon/recover-expired'?120000:route.startsWith('/v1/routes/SPYon/')?60000:route==='/v1/regime'?30000:route==='/v1/capital/inflows/propose'||route==='/v1/capital/refresh'||route==='/v1/capital/proposals/revalidate'?60000:route==='/v1/capital/inflows/check'?35000:10000;const response=await fetch('http://127.0.0.1:'+(process.env.MANDATE_API_PORT||'4110')+route+request.nextUrl.search,{method:request.method,headers,body:['POST','PUT','PATCH'].includes(request.method)?await request.text():undefined,cache:'no-store',signal:AbortSignal.timeout(timeout)});const outHeaders=new Headers({'Content-Type':'application/json','Cache-Control':'no-store'});const setCookie=response.headers.get('set-cookie');if(setCookie)outHeaders.set('Set-Cookie',setCookie);return new Response(await response.text(),{status:response.status,headers:outHeaders});}
 catch{return Response.json({error:'API_UNAVAILABLE',message:'Start the workspace API, then retry.'},{status:503});}
}
export {proxy as GET,proxy as POST,proxy as DELETE};
