'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';

type CatalogItem={symbol:string;underlying:string;issuer:string;tokenPrice:string|null;reportedStatus:string;marketDataState:'OBSERVED'|'UNKNOWN';lastKnownAgeSeconds:number|null};
type Catalogue={stale:boolean;observedAt:string|null;completeIssuers:boolean;items:CatalogItem[]};
type Passport={symbol:string;underlying:string;issuer:string;category:string;leveraged:boolean;contract:string;profile:{state:string}};
type Filter='All'|'Stocks'|'ETFs';
const money=(value:string)=>{const number=Number(value);return Number.isFinite(number)?'$'+new Intl.NumberFormat('en-US',{maximumFractionDigits:2,minimumFractionDigits:2}).format(number):'Unknown';};
const time=(value:string|null)=>value?new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'No recorded frame';

export default function MarketClient(){
 const [catalogue,setCatalogue]=useState<Catalogue|null>(null),[passports,setPassports]=useState<Passport[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[filter,setFilter]=useState<Filter>('All'),[issuer,setIssuer]=useState('All'),[query,setQuery]=useState('');
 useEffect(()=>{const controller=new AbortController();(async()=>{try{const [recorded,sourced]=await Promise.all([fetch('/api/v1/instruments',{signal:controller.signal,cache:'no-store'}),fetch('/api/v1/instruments/passports',{signal:controller.signal,cache:'no-store'})]);if(!recorded.ok||!sourced.ok)throw new Error('Token observations are unavailable. Try again shortly.');const [r,p]=await Promise.all([recorded.json(),sourced.json()]);setCatalogue(r);setPassports(p.items??[]);}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[]);
 const bySymbol=useMemo(()=>new Map(catalogue?.items.map(item=>[item.symbol.toLowerCase(),item])??[]),[catalogue]);
 const shown=passports.filter(p=>(filter==='All'||(filter==='Stocks'?p.category==='Stock':p.category!=='Stock'))&&(issuer==='All'||p.issuer===issuer)&&`${p.symbol} ${p.underlying} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
 return <>
  <section className="market-status" aria-label="Market data status"><div><span className="product-state">SOURCED TOKEN IDENTITIES</span><strong>{passports.length||'—'} tracked token versions</strong><small>Ondo and bStocks · identity does not establish trade eligibility</small></div><div><span className={`product-state ${catalogue?.stale?'stale':'unknown'}`}>{catalogue?catalogue.stale?'STALE':'RECORDED':'UNKNOWN'}</span><strong>{time(catalogue?.observedAt??null)}</strong><small>Collector frame, not an executable route</small></div></section>
  <div className="market-controls"><label>Search tokens<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Symbol or underlying"/></label><div role="group" aria-label="Asset type">{(['All','Stocks','ETFs'] as Filter[]).map(choice=><button type="button" key={choice} aria-pressed={filter===choice} onClick={()=>setFilter(choice)}>{choice}</button>)}</div><label>Issuer<select value={issuer} onChange={event=>setIssuer(event.target.value)}><option>All</option><option value="ondo">Ondo</option><option value="bstock">bStocks</option></select></label></div>
  {catalogue?.stale&&<p className="market-warning" role="status">Recorded market data is stale. Token prices are hidden until the collector records a fresh frame. Token identities below remain research facts.</p>}
  {loading?<div className="product-empty" role="status">Loading sourced token identities and recorded observations…</div>:error?<div className="product-empty" role="alert">{error}</div>:shown.length===0?<div className="product-empty">No tracked tokens match these filters.</div>:<div className="market-list" aria-label="Tracked tokenized stocks">{shown.map(p=>{const recorded=bySymbol.get(p.symbol.toLowerCase());const hasPrice=!catalogue?.stale&&recorded?.marketDataState==='OBSERVED'&&recorded.tokenPrice!==null;return <article className="market-row" key={p.contract}><div className="market-identity"><strong>{p.symbol}</strong><span>{p.underlying} · {p.category} · {p.issuer==='ondo'?'Ondo':'bStocks'}</span></div><div className="market-price"><span>Recorded token price</span><strong>{hasPrice?money(recorded!.tokenPrice!):'Unknown'}</strong><small>{hasPrice?'Not a current buy quote':catalogue?.stale?'Stale frame hidden':'No price observation'}</small></div><div className="market-route"><span>Current route</span><strong>{p.symbol==='SPYon'?'Check with wallet':'No verified trade route'}</strong><small>{p.symbol==='SPYon'?'Capped SPYon path':'Research only'}</small></div><Link href={`/asset/${p.symbol}`} aria-label={`Inspect ${p.symbol}`}>Inspect token <span aria-hidden="true">↗</span></Link></article>;})}</div>}
  <p className="product-fine market-limit">A recorded token price is not the underlying stock reference, a live route, a fill, or permission to trade. Mandate checks those separately where a route is available.</p>
 </>;
}
