'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import RegimeView,{type CostReview,CostReviewEvidence} from '../../regime';

type Fact={value:string;source:string;checkedAt:string;scope:string};
type Passport={symbol:string;underlying:string;issuer:string;contract:string;chainId:number;category:string;leveraged:boolean;facts:Record<string,Fact>;unknowns:string[];profile:{state:string;observedAt:string|null;underlyingName:string|null;tokenToShareRatio:string|null}};
type Recorded={symbol:string;tokenPrice:string|null;marketDataState:string;reportedStatus:string};
type Catalogue={stale:boolean;observedAt:string|null;items:Recorded[]};
type Tab='overview'|'history'|'details';
const formatPrice=(value:string)=>{const number=Number(value);return Number.isFinite(number)?'$'+new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(number):'Unknown';};
const date=(value:string)=>new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});

export default function AssetClient({symbol}:{symbol:string}){
 const [passport,setPassport]=useState<Passport|null>(null),[catalogue,setCatalogue]=useState<Catalogue|null>(null),[review,setReview]=useState<CostReview|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[tab,setTab]=useState<Tab>('overview'),[showFullHistory,setShowFullHistory]=useState(false);
 useEffect(()=>{if(location.hash==='#history')setTab('history');else if(location.hash==='#details')setTab('details');},[]);
 useEffect(()=>{const controller=new AbortController();(async()=>{try{const [source,recorded]=await Promise.all([fetch('/api/v1/instruments/passports',{signal:controller.signal,cache:'no-store'}),fetch('/api/v1/instruments',{signal:controller.signal,cache:'no-store'})]);if(!source.ok||!recorded.ok)throw new Error('Token facts could not be loaded.');const [p,c]=await Promise.all([source.json(),recorded.json()]);const selected=(p.items as Passport[]).find(item=>item.symbol.toLowerCase()===symbol.toLowerCase());if(!selected){setError('This token is not in Mandate’s sourced token list.');return;}setPassport(selected);setCatalogue(c);const response=await fetch(`/api/v1/cost-review?ticker=${encodeURIComponent(selected.underlying)}&platform=${encodeURIComponent(selected.issuer)}&side=buy&usd=10000`,{signal:controller.signal,cache:'no-store'});if(response.ok)setReview(await response.json());}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[symbol]);
 if(loading)return <div className="product-empty" role="status">Loading token facts and recorded cost evidence…</div>;
 if(error||!passport)return <div className="product-empty" role="alert">{error||'Token unavailable.'} <Link href="/market">Return to Explore</Link></div>;
 const recorded=catalogue?.items.find(item=>item.symbol.toLowerCase()===passport.symbol.toLowerCase());
 const usablePrice=!catalogue?.stale&&recorded?.marketDataState==='OBSERVED'&&recorded.tokenPrice!==null;
 const isPilot=passport.symbol==='SPYon';
 return <>
  <Link className="asset-back" href="/market">← Explore tokens</Link>
  <div className="asset-heading"><div><p className="product-eyebrow">{passport.issuer==='ondo'?'Ondo':'bStocks'} · BNB Smart Chain · {passport.category}</p><h1>{passport.symbol}</h1><p>{passport.profile.underlyingName??`${passport.underlying} exposure`} · tokenized exposure, not direct ownership of the underlying security.</p></div><span className={`product-state ${catalogue?.stale?'stale':''}`}>{catalogue?.stale?'STALE SOURCE':'SOURCED IDENTITY'}</span></div>
  <div className="asset-decision"><div><span className="asset-micro">THE TOKEN</span><strong>{passport.underlying}</strong><small>Underlying tracked</small></div><div><span className="asset-micro">RECORDED TOKEN PRICE</span><strong>{usablePrice?formatPrice(recorded!.tokenPrice!):'Unknown'}</strong><small>{usablePrice&&catalogue?.observedAt?`Collector frame ${date(catalogue.observedAt)}`:catalogue?.stale?'Stale frame hidden':'No price observation'}</small></div><div><span className="asset-micro">CURRENT ROUTE</span><strong>{isPilot?'Check with wallet':'No verified trade route'}</strong><small>{isPilot?'Fresh quote, wallet and rule checks required':'No certified execution path for this token'}</small></div></div>
  <p className="asset-warning">The recorded token price is neither the underlying reference price nor an executable buy quote. Mandate never uses it to authorize a trade.</p>
  <div className="asset-actions">{isPilot?<Link className="product-button" href="/plan/SPYon">Check SPYon route</Link>:<span className="product-state unknown">Research only</span>}<button type="button" className="asset-text-action" onClick={()=>setTab('history')}>Inspect recorded cost →</button></div>
  <div className="asset-tabs" role="tablist" aria-label="Token research sections">{([['overview','Overview'],['history','Cost history'],['details','Token details']] as [Tab,string][]).map(([key,label])=><button role="tab" aria-selected={tab===key} type="button" key={key} onClick={()=>setTab(key)}>{label}</button>)}</div>
  {tab==='overview'&&<div className="asset-overview"><section><p className="product-eyebrow">What to verify</p><h2>Know the route before deciding.</h2><p>The issuer, token contract and underlying are research facts. A current route check must separately establish its price, pool, wallet funds, spending permission and simulation result.</p><ol><li>Confirm this token and its issuer.</li><li>Compare a fresh route with a fresh reference.</li><li>Check your wallet and protected cash.</li><li>Review any wallet request separately.</li></ol></section><section><p className="product-eyebrow">Recorded evidence</p><h2>{review?.observation==='measured'?'A historical cost exists.':'No matching measured cost.'}</h2><p>{review?.observation==='measured'?'The observation below is dated and cannot price a purchase now.':'This token/issuer/size has no matching recorded cost. Mandate leaves that gap visible.'}</p>{review?<CostReviewEvidence review={review}/>:<p>Cost evidence is unavailable.</p>}</section></div>}
  {tab==='history'&&<div id="history" className="asset-history"><p className="product-fine">Recorded quotes are historical observations. Missing rows are not zero-cost routes.</p><section className="asset-history-summary"><p className="product-eyebrow">Latest matching recorded attempt</p><h2>{review?.observation==='measured'?'Measured cost, with original source':'No current measured cost'}</h2><p>The latest matching $10,000 buy research is evidence from its timestamp. It cannot price or authorize a purchase now.</p>{review?<CostReviewEvidence review={review}/>:<p>The matching source is unavailable.</p>}</section><button className="asset-text-action" type="button" aria-expanded={showFullHistory} onClick={()=>setShowFullHistory(value=>!value)}>{showFullHistory?'Hide full research history':'Explore full research history →'}</button>{showFullHistory&&<RegimeView initialToken={passport.underlying} initialPlatform={passport.issuer}/>}</div>}
  {tab==='details'&&<div id="details" className="asset-details"><div><p className="product-eyebrow">Sourced identity</p><h2>What this token represents</h2><dl><div><dt>Issuer</dt><dd>{passport.issuer==='ondo'?'Ondo':'bStocks'}</dd></div><div><dt>Underlying</dt><dd>{passport.underlying}</dd></div><div><dt>Contract · BNB Chain</dt><dd><code>{passport.contract}</code></dd></div><div><dt>Profile status</dt><dd>{passport.profile.state}{passport.profile.observedAt?` · observed ${date(passport.profile.observedAt)}`:''}</dd></div></dl><p className="product-fine">Token/share ratio: {passport.profile.state==='OBSERVED'?passport.profile.tokenToShareRatio??'Unknown':'Unknown until a fresh validated profile'}. A stale ratio is not used as a current holding multiplier.</p></div><details><summary>Issuer facts, sources and remaining unknowns</summary><dl>{Object.entries(passport.facts).map(([name,fact])=><div key={name}><dt>{name}</dt><dd>{fact.value}<br/><a href={fact.source} target="_blank" rel="noreferrer">Primary source ↗</a> · checked {fact.checkedAt}</dd></div>)}</dl><h3>Still unknown</h3><ul>{passport.unknowns.map(value=><li key={value}>{value}</li>)}</ul></details></div>}
 </>;
}
